Repository Azure/LogicAppsUX, pull requests merged in 2023-05, with the labels that each got.

#2206 fix(designer): Dynamic content was incorrectly cached for swagger based operations
  libs/designer/src/lib/core/queries/connector.ts
  libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
  libs/services/designer-client-services/src/lib/base/connector.ts
  libs/services/designer-client-services/src/lib/connector.ts
Labels: BREAKING

#2235 fix(designer): Use skipValidation to skip throwing errors in serializeWorkflow
  apps/vs-code-designer-react/src/app/DesignerCommandBar/index.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
Labels: BREAKING

#2392 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 536
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: ConventionalCommitMessage

#2403 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 537
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: ConventionalCommitMessage

#2523 fix(designer): Fixed connections with non-optional gateway parameters
  libs/designer-ui/src/lib/createConnection/index.tsx
Labels: ConventionalCommitMessage

#2572 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 544
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: ConventionalCommitMessage

#2623 chore: Added Trouble Shooting Guide to documentation site
  .github/workflows/Deploy-Documentation.yml
  apps/logic-apps-ux-docs/docs/img/tsg/knownIssuesExample_dark.png
  apps/logic-apps-ux-docs/docs/img/tsg/knownIssuesExample_light.png
  apps/logic-apps-ux-docs/docs/img/tsg/portalVersionBox.png
  apps/logic-apps-ux-docs/docs/tsg.mdx
  apps/logic-apps-ux-docs/src/css/custom.css
  package.json
Labels: Documentation

#2579 feat(Power Automate): Added data automation ids for main designer components for use in automated testing
  libs/designer-ui/src/lib/actionbuttonv2/index.tsx
  libs/designer-ui/src/lib/card/__test__/__snapshots__/card.spec.tsx.snap
  libs/designer-ui/src/lib/card/addActionCard/index.tsx
  libs/designer-ui/src/lib/card/index.tsx
  libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheader.spec.tsx.snap
  libs/designer-ui/src/lib/panel/panelheader/panelheader.tsx
  libs/designer-ui/src/lib/panel/panelpivot.tsx
  libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchCard/index.tsx
  libs/designer-ui/src/lib/searchbox/index.tsx
  libs/designer-ui/src/lib/utils/utils.ts
  libs/designer/src/lib/ui/connections/dropzone.tsx
Labels: Test Changes

#2583 feat(Power Automate): Add automation ids for editors and token picker components
  libs/designer-ui/src/lib/editor/base/plugins/tokenpickerbutton/index.tsx
  libs/designer-ui/src/lib/expressioneditor/index.tsx
  libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
  libs/designer-ui/src/lib/token/inputToken.tsx
  libs/designer-ui/src/lib/tokenpicker/index.tsx
  libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx
  libs/designer-ui/src/lib/tokenpicker/tokenpickerheader.tsx
  libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickeroption.tsx
Labels: Test Changes
