Repository Azure/LogicAppsUX, pull requests merged in 2023-08, with the labels that each got.

#3090 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 597
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: ConventionalCommitMessage

#3174 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230822000653402 to main
  Localize/loc/ja/strings.json.lcl
Labels: auto-localization-update, ConventionalCommitMessage

#3190 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 611
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: ConventionalCommitMessage

#3201 feat(designer): Adding search service 2 to allow for custom search results
  libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchHeader/index.tsx
  libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
  libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
  libs/services/designer-client-services/src/lib/search.ts
  libs/utils/src/lib/models/connector.ts
Labels: BREAKING

#3217 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20230830001010264 to main
  Localize/loc/de/strings.json.lcl
  Localize/loc/es/strings.json.lcl
  Localize/loc/fr/strings.json.lcl
  Localize/loc/hu/strings.json.lcl
  Localize/loc/id/strings.json.lcl
  Localize/loc/ko/strings.json.lcl
  Localize/loc/nl/strings.json.lcl
  Localize/loc/pt-BR/strings.json.lcl
  Localize/loc/pt-PT/strings.json.lcl
  Localize/loc/ru/strings.json.lcl
  Localize/loc/sv/strings.json.lcl
  Localize/loc/tr/strings.json.lcl
  Localize/loc/zh-Hans/strings.json.lcl
  Localize/loc/zh-Hant/strings.json.lcl
Labels: ConventionalCommitMessage
