Repository Azure/LogicAppsUX, pull requests merged in 2025-02, with the labels that each got.

#6534 feat(designer): Introduce collapse node route
  Localize/lang/strings.json
  e2e/designer/collapseActions.spec.ts
  libs/designer-ui/src/lib/card/card.less
  libs/designer-ui/src/lib/card/collapsedCard/__test__/__snapshots__/collapsedCard.spec.tsx.snap
  libs/designer-ui/src/lib/card/collapsedCard/__test__/collapsedCard.spec.tsx
  libs/designer-ui/src/lib/card/collapsedCard/collapsedCard.less
  libs/designer-ui/src/lib/card/collapsedCard/index.tsx
  libs/designer-ui/src/lib/index.ts
  libs/designer/src/lib/core/state/operation/operationSelector.ts
  libs/designer/src/lib/core/state/workflow/__test__/helper.spec.ts
  libs/designer/src/lib/core/state/workflow/helper.ts
  libs/designer/src/lib/core/state/workflow/workflowInterfaces.ts
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
  libs/designer/src/lib/ui/CanvasFinder.tsx
  libs/designer/src/lib/ui/CustomNodes/CollapsedCardNode.tsx
  libs/designer/src/lib/ui/CustomNodes/__test__/CollapsedCardNode.spec.tsx
  libs/designer/src/lib/ui/CustomNodes/__test__/__snapshots__/CollapsedCardNode.spec.tsx.snap
  libs/designer/src/lib/ui/Designer.tsx
  libs/designer/src/lib/ui/Minimap.tsx
  libs/designer/src/lib/ui/common/DesignerContextualMenu/DesignerContextualMenu.tsx
  libs/designer/src/lib/ui/common/DesignerContextualMenu/Priorities.tsx
  libs/designer/src/lib/ui/menuItems/__test__/__snapshots__/collapseMenuItem.spec.tsx.snap
  libs/designer/src/lib/ui/menuItems/__test__/collapseMenuItem.spec.tsx
  libs/designer/src/lib/ui/menuItems/collapseMenuItem.tsx
  libs/designer/src/lib/ui/menuItems/index.tsx
  libs/logic-apps-shared/src/utils/src/lib/models/workflowNode.ts
Labels: Risk:Medium

#6599 Fix(Data Mapper): extra '/' added to custom values on for/if
  libs/data-mapper-v2/src/mapHandling/MapDefinitionDeserializer.ts
  libs/data-mapper-v2/src/mapHandling/__test__/MapDefinitionDeserializer.spec.ts
Labels: Risk:Low

#6583 feat(Designer): Local caching of manifests / connectors / swaggers
  apps/Standalone/package.json
  apps/Standalone/src/dataMapperV1/components/DevToolbox.tsx
  apps/Standalone/src/dataMapperV1/mapDefinitions/X12Definition.ts
  apps/Standalone/src/dataMapperV1/mapDefinitions/index.ts
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
  apps/Standalone/src/designer/app/DesignerShell/designer.tsx
  apps/Standalone/src/designer/app/SettingsSections/contextSettings.tsx
  apps/Standalone/src/designer/state/workflowLoadingSelectors.ts
  apps/Standalone/src/designer/state/workflowLoadingSlice.ts
  apps/vs-code-react/package.json
  e2e/designer/queryCache.spec.ts
  libs/data-mapper-v2/src/utils/Schema.Utils.ts
  libs/data-mapper/src/lib/utils/MapDefinition.Utils.ts
  libs/designer-ui/package.json
  libs/designer-ui/src/lib/templates/templatesFilterDropdown.tsx
  libs/designer/package.json
  libs/designer/src/lib/core/ReactQueryProvider.tsx
  libs/designer/src/lib/ui/panel/runHistoryPanel/statusIndicator.tsx
  libs/logic-apps-shared/package.json
  libs/vscode-extension/package.json
  pnpm-lock.yaml
Labels: Performance, Risk:Low

#6619 fix(vscode): Fix build and test errors for dev branch
  apps/vs-code-designer/test-setup.ts
  libs/designer-ui/src/lib/unitTesting/conditionExpression/index.tsx
  libs/designer-ui/src/lib/unitTesting/outputMocks/errorDetails.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
Labels: Risk:Low

#6598 feat(designer): Add info message for request trigger type
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
  e2e/designer/operationPanel.spec.ts
  libs/data-mapper/src/lib/components/notification/Notification.tsx
  libs/designer-ui/src/lib/panel/panel.less
  libs/designer-ui/src/lib/panel/panelcontainer.tsx
  libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheader.spec.tsx.snap
  libs/designer-ui/src/lib/panel/panelheader/__test__/panelheader.spec.tsx
  libs/designer-ui/src/lib/panel/panelheader/panelheader.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/__test__/initialize.spec.ts
  libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/connector.ts
  libs/logic-apps-shared/src/designer-client-services/lib/workflow.ts
Labels: Risk:Low

#6624 fix(Designer): Fixed nested loop monitoring view issues
  e2e/designer/fixtures/real-api.ts
  e2e/designer/real-api/monitoring/NestedLoops/nestedLoops.spec.ts
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
  libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
Labels: Risk:Low

#6627 fix(Designer): Fixed nested loop monitoring view issues (#6624)
  e2e/designer/fixtures/real-api.ts
  e2e/designer/real-api/monitoring/NestedLoops/nestedLoops.spec.ts
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
  libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
Labels: Risk:Low

#6605 feat(templates): Adding support for dynamic list and file/folder picker in template parameters
  apps/Standalone/src/templates/app/TemplatesConsumption.tsx
  apps/Standalone/src/templates/app/TemplatesShell.tsx
  apps/Standalone/src/templates/app/TemplatesStandard.tsx
  libs/designer-ui/src/lib/arrayeditor/index.tsx
  libs/designer-ui/src/lib/authentication/index.tsx
  libs/designer-ui/src/lib/combobox/index.tsx
  libs/designer-ui/src/lib/dictionary/index.tsx
  libs/designer-ui/src/lib/editor/base/index.tsx
  libs/designer-ui/src/lib/editor/index.ts
  libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
  libs/designer/src/lib/core/queries/connections.ts
  libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
  libs/designer/src/lib/core/state/templates/store.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/core/state/templates/templateselectors.ts
  libs/designer/src/lib/core/templates/TemplatesDesignerContext.tsx
  libs/designer/src/lib/core/templates/utils/__test__/mocks.ts
  libs/designer/src/lib/core/templates/utils/__test__/parametershelper.spec.ts
  libs/designer/src/lib/core/templates/utils/parametershelper.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/designer/src/lib/core/utils/swagger/operation.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
  libs/designer/src/lib/ui/panel/templatePanel/__tests__/parametersTab.spec.tsx
  libs/designer/src/lib/ui/templates/__tests__/displayParameters.spec.tsx
  libs/designer/src/lib/ui/templates/parameters/displayParameters.tsx
  libs/designer/src/lib/ui/templates/parameters/parametereditor.tsx
  libs/designer/src/lib/ui/templates/templateslist.tsx
  libs/designer/src/lib/ui/templates/templateview.tsx
  libs/logic-apps-shared/src/utils/src/lib/models/template.ts
Labels: Risk:Low

#6634 docs(vscode): Add Cloud to Local feature announcement
  apps/vs-code-designer/src/README.md
Labels: Risk:Low

#6636 fix(Designer): Fixes an issue where '\"' causing json errors in expressions
  e2e/designer/tokens/escapeExpressionTokens.spec.ts
  libs/designer-ui/src/lib/tokenpicker/tokenpickerfooter.tsx
  libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Labels: Risk:Low

#6580 feat(vscode): Add Unit Test Generation Classes for Workflow Run
  apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForLocal.ts
  apps/vs-code-designer/src/app/commands/workflows/unitTest/__test__/saveBlankUnitTest.test.ts
  apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
  apps/vs-code-designer/src/app/commands/workflows/unitTest/saveBlankUnitTest.ts
  apps/vs-code-designer/src/app/utils/__test__/UnitTesting/unitTestUtils.test.ts
  apps/vs-code-designer/src/app/utils/codeful/__test__/saveBlankUnitTest.test.ts
  apps/vs-code-designer/src/app/utils/codeful/__test__/unitTestUtils.test.ts
  apps/vs-code-designer/src/app/utils/unitTests.ts
  apps/vs-code-designer/src/assets/UnitTestTemplates/TestClassFile
  apps/vs-code-designer/test-setup.ts
  apps/vs-code-react/src/app/designer/DesignerCommandBar/index.tsx
Labels: Risk:Low

#6641 fix(vscode): Bug with path separator in local tests
  apps/vs-code-designer/src/app/utils/tree/__test__/assets.test.ts
Labels: Risk:Low

#6649 fix(vscode): Add workflow and logic app creation back to azure blade
  apps/vs-code-designer/src/package.json
Labels: Risk:Low

#6639 feat(Data Mapper): custom code
  Localize/lang/strings.json
  apps/Standalone/src/dataMapperV1/app/DataMapperStandaloneDesignerV2.tsx
  apps/vs-code-designer/src/app/commands/dataMapper/DataMapperPanel.ts
  apps/vs-code-react/src/run-service/types.ts
  apps/vs-code-react/src/state/DataMapSliceV2.ts
  apps/vs-code-react/src/webviewCommunication.tsx
  libs/data-mapper-v2/src/__test__/redux-test-helper-dm.tsx
  libs/data-mapper-v2/src/components/common/fileDropdownTree/FileDropdownTree.tsx
  libs/data-mapper-v2/src/components/common/fileDropdownTree/__test__/FileDropdownTree.spec.tsx
  libs/data-mapper-v2/src/components/common/selector/FileSelector.tsx
  libs/data-mapper-v2/src/components/common/selector/__test__/FileSelector.spec.tsx
  libs/data-mapper-v2/src/components/common/styles.ts
  libs/data-mapper-v2/src/components/fileDropdown/fileDropdown.tsx
  libs/data-mapper-v2/src/components/functionConfigurationMenu/functionConfigurationPopover.tsx
  libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/inputTab.tsx
  libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/inputTextbox.tsx
  libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/styles.tsx
  libs/data-mapper-v2/src/components/functionConfigurationMenu/inputTab/xsltFilePicker.tsx
  libs/data-mapper-v2/src/components/functionConfigurationMenu/styles.ts
  libs/data-mapper-v2/src/components/schema/SchemaPanelBody.tsx
  libs/data-mapper-v2/src/core/DataMapDataProvider.tsx
  libs/data-mapper-v2/src/core/state/FunctionSlice.ts
  libs/data-mapper-v2/src/core/state/Store.ts
  libs/data-mapper-v2/src/utils/Function.Utils.ts
  libs/vscode-extension/src/lib/models/dataMapper.ts
  libs/vscode-extension/src/lib/models/extensioncommand.ts
  package.json
  pnpm-lock.yaml
Labels: Risk:Medium

#6645 fix(vscode): bug where DateTime properties have invalid type in generated unit…
  apps/vs-code-designer/src/app/utils/__test__/UnitTesting/unitTestUtils.test.ts
  apps/vs-code-designer/src/app/utils/unitTests.ts
Labels: Risk:Low

#6657 fix(vscode): Create Unique Configuration Names
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/initLogicAppCodeProjectVScode/InitCodeProject.ts
  apps/vs-code-designer/src/app/commands/initProjectForVSCode/InitVSCodeStepBase.ts
Labels: Risk:Low

#6664 chore(templates): Updating templates repo for new release
  downloadTemplates.js
Labels: Risk:Low

#6665 chore(templates): Updating templates repo for new release
  downloadTemplates.js
Labels: Risk:Low

#6666 fix(designer): Dictionary Editor to not use string interpolation for tokens if ANY value type
  e2e/designer/editors/dictionary.spec.ts
  libs/designer-ui/src/lib/editor/base/utils/helper.ts
  libs/designer-ui/src/lib/editor/base/utils/keyvalueitem.ts
Labels: Risk:Low

#6662 Feat(VSCode): added docs around new telemetry collection
  apps/docs/docs/Development/Kusto.md
  apps/docs/docs/img/aiKustoFlow.png
Labels: Risk:Low

#6684 chore(standalone): Add sorting and fix valid resource regex
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureConsumptionLogicAppSelector.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureStandardLogicAppSelector.tsx
Labels: Risk:Low

#6690 fix(vscode): Add validation for workspace and logic app name
  apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/ScriptSteps/ScriptWorkflowNameStep.ts
  apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/WorkflowNameStepBase.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/SetLogicAppNameStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/SetWorkspaceName.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/setMethodName.ts
  apps/vs-code-designer/src/constants.ts
Labels: Risk:Low

#6696 feat(designer): Support parsedocumentwithmetadat in standard
  libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
Labels: Risk:Low

#6687 feat(designer): Adding Password Masking to Authentication Editors
  Localize/lang/strings.json
  e2e/designer/editors/password.spec.ts
  libs/designer-ui/src/lib/authentication/AADOAuth/AADOAuth.tsx
  libs/designer-ui/src/lib/authentication/AADOAuth/AADOAuthCredentials.tsx
  libs/designer-ui/src/lib/authentication/AuthenticationProperty.tsx
  libs/designer-ui/src/lib/authentication/BasicAuth.tsx
  libs/designer-ui/src/lib/authentication/CertificateAuth.tsx
  libs/designer-ui/src/lib/authentication/CollapsedAuthentication.tsx
  libs/designer-ui/src/lib/authentication/MSIAuth/MSIAuth.tsx
  libs/designer-ui/src/lib/authentication/MSIAuth/MSIAuthDefault.tsx
  libs/designer-ui/src/lib/authentication/RawAuth.tsx
  libs/designer-ui/src/lib/authentication/authentication.less
  libs/designer-ui/src/lib/authentication/index.tsx
  libs/designer-ui/src/lib/dictionary/expandeddictionary.tsx
  libs/designer-ui/src/lib/editor/base/EditorWrapper.tsx
  libs/designer-ui/src/lib/editor/base/index.tsx
  libs/designer-ui/src/lib/editor/base/nodes/passwordNode.tsx
  libs/designer-ui/src/lib/editor/base/plugins/PasswordMaskPlugin.tsx
  libs/designer-ui/src/lib/editor/base/utils/editorToSegment.ts
  libs/designer-ui/src/lib/editor/base/utils/helper.ts
  libs/designer-ui/src/lib/editor/base/utils/initialConfig.ts
  libs/designer-ui/src/lib/editor/base/utils/parsesegments.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
Labels: Risk:Low

#6698 fix(vscode): Fix nuget debug issue introduced with workspace
  apps/vs-code-designer/src/app/commands/initProjectForVSCode/DotnetInitVSCodeStep.ts
  apps/vs-code-designer/src/app/commands/initProjectForVSCode/InitVSCodeStepBase.ts
  apps/vs-code-designer/src/app/commands/initProjectForVSCode/ScriptInitVSCodeStep.ts
Labels: Risk:Low

#6686 fix(Designer): Fixed loop causing rerender in monitoring view
  e2e/designer/real-api/monitoring/NestedLoops/nestedLoops.spec.ts
  libs/designer/src/lib/core/store.ts
  libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
  playwright.config.ts
Labels: Risk:Low

#6699 fix(Designer): Fixed loop causing rerender in monitoring view (v5.44)
  e2e/designer/real-api/monitoring/NestedLoops/nestedLoops.spec.ts
  libs/designer/src/lib/core/store.ts
  libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
  playwright.config.ts
Labels: Risk:Low

#6700 fix(vscode): automated testing bug in config workspace path and C# class generation
  apps/vs-code-designer/src/app/utils/__test__/UnitTesting/unitTestUtils.test.ts
  apps/vs-code-designer/src/app/utils/unitTests.ts
Labels: Risk:Low

#6697 Feat(Data Mapper): dark theme
  libs/data-mapper-v2/src/components/codeView/styles.ts
  libs/data-mapper-v2/src/components/commandBar/styles.ts
  libs/data-mapper-v2/src/components/common/panel/styles.ts
  libs/data-mapper-v2/src/components/common/reactflow/edges/ConnectedEdge.tsx
  libs/data-mapper-v2/src/components/common/reactflow/edges/ConnectionLine.tsx
  libs/data-mapper-v2/src/components/common/reactflow/styles.ts
  libs/data-mapper-v2/src/components/common/styles.ts
  libs/data-mapper-v2/src/components/functionConfigurationMenu/styles.ts
  libs/data-mapper-v2/src/components/functionList/styles.tsx
  libs/data-mapper-v2/src/components/functionsPanel/styles.ts
  libs/data-mapper-v2/src/components/mapChecker/styles.tsx
  libs/data-mapper-v2/src/components/schema/styles.ts
  libs/data-mapper-v2/src/components/schema/tree/styles.ts
  libs/data-mapper-v2/src/components/test/styles.ts
  libs/data-mapper-v2/src/constants/FunctionConstants.tsx
  libs/data-mapper-v2/src/core/ThemeConect.ts
  libs/data-mapper-v2/src/ui/styles.ts
Labels: Risk:Low

#6705 fix(vscode): Adjust Folder Insertion to End of Workspace
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/__test__/FileManagement.test.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/iacGestureHelperFunctions.ts
  apps/vs-code-designer/test-setup.ts
Labels: Risk:Low
