Repository Azure/LogicAppsUX, pull requests merged in 2025-09, with the labels that each got.

#8190 fix(vscode): Changed validate call on workflow save to use saved data instead of panel metadata
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
Labels: Risk:Low, needs-pr-update

#8198 feat(VSCode): VSCode view switching
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBarV2.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerV2.tsx
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
  apps/vs-code-react/package.json
  apps/vs-code-react/src/app/designer/CodeViewEditor/index.tsx
  apps/vs-code-react/src/app/designer/DesignerCommandBar/indexV2.tsx
  apps/vs-code-react/src/app/designer/DesignerCommandBar/styles.ts
  apps/vs-code-react/src/app/designer/appV2.tsx
  apps/vs-code-react/src/app/designer/constants.ts
  apps/vs-code-react/src/app/designer/servicesHelper.ts
  apps/vs-code-react/src/app/designer/utilities/workflow.ts
  apps/vs-code-react/src/router/index.tsx
  libs/designer-v2/src/lib/core/queries/runs.ts
  libs/designer-v2/src/lib/ui/FloatingRunButton/index.tsx
  libs/designer-v2/src/lib/ui/index.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/browse/connectorBrowse.tsx
  libs/designer-v2/src/lib/ui/panel/runHistoryPanel/runHistoryPanel.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/logicapps.ts
  libs/vscode-extension/src/lib/models/extensioncommand.ts
  libs/vscode-extension/src/lib/services/httpClient.ts
  pnpm-lock.yaml
Labels: Risk:Medium, pr-validated

#8202 feat(Designer): Run with payload popover
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBarV2.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/HttpClient.ts
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerV2.tsx
  apps/vs-code-react/src/app/designer/appV2.tsx
  libs/designer-ui/src/lib/settings/settingsection/index.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/card.styles.ts
  libs/designer-v2/src/lib/ui/FloatingRunButton/index.tsx
  libs/designer-v2/src/lib/ui/FloatingRunButton/payloadPopover.tsx
  libs/designer-v2/src/lib/ui/FloatingRunButton/styles.tsx
  libs/designer-v2/src/lib/ui/connections/addButton/addButton.styles.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
  libs/vscode-extension/src/lib/services/httpClient.ts
Labels: Risk:Low, pr-validated

#8204 feat(DesignerV2): Card error badge, Scope cards
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBarV2.tsx
  apps/vs-code-react/src/app/designer/DesignerCommandBar/styles.ts
  libs/designer-v2/src/lib/ui/CustomNodes/OperationCardNode.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/ScopeCardNode.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/actionCard.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/card.styles.ts
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/cardErrorBadge.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/cardRunStatusBadge.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/collapseToggle.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/index.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/svgs/error.svg
Labels: Risk:Low, pr-validated

#8220 chore(Designer): Added E2E test to verify auth type switching + params
  e2e/designer/real-api/connections/connectionAuth.spec.ts
Labels: Risk:Low, pr-validated

#8214 feat(designer-v2): add dark mode support for floating chat button
  apps/vs-code-react/src/app/designer/appV2.tsx
  apps/vs-code-react/src/app/designer/services/workflowService.ts
  libs/designer-v2/src/lib/ui/FloatingRunButton/floatingChat.tsx
  libs/designer-v2/src/lib/ui/FloatingRunButton/index.tsx
Labels: Risk:Low, pr-validated

#8252 feat(vscode): disable codeful feature flag
  apps/vs-code-designer/src/main.ts
Labels: Risk:Low, pr-validated

#8261 fix(vs-code): prevent null error in Logic App AppInsights creation
  apps/vs-code-designer/src/app/commands/createProject/createProjectSteps/projectTypeStep.ts
  apps/vs-code-designer/src/app/tree/subscriptionTree/subscriptionTreeItem.ts
Labels: Risk:Low, pr-validated

#8262 chore(vscode): add production signing configuration to pipeline
  .azure-pipelines/1esmain.yml
Labels: Risk:Low, pr-validated

#8263 chore(vscode): add production signing configuration to pipeline #8262
  .azure-pipelines/1esmain.yml
Labels: Risk:Low, pr-validated

#8266 chore: Update release pipeline to use Github_Token instead of personal PAT
  .github/workflows/version-release.yml
Labels: Risk:Low, pr-validated

#8268 chore: Update release pipeline to use Github_Token instead of personal PAT
  .github/workflows/version-release.yml
Labels: Risk:Low, pr-validated

#8275 feat(DesignerV2): Add markdown Notes to DesignerV2, including YouTube embeds and color customization
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Models/Workflow.ts
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerV2.tsx
  apps/Standalone/src/mcp/app/McpStandard.tsx
  apps/Standalone/src/templates/app/TemplatesStandard.tsx
  libs/designer-v2/src/lib/common/models/workflow.ts
  libs/designer-v2/src/lib/core/actions/bjsworkflow/serializer.ts
  libs/designer-v2/src/lib/core/parsers/ParseReduxAction.ts
  libs/designer-v2/src/lib/core/state/designerView/designerViewInterfaces.ts
  libs/designer-v2/src/lib/core/state/global.ts
  libs/designer-v2/src/lib/core/state/notes/notesSelectors.ts
  libs/designer-v2/src/lib/core/state/notes/notesSlice.ts
  libs/designer-v2/src/lib/core/state/undoRedo/undoRedoTypes.ts
  libs/designer-v2/src/lib/core/store.ts
  libs/designer-v2/src/lib/core/utils/graph.ts
  libs/designer-v2/src/lib/core/utils/undoredo.ts
  libs/designer-v2/src/lib/ui/CustomNodes/NoteNode/NoteColorButton.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/NoteNode/NoteMarkdownRenderer.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/NoteNode/NoteNode.styles.ts
  libs/designer-v2/src/lib/ui/CustomNodes/NoteNode/index.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/actionCard.tsx
  libs/designer-v2/src/lib/ui/Designer.tsx
  libs/designer-v2/src/lib/ui/DesignerReactFlow.tsx
  libs/designer-v2/src/lib/ui/Minimap.tsx
  libs/designer-v2/src/lib/ui/common/DesignerContextualMenu/DesignerContextualMenu.tsx
  libs/designer-v2/src/lib/ui/menuItems/addNoteMenuItem.tsx
  libs/designer-v2/src/lib/ui/styles.less
  libs/designer/src/lib/ui/DesignerReactFlow.tsx
  libs/designer/src/lib/ui/Minimap.tsx
  libs/designer/src/lib/ui/styles.less
  libs/logic-apps-shared/src/utils/src/lib/models/helpers.ts
  libs/logic-apps-shared/src/utils/src/lib/models/workflowNode.ts
Labels: Risk:Low, pr-validated

#8281 fix(DesignerV2): Fixes httpclient response header property issue
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/HttpClient.ts
  libs/designer-v2/src/lib/ui/FloatingRunButton/index.tsx
  libs/vscode-extension/src/lib/services/httpClient.ts
Labels: Risk:Low, pr-validated

#8271 Add Agent Request Trigger for automated chat session integrations in Logic Apps Consumption Workflows
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/a2arequest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/agentloop.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/operationmanifest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/operations/agent.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/operations/index.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/operations/operationgroups.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/search.ts
Labels: pr-validated

#8283 fix(DesignerV2): Fixed react-flow `NoteNode` visibility and interaction issues
  libs/designer-ui/src/lib/styles.less
  libs/designer-v2/src/lib/ui/CustomNodes/NoteNode/index.tsx
  libs/designer-v2/src/lib/ui/DesignerReactFlow.tsx
  libs/designer-v2/src/lib/ui/styles.less
Labels: Risk:Low, pr-validated

#8291 fix(designer): Remove fluentui/azure-themes from designer repo
  libs/designer/src/lib/core/DesignerProvider.tsx
  libs/designer/src/lib/core/templates/TemplatesDesignerProvider.tsx
Labels: Risk:Low, pr-validated

#8299 fix(designer): Downgrade Lexical for Foundry Compatibility
  e2e/designer/editors/password.spec.ts
  libs/designer-ui/package.json
  libs/designer-ui/src/lib/editor/base/index.tsx
  libs/designer-ui/src/lib/html/plugins/toolbar/DropdownBlockFormat.tsx
  pnpm-lock.yaml
Labels: Risk:Low, pr-validated

#8301 chore(designer): Removing Monaco for Foundry Integration
  apps/Standalone/src/dataMapperV1/components/DevApiTester.tsx
  apps/Standalone/src/dataMapperV1/components/DevSerializationTester.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/CodeView.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/CodeViewV2.tsx
  apps/Standalone/src/designer/app/LocalDesigner/pseudoCommandBar.tsx
  e2e/designer/TokenPicker.spec.ts
  e2e/designer/editors/dictionary.spec.ts
  e2e/designer/tokens/escapeExpressionTokens.spec.ts
  e2e/designer/variables/multiVariable.spec.ts
  e2e/designer/variables/variableEditor.spec.ts
  libs/data-mapper-v2/src/components/codeView/CodeViewPanelBody.tsx
  libs/data-mapper-v2/src/components/test/TestPanelBody.tsx
  libs/data-mapper/src/lib/components/codeView/CodeView.tsx
  libs/data-mapper/src/lib/components/propertiesPane/tabs/CodeTab.tsx
  libs/data-mapper/src/lib/components/testMapPanel/TestMapPanel.tsx
  libs/designer-ui/package.json
  libs/designer-ui/src/lib/code/index.tsx
  libs/designer-ui/src/lib/editor/base/plugins/TokenPickerButtonLegacy.tsx
  libs/designer-ui/src/lib/editor/initializevariable/__test__/VariableEditor.spec.tsx
  libs/designer-ui/src/lib/editor/monaco/index.tsx
  libs/designer-ui/src/lib/expressioneditor/index.tsx
  libs/designer-ui/src/lib/index.ts
  libs/designer-ui/src/lib/peek/index.tsx
  libs/designer-ui/src/lib/schemaeditor/index.tsx
  libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
  libs/designer-ui/src/lib/tokenpicker/index.tsx
  libs/designer-ui/src/lib/tokenpicker/tokenpickerheader.tsx
  libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickeroption.tsx
  libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickersection.tsx
  libs/designer-ui/src/lib/unitTesting/conditionExpression/__tests__/__snapshots__/conditionExpression.spec.tsx.snap
  libs/designer-ui/src/lib/unitTesting/conditionExpression/index.tsx
  libs/designer-ui/src/lib/workflow/languageservice/workflowlanguageservice.ts
  libs/designer-v2/src/lib/ui/FloatingRunButton/payloadPopover.tsx
  libs/designer-v2/src/lib/ui/mcp/parameters/ParameterEditor.tsx
  libs/designer/src/lib/ui/mcp/parameters/ParameterEditor.tsx
  pnpm-lock.yaml
Labels: Risk:Medium, pr-validated

#8305 fix(Designer): Prevent Combining Variables Above Backend Max Variables Size
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerV2.tsx
  apps/Standalone/src/designer/state/workflowLoadingSlice.ts
  e2e/designer/variables/ensureInitializeVariable.spec.ts
  e2e/designer/variables/multiVariable.spec.ts
  e2e/designer/variables/variableEditor.spec.ts
  libs/designer-ui/src/lib/constants.ts
  libs/designer-ui/src/lib/editor/initializevariable/index.tsx
  libs/designer-v2/src/lib/core/parsers/ParseReduxAction.ts
  libs/designer/src/lib/core/parsers/ParseReduxAction.ts
  libs/logic-apps-shared/src/parsers/lib/common/constants.ts
Labels: Risk:Low, pr-validated
