Repository Azure/LogicAppsUX, pull requests merged in 2025-06, with the labels that each got.

#7403 docs: Update docs to be more extensive
  .github/copilot-instructions.md
  apps/docs/README.md
  apps/docs/docs/Development/Testing.md
  apps/docs/docs/Development/workflow.md
  apps/docs/docs/architecture.md
  apps/docs/docs/intro.md
  apps/docs/docs/troubleshooting.md
  apps/docs/docusaurus.config.ts
  apps/docs/package.json
  apps/docs/src/pages/markdown-page.md
  package.json
  pnpm-lock.yaml
Labels: Risk:Low

#7412 docs: Overhaul troubleshooting and accessibility documentation
  apps/docs/docs/Development/troubleshooting-dev.md
  apps/docs/docs/accessibility.mdx
  apps/docs/docs/powerautomate.md
  apps/docs/docs/troubleshooting.md
  apps/docs/docs/tsg.mdx
Labels: Risk:Low

#7415 feat(Designer): Added test over actions with special character names
  __mocks__/workflows/UnicodeKeys.json
  e2e/designer/unicodeCharacters.spec.ts
Labels: Risk:Low

#7417 fix(Templates): Tab navigation broken UI + Template card css overlapping issue
  libs/designer/src/lib/ui/templates/cards/templateCard.less
  libs/designer/src/lib/ui/templates/filters/templatesearchfilters.tsx
  libs/designer/src/lib/ui/templates/gallery/templatesfullgalleryview.tsx
Labels: Risk:Low

#7418 fix(Designer): Modified connector icon error log as warning
  libs/designer-ui/src/lib/panel/recommendationpanel/connectorAvatar/index.tsx
Labels: Risk:Low

#7419 fix(vscode): Bypass isMockable check for trigger mocks
  apps/vs-code-designer/src/app/utils/unitTests.ts
Labels: Risk:Low

#7320 test(designer): Adding redux state tests
  libs/designer/src/lib/core/state/__test__/designerViewSlice.spec.ts
  libs/designer/src/lib/core/state/__test__/devSlice.spec.ts
  libs/designer/src/lib/core/state/__test__/modalSlice.spec.ts
  libs/designer/src/lib/core/state/__test__/unitTestSlice.spec.ts
  pnpm-lock.yaml
Labels: Risk:Low

#7420 feat(styling): Migrate chatbot library from .less to Fluent UI v9 makeStyles
  CLAUDE.md
  LESS_TO_MAKESTYLES_MIGRATION_PLAN.md
  apps/vs-code-react/src/main.tsx
  libs/chatbot/src/index.ts
  libs/chatbot/src/lib/styles.less
  libs/chatbot/src/lib/styles.ts
  libs/chatbot/src/lib/ui/ChatbotUi.tsx
  libs/chatbot/src/lib/ui/panelheader.tsx
  libs/chatbot/src/lib/ui/styles.less
  libs/chatbot/src/lib/ui/styles.ts
  libs/designer-ui/src/lib/index.ts
  libs/designer-ui/src/lib/tokens/designTokens.ts
  libs/designer-ui/src/lib/tokens/index.ts
Labels: Risk:Low

#7421 feat(styling): Migrate Card and Panel components from LESS to Fluent UI v9 makeStyles
  LESS_TO_MAKESTYLES_MIGRATION_PLAN.md
  e2e/designer/monitoringView/monitoringView.spec.ts
  e2e/designer/operationPanel.spec.ts
  libs/data-mapper-v2/src/components/schema/style.less
  libs/designer-ui/src/lib/card/__test__/__snapshots__/card.spec.tsx.snap
  libs/designer-ui/src/lib/card/__test__/__snapshots__/cardfooter.spec.tsx.snap
  libs/designer-ui/src/lib/card/__test__/emptycontent.spec.tsx
  libs/designer-ui/src/lib/card/cardfooter.tsx
  libs/designer-ui/src/lib/card/collapsedCard/__test__/__snapshots__/collapsedCard.spec.tsx.snap
  libs/designer-ui/src/lib/card/collapsedCard/index.tsx
  libs/designer-ui/src/lib/card/emptycontent.tsx
  libs/designer-ui/src/lib/card/index.tsx
  libs/designer-ui/src/lib/card/scopeCard/index.tsx
  libs/designer-ui/src/lib/card/styles.ts
  libs/designer-ui/src/lib/panel/__test__/__snapshots__/panelContent.spec.tsx.snap
  libs/designer-ui/src/lib/panel/__test__/__snapshots__/panelcontainer.spec.tsx.snap
  libs/designer-ui/src/lib/panel/__test__/panelcontainer.spec.tsx
  libs/designer-ui/src/lib/panel/index.ts
  libs/designer-ui/src/lib/panel/panelcontainer.tsx
  libs/designer-ui/src/lib/panel/panelcontent.tsx
  libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheader.spec.tsx.snap
  libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheadercomment.spec.tsx.snap
  libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheadertitle.spec.tsx.snap
  libs/designer-ui/src/lib/panel/panelheader/__test__/panelheader.spec.tsx
  libs/designer-ui/src/lib/panel/panelheader/__test__/panelheadercomment.spec.tsx
  libs/designer-ui/src/lib/panel/panelheader/__test__/panelheadertitle.spec.tsx
  libs/designer-ui/src/lib/panel/panelheader/panelheader.tsx
  libs/designer-ui/src/lib/panel/panelheader/panelheadercomment.tsx
  libs/designer-ui/src/lib/panel/panelheader/panelheadertitle.tsx
  libs/designer-ui/src/lib/panel/styles.ts
  libs/designer-ui/src/lib/styles.less
  playwright.config.ts
Labels: Risk:Low

#7426 fix(vscode): Bypass isMockable check for trigger mocks (#7419)
  apps/vs-code-designer/src/app/utils/unitTests.ts
Labels: Risk:Low

#7424 chore: Update PR template for better context and automation
  .github/pull_request_template.md
  .github/workflows/RiskCheck.yml
  .github/workflows/pr-ai-validation.yml
  .github/workflows/pr-title-check.yml
Labels: Risk:Low, pr-validated

#7431 fix(designer): Fix C Sharp Custom Code Unable to Save Due to #
  libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Labels: Risk:Low

#7329 fix(Templates): Update release branch
  downloadTemplates.js
Labels: Risk:Low, needs-pr-update

#7434 Temporary fix of GeoLocation API version in VSCode until we can update vscode-azuretools
  apps/vs-code-designer/package.json
  apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/LogicAppHostingPlanStep.ts
  apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts
  apps/vs-code-designer/src/constants.ts
  pnpm-lock.yaml
Labels: Risk:Medium, pr-validated

#7437 fix(templates): Featured connectors and parameter definition fix cherry pick
  apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/configuretemplate/utils/helper.ts
Labels: Risk:Low

#7439 feat(VSCode): Temporary fix of GeoLocation API version in VSCode until we can update vscode-azuretools
  apps/vs-code-designer/package.json
  apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/LogicAppHostingPlanStep.ts
  apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts
  apps/vs-code-designer/src/constants.ts
  pnpm-lock.yaml
Labels: Risk:Medium

#7442 chore: Improve issue templates for better triage and consistency
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/ca11y.yml
  .github/ISSUE_TEMPLATE/data_mapper.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/templates.yml
Labels: pr-validated

#7445 fix(templates): Fixing query cache for template workflows to allow correct data saving
  apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
  e2e/templates/app.spec.ts
  libs/designer/src/lib/core/configuretemplate/utils/queries.ts
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/templates/gallery/templatesfullgalleryview.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/template.ts
Labels: pr-validated

#7448 fix(vscode): fix build custom code project task
  apps/vs-code-designer/src/app/commands/buildCustomCodeFunctionsProject.ts
  apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
Labels: Risk:Low

#7433 fix(vscode): Apim connector parameterization check fix (#7310)
  apps/vs-code-designer/src/app/utils/codeless/__test__/parameterizer.test.ts
  apps/vs-code-designer/src/app/utils/codeless/parameterizer.ts
Labels: Risk:Low

#7451 fix(Templates): Workflow tab, Template save, Accelarator loading issue
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
  libs/designer/src/lib/core/configuretemplate/utils/queries.ts
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/templateprofile/connectors.tsx
  libs/designer/src/lib/ui/templates/connections/connector.tsx
Labels: pr-validated

#7444 feat(templates): Adding new search filters for custom templates
  Localize/lang/strings.json
  apps/Standalone/src/templates/app/TemplatesConsumption.tsx
  apps/Standalone/src/templates/app/TemplatesStandard.tsx
  e2e/templates/app.spec.ts
  libs/designer-ui/src/lib/templates/templatesFilterDropdown.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
  libs/designer/src/lib/core/configuretemplate/ConfigureTemplateDataProvider.tsx
  libs/designer/src/lib/core/index.ts
  libs/designer/src/lib/core/state/templates/manifestSlice.ts
  libs/designer/src/lib/core/templates/TemplatesDataProvider.tsx
  libs/designer/src/lib/core/templates/utils/helper.ts
  libs/designer/src/lib/core/templates/utils/queries.ts
  libs/designer/src/lib/ui/templates/filters/templatesearchfilters.tsx
  libs/designer/src/lib/ui/templates/gallery/templatesfullgalleryview.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/template.ts
  libs/logic-apps-shared/src/designer-client-services/lib/template.ts
Labels: pr-validated

#7456 chore: Migrate from standard-version to tag-based releases
  .github/workflows/version-release.yml
  .versionrc
  VERSION_RELEASE_MIGRATION.md
  package.json
  pnpm-lock.yaml
  scripts/update-versions.js
Labels: pr-validated

#7458 Correct patch version calculation for hotfix branches
  .github/workflows/version-release.yml
  scripts/update-versions.js
Labels: pr-validated

#7459 fix(scripts): Add ES module __dirname equivalent for update-versions.js
  scripts/update-versions.js
Labels: pr-validated

#7462 chore: remove obsolete GitHub workflow files
  .github/workflows/base-coverage.yml
  .github/workflows/coverage-report.yml
  .github/workflows/production-build.yml
Labels: pr-validated

#7463 fix(templates): Doing case insensitive check for filtering out workflow artifacts while adding workflows in template (#7455)
  libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
Labels: Risk:Medium

#7468 Revert "chore: remove obsolete GitHub workflow files"
  .github/workflows/base-coverage.yml
  .github/workflows/coverage-report.yml
  .github/workflows/production-build.yml
Labels: needs-pr-update

#7469 docs: fix styling and readability issues in documentation
  .github/workflows/base-coverage.yml
  .github/workflows/coverage-report.yml
  .github/workflows/production-build.yml
  apps/docs/docs/intro.md
  apps/docs/docs/tsg.mdx
  apps/docs/src/css/custom.css
Labels: pr-validated

#7443 feat(designer): Adding Support for nested agent operation
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
  libs/designer-ui/src/lib/card/subgraphCard/index.tsx
  libs/designer-ui/src/lib/card/subgraphCard/subgraphCard.less
  libs/designer-ui/src/lib/panel/recommendationpanel/recommendationPanelCard/index.tsx
  libs/designer/src/lib/common/constants.ts
  libs/designer/src/lib/ui/panel/recommendation/hooks.ts
  libs/designer/src/lib/ui/panel/recommendation/operationGroupDetailView.tsx
  libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/experimentationFlags.ts
Labels: pr-validated

#7473 fix(vscode): Unit Test Array Object Name #7472
  apps/vs-code-designer/src/app/utils/__test__/unitTestUtils.test.ts
  apps/vs-code-designer/src/app/utils/unitTests.ts
Labels: Risk:Low

#7474 fix(templates): Adding case insensitive lookups while using data from custom template
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/templates/utils/parametershelper.ts
Labels: pr-validated

#7475 fix(templates): Adding case insensitive lookups while using data from custom template (#7474)
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/templates/utils/parametershelper.ts
Labels: Risk:Medium

#7476 feat(designer-ui): comprehensive LESS to makeStyles migration analysis and first component migrations
  AI_MIGRATION_EXECUTION_SCRIPT.md
  AI_OPTIMIZED_MIGRATION_PLAN.md
  LESS_FILES_MIGRATION_ANALYSIS.md
  LESS_TO_MAKESTYLES_DETAILED_MIGRATION_PLAN.md
  LESS_TO_MAKESTYLES_MIGRATION_PLAN.md
  MIGRATION_DEPENDENCY_GRAPH.md
  apps/Standalone/package.json
  apps/docs/package.json
  apps/docs/src/components/AzureHero/styles.module.css
  apps/docs/src/css/custom.css
  apps/vs-code-designer/package.json
  code-coverage-results.md
  filtered_code-coverage-results.md
  libs/chatbot/package.json
  libs/data-mapper-v2/package.json
  libs/data-mapper-v2/src/core/ThemeConect.ts
  libs/data-mapper/package.json
  libs/designer-ui/package.json
  libs/designer-ui/src/lib/ariaSearchResults/ariaSearchResultsAlert.less
  libs/designer-ui/src/lib/ariaSearchResults/ariaSearchResultsAlert.tsx
  libs/designer-ui/src/lib/ariaSearchResults/styles.ts
  libs/designer-ui/src/lib/checkbox/__test__/__snapshots__/checkbox.spec.tsx.snap
  libs/designer-ui/src/lib/checkbox/checkbox.less
  libs/designer-ui/src/lib/checkbox/index.tsx
  libs/designer-ui/src/lib/checkbox/styles.ts
  libs/designer-ui/src/lib/dropdown/dropdown.less
  libs/designer-ui/src/lib/dropdown/index.tsx
  libs/designer-ui/src/lib/dropdown/styles.ts
  libs/designer-ui/src/lib/editor/initializevariable/__test__/__snapshots__/VariableEditor.spec.tsx.snap
  libs/designer-ui/src/lib/identitydropdown/__test__/__snapshots__/identitydropdown.spec.tsx.snap
  libs/designer-ui/src/lib/infoDot/index.tsx
  libs/designer-ui/src/lib/infoDot/infoDot.less
  libs/designer-ui/src/lib/infoDot/styles.ts
  libs/designer-ui/src/lib/label/__test__/__snapshots__/label.spec.tsx.snap
  libs/designer-ui/src/lib/label/index.tsx
  libs/designer-ui/src/lib/label/label.less
  libs/designer-ui/src/lib/label/styles.ts
  libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchCard/index.tsx
  libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchHeader/__test__/__snapshots__/operationSearchHeader.spec.tsx.snap
  libs/designer-ui/src/lib/searchbox/__test__/__snapshots__/searchbox.spec.tsx.snap
  libs/designer-ui/src/lib/searchbox/index.tsx
  libs/designer-ui/src/lib/searchbox/searchbox.less
  libs/designer-ui/src/lib/searchbox/styles.ts
  libs/designer-ui/src/lib/styles.less
  libs/designer-ui/src/lib/table/index.tsx
  libs/designer-ui/src/lib/table/styles.ts
  libs/designer-ui/src/lib/table/table.less
  libs/designer-ui/src/lib/tokens/designTokens.ts
  libs/designer-ui/src/lib/utils/styles/index.ts
  libs/designer-ui/src/lib/utils/styles/migrationHelpers.ts
  libs/designer/package.json
  libs/designer/src/lib/core/state/__test__/devSlice.spec.ts
  libs/designer/src/lib/core/state/__test__/modalSlice.spec.ts
  libs/designer/src/lib/core/state/__test__/unitTestSlice.spec.ts
  libs/logic-apps-shared/package.json
  libs/vscode-extension/package.json
  package.json
Labels: pr-validated

#7477 refactor(designer-ui): complete foundational LESS to makeStyles migration with 9 component migrations
  LESS_FILES_MIGRATION_ANALYSIS.md
  LESS_TO_MAKESTYLES_MIGRATION_PLAN.md
  e2e/designer/operationPanel.spec.ts
  libs/designer-ui/src/lib/error.less
  libs/designer-ui/src/lib/error/index.ts
  libs/designer-ui/src/lib/error/styles.ts
  libs/designer-ui/src/lib/nodeCollapseToggle/__test__/__snapshots__/nodeCollapseToggle.spec.tsx.snap
  libs/designer-ui/src/lib/nodeCollapseToggle/index.tsx
  libs/designer-ui/src/lib/nodeCollapseToggle/nodeCollapseToggle.less
  libs/designer-ui/src/lib/nodeCollapseToggle/styles.ts
  libs/designer-ui/src/lib/overview/__test__/__snapshots__/overviewproperties.spec.tsx.snap
  libs/designer-ui/src/lib/overview/index.tsx
  libs/designer-ui/src/lib/overview/overview.less
  libs/designer-ui/src/lib/overview/overviewproperties.tsx
  libs/designer-ui/src/lib/overview/styles.ts
  libs/designer-ui/src/lib/panel/recommendationpanel/browseResults.tsx
  libs/designer-ui/src/lib/peek/index.tsx
  libs/designer-ui/src/lib/peek/peek.less
  libs/designer-ui/src/lib/peek/styles.ts
  libs/designer-ui/src/lib/settings/settingsection/settingtextfield.tsx
  libs/designer-ui/src/lib/styles.less
  libs/designer-ui/src/lib/styles/common.ts
  libs/designer-ui/src/lib/templates/templatesSection.tsx
  libs/designer-ui/src/lib/texteditor.less
  libs/designer-ui/src/lib/texteditor/index.ts
  libs/designer-ui/src/lib/texteditor/styles.ts
  libs/designer-ui/src/lib/tip/__test__/tip.spec.tsx
  libs/designer-ui/src/lib/tip/index.tsx
  libs/designer-ui/src/lib/tip/styles.ts
  libs/designer-ui/src/lib/tip/tip.less
  libs/designer-ui/src/lib/utils/styles/index.ts
  libs/designer-ui/src/lib/utils/styles/mixins.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
  libs/designer/src/lib/ui/settings/advancedSettingsMessage.tsx
  playwright.config.ts
Labels: pr-validated

#7478 refactor(designer-ui): migrate 5 additional LESS components to makeStyles system
  libs/designer-ui/src/lib/about/__test__/__snapshots__/about.spec.tsx.snap
  libs/designer-ui/src/lib/about/about.styles.ts
  libs/designer-ui/src/lib/about/index.tsx
  libs/designer-ui/src/lib/card/batch.styles.ts
  libs/designer-ui/src/lib/chatbot/components/connectionStatus.tsx
  libs/designer-ui/src/lib/dropdown/styles.ts
  libs/designer-ui/src/lib/editor/initializevariable/__test__/__snapshots__/VariableEditor.spec.tsx.snap
  libs/designer-ui/src/lib/flyout/__test__/__snapshots__/flyout.spec.tsx.snap
  libs/designer-ui/src/lib/flyout/__test__/__snapshots__/flyoutcallout.spec.tsx.snap
  libs/designer-ui/src/lib/flyout/__test__/flyoutcallout.spec.tsx
  libs/designer-ui/src/lib/flyout/flyout.styles.ts
  libs/designer-ui/src/lib/flyout/flyoutcallout.tsx
  libs/designer-ui/src/lib/flyout/index.tsx
  libs/designer-ui/src/lib/index.ts
  libs/designer-ui/src/lib/modaldialog/index.tsx
  libs/designer-ui/src/lib/modaldialog/modaldialog.styles.ts
  libs/designer-ui/src/lib/styles/connectionContainer.ts
  libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/connectionEntry.tsx
Labels: pr-validated

#7480 fix(designer): hide connection creation date when showing epoch 0
  libs/designer/src/lib/ui/panel/connectionsPanel/selectConnection/__test__/connectionTableDetailsButton.spec.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/selectConnection/connectionTableDetailsButton.tsx
Labels: Connections, Risk:Low, pr-validated

#7483 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 899
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7351 feat(designer): ACA Session Connector/ Python Action
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/customConnectionParameterEditorService.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  apps/Standalone/src/designer/app/LocalDesigner/customConnection/customConnectionParameterEditorService.tsx
  libs/designer-ui/src/lib/code/index.tsx
  libs/designer-ui/src/lib/code/util.ts
  libs/designer-ui/src/lib/constants.ts
  libs/designer-ui/src/lib/editor/base/plugins/TokenPickerButtonLegacy.tsx
  libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
  libs/designer-ui/src/lib/tokenpicker/index.tsx
  libs/designer-ui/src/lib/tokenpicker/tokenpickersection/agentparameter/SelectAgentParameter.tsx
  libs/designer/src/lib/common/constants.ts
  libs/designer/src/lib/core/actions/bjsworkflow/add.ts
  libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
  libs/designer/src/lib/core/configuretemplate/utils/helper.ts
  libs/designer/src/lib/core/queries/connections.ts
  libs/designer/src/lib/core/state/selectors/actionMetadataSelector.ts
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
  libs/designer/src/lib/core/utils/graph.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/designer/src/lib/core/utils/tokens.ts
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/__test__/createConnectionWrapper.spec.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionInternal.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionWrapper.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/acasessionConnector.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/components/SubscriptionDropdown.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/styles.ts
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/useCognitiveService.ts
  libs/designer/src/lib/ui/panel/index.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/connectionInline.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
  libs/designer/src/lib/ui/panel/recommendation/SearchOpeationsService.tsx
  libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
  libs/designer/src/lib/ui/panel/recommendation/hooks.ts
  libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
  libs/designer/src/lib/ui/templates/connections/createConnection.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/cognitiveService.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/manifests/inlinecode.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/operations/index.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/operations/inlinecode.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts
  libs/logic-apps-shared/src/designer-client-services/lib/cognitiveService.ts
  libs/logic-apps-shared/src/designer-client-services/lib/experimentationFlags.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/acaSessionConnector.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
  libs/logic-apps-shared/src/parsers/lib/common/constants.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/customcode.ts
Labels: Risk:Low, pr-validated

#7492 feat(designer-ui): update workflow parameters UX to match multi-variable UX consistency
  .github/workflows/pr-ai-validation.yml
  Localize/lang/strings.json
  apps/Standalone/src/dataMapperV1/schemas/x12.json
  apps/vs-code-designer/src/package.json
  biome.json
  e2e/designer/errorsPanel.spec.ts
  e2e/designer/tokens/tokenRemoval.spec.ts
  e2e/designer/workflowParametersPanel.spec.ts
  libs/designer-ui/src/lib/editor/initializevariable/__test__/__snapshots__/VariableEditor.spec.tsx.snap
  libs/designer-ui/src/lib/workflowparameters/__tests__/__snapshots__/workflowparameter.spec.tsx.snap
  libs/designer-ui/src/lib/workflowparameters/__tests__/__snapshots__/workflowparameters.spec.tsx.snap
  libs/designer-ui/src/lib/workflowparameters/__tests__/workflowparameter.spec.tsx
  libs/designer-ui/src/lib/workflowparameters/__tests__/workflowparameterField.spec.tsx
  libs/designer-ui/src/lib/workflowparameters/__tests__/workflowparameters.spec.tsx
  libs/designer-ui/src/lib/workflowparameters/index.ts
  libs/designer-ui/src/lib/workflowparameters/styles.ts
  libs/designer-ui/src/lib/workflowparameters/workflowparameter.tsx
  libs/designer-ui/src/lib/workflowparameters/workflowparameters.tsx
  libs/designer-ui/src/lib/workflowparameters/workflowparametersField.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/operations/index.ts
Labels: pr-validated

#7494 fix(designer): use semantic h2 heading for Add a trigger panel header
  libs/designer-ui/src/lib/text/index.tsx
  libs/designer/src/lib/ui/panel/recommendation/recommendationPanelContext.tsx
Labels: pr-validated

#7493 fix(designer-ui): improve screen reader accessibility for 'Add a trigger' button tooltip
  libs/designer-ui/src/lib/card/addActionCard/__test__/__snapshots__/addActionCard.spec.tsx.snap
  libs/designer-ui/src/lib/card/addActionCard/__test__/addActionCard.spec.tsx
  libs/designer-ui/src/lib/card/addActionCard/index.tsx
Labels: pr-validated

#7490 fix(perf): Fixing Child Workflow Service In Hybrid (Standalone)
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/ChildWorkflow.ts
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
Labels: pr-validated

#7446 Add support for creating codeful workflows in VS Code with .NET 8 and new workflow templates
  apps/vs-code-designer/src/app/commands/createCodeful/CodefulWorkflowCreateStep.ts
  apps/vs-code-designer/src/app/commands/createCodeful/__test__/CodefulWorkflowCreateStep.spec.ts
  apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/CodelessWorkflowCreateStep.ts
  apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/WorkflowCreateStepBase.ts
  apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/WorkflowStateTypeStep.ts
  apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/__test__/WorkflowCreateStepBase.spec.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/NewCodeProjectTypeStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/CodelessFunctionWorkflow.ts
  apps/vs-code-designer/src/app/commands/createWorkflow/WorkflowCodeTypeStep.ts
  apps/vs-code-designer/src/app/commands/createWorkflow/__test__/workflowCodeTypeStep.spec.ts
  apps/vs-code-designer/src/app/commands/createWorkflow/createWorkflow.ts
  apps/vs-code-designer/src/app/commands/dotnet/validateDotNetInstalled.ts
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts
  apps/vs-code-designer/src/app/utils/appSettings/localSettings.ts
  apps/vs-code-designer/src/app/utils/codeful/utils.ts
  apps/vs-code-designer/src/app/utils/codeless/common.ts
  apps/vs-code-designer/src/app/utils/codeless/connection.ts
  apps/vs-code-designer/src/app/utils/codeless/parameter.ts
  apps/vs-code-designer/src/app/utils/codeless/templates.ts
  apps/vs-code-designer/src/app/utils/codeless/updateBuildFile.ts
  apps/vs-code-designer/src/app/utils/dotnet/executeDotnetTemplateCommand.ts
  apps/vs-code-designer/src/app/utils/verifyIsProject.ts
  apps/vs-code-designer/src/assets/CodefulWorkflowTemplate/codefulTemplate.cs
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.DotNet.Cli.CommandLine.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Abstractions.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Cli.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Core.Contracts.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Core.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Edge.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.JsonCli.deps.json
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.JsonCli.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.JsonCli.runtimeconfig.json
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Orchestrator.RunnableProjects.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Utils.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateSearch.Common.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Newtonsoft.Json.dll
  apps/vs-code-designer/src/constants.ts
  apps/vs-code-designer/src/package.json
  libs/vscode-extension/src/lib/models/functions.ts
  libs/vscode-extension/src/lib/models/host.ts
Labels: VSCode, Risk:High, pr-validated

#7497 Revert "Temporary fix of GeoLocation API version in VSCode
  apps/vs-code-designer/package.json
  apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/LogicAppHostingPlanStep.ts
  apps/vs-code-designer/src/app/tree/subscriptionTree/SubscriptionTreeItem.ts
  apps/vs-code-designer/src/constants.ts
  pnpm-lock.yaml
Labels: pr-validated

#7501 fix(vscode): cherry-pick Rules Engine debugger fix
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/LogicAppTypeStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppNamespaceStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/__test__/FunctionAppNamespaceStep.test.ts
  apps/vs-code-designer/src/constants.ts
Labels: Risk:Low

#7502 fix(designer-ui): make About tab scrollable content keyboard accessible
  libs/designer-ui/src/lib/panel/panel.less
  libs/designer-ui/src/lib/panel/panelcontent.tsx
Labels: pr-validated

#7491 feat(vscode): add cloud.settings.json project file
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/commands/syncCloudSettings.ts
  apps/vs-code-designer/src/app/commands/workflows/unitTest/__test__/saveBlankUnitTest.test.ts
  apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
  apps/vs-code-designer/src/app/commands/workflows/unitTest/saveBlankUnitTest.ts
  apps/vs-code-designer/src/app/functionsExtension/executeOnFunctionsExt.ts
  apps/vs-code-designer/src/constants.ts
  apps/vs-code-designer/src/package.json
Labels: VSCode, Risk:Low, pr-validated

#7499 fix(designer): Initialize Variable Object Updating Serialization, deserialization, and validation
  Localize/lang/strings.json
  libs/designer-ui/src/lib/editor/initializevariable/__test__/util.spec.tsx
  libs/designer-ui/src/lib/editor/initializevariable/util.ts
  libs/designer-ui/src/lib/editor/shared/testtokensegment.ts
Labels: pr-validated

#7244 feat(vscode): Deployment center POC
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ConvertToWorkspace.ts
  apps/vs-code-designer/src/app/commands/debugLogicApp.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/__test__/FileManagement.test.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/__test__/generateDeploymentScripts.test.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/azureScriptWizard.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScriptsSteps/DeploymentScriptTypeStep.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScriptsSteps/SubscriptionAndResourceGroupStep.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScriptsSteps/adoDeploymentScriptsSteps/AppServicePlanNameStep.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScriptsSteps/adoDeploymentScriptsSteps/GenerateADODeploymentScriptsStep.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScriptsSteps/adoDeploymentScriptsSteps/LogicAppNameStep.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScriptsSteps/adoDeploymentScriptsSteps/StorageAccountNameStep.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScriptsSteps/deploymentCenterScriptsSteps/GenerateDeploymentCenterScriptsStep.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScriptsSteps/deploymentCenterScriptsSteps/LogicAppStep.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScriptsSteps/deploymentCenterScriptsSteps/LogicAppUAMIStep.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScriptsSteps/deploymentCenterScriptsSteps/__test__/GenerateDeploymentCenterScriptsStep.test.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/iacGestureHelperFunctions.ts
  apps/vs-code-designer/src/app/utils/__test__/customCodeUtils.test.ts
  apps/vs-code-designer/src/app/utils/taskUtils.ts
  apps/vs-code-designer/src/app/utils/unitTests.ts
  apps/vs-code-designer/src/assets/DeploymentScriptTemplates/DeploymentCenterReadme
  apps/vs-code-designer/src/assets/DeploymentScriptTemplates/DeploymentCenterScript
  apps/vs-code-designer/src/assets/DeploymentScriptTemplates/dotdeployment
  apps/vs-code-designer/src/constants.ts
  apps/vs-code-designer/test-setup.ts
  libs/vscode-extension/src/lib/models/project.ts
Labels: VSCode, Risk:Medium, pr-validated

#7517 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250612201934658 to main
  Localize/loc/es/strings.json.lcl
  Localize/loc/fr/strings.json.lcl
  Localize/loc/hu/strings.json.lcl
  Localize/loc/it/strings.json.lcl
  Localize/loc/ja/strings.json.lcl
  Localize/loc/ko/strings.json.lcl
  Localize/loc/nl/strings.json.lcl
  Localize/loc/pt-PT/strings.json.lcl
  Localize/loc/sv/strings.json.lcl
Labels: pr-validated

#7500 fix(Designer): [Medium Risk] Connection Creation bugs with Client Certs and Legacy Service Principal Multi-Auth
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/__test__/createConnection.spec.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/__test__/mocks/connectionParameters.ts
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
  libs/logic-apps-shared/src/utils/src/lib/helpers/connections.ts
Labels: Risk:Medium, pr-validated

#7529 feat(designer): Wire-up calls for Deployment model creation in-pace and add necessary disable states
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/customEditor/CustomEditorIncrementVariable.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/customEditor/CustomEditorInitializeVariable.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/customEditorService.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  apps/vs-code-react/src/app/designer/customEditorService.tsx
  libs/designer-ui/src/lib/editor/base/index.tsx
  libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
  libs/designer-ui/src/lib/settings/settingsection/styles.ts
  libs/designer/src/lib/common/constants.ts
  libs/designer/src/lib/common/utilities/Utils.ts
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/useCognitiveService.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/connectionInline.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/custom/deploymentModelResource.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/custom/styles.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/helpers.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/cognitiveService.ts
  libs/logic-apps-shared/src/designer-client-services/lib/cognitiveService.ts
  libs/logic-apps-shared/src/designer-client-services/lib/editor.ts
Labels: pr-validated

#7530 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250614052812074 to main
  Localize/loc/es/strings.json.lcl
  Localize/loc/hu/strings.json.lcl
  Localize/loc/id/strings.json.lcl
  Localize/loc/ko/strings.json.lcl
  Localize/loc/zh-Hant/strings.json.lcl
Labels: pr-validated

#7533 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250614172123169 to main
  Localize/loc/de/strings.json.lcl
  Localize/loc/pt-BR/strings.json.lcl
  Localize/loc/pt-PT/strings.json.lcl
  Localize/loc/ru/strings.json.lcl
  Localize/loc/zh-Hans/strings.json.lcl
Labels: pr-validated

#7555 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 905
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7564 fix(vscode): fix "Use connectors from Azure" for workspace with multiple logic apps
  apps/vs-code-designer/src/app/commands/workflows/enableAzureConnectors.ts
Labels: Risk:Low, pr-validated

#7567 fix(vscode): fix "switch to Dotnet Project" to use dot net 8 templates
  apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts
  apps/vs-code-designer/src/app/templates/dotnet/DotnetTemplateProvider.ts
  apps/vs-code-designer/src/app/utils/dotnet/dotnet.ts
  apps/vs-code-designer/src/app/utils/dotnet/executeDotnetTemplateCommand.ts
  apps/vs-code-designer/src/assets/backupTemplates/dotnet/~4/net8.0/item.nupkg
  apps/vs-code-designer/src/assets/backupTemplates/dotnet/~4/net8.0/project.nupkg
  apps/vs-code-designer/src/constants.ts
Labels: Risk:Low, pr-validated, bug

#7578 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250619051906219 to main
  Localize/loc/de/strings.json.lcl
  Localize/loc/pt-BR/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7577 fix(designer): Fixing standalone+vscode resolving connection references in standalone causing infinite loop
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Utilities/Workflow.ts
  apps/vs-code-react/src/app/designer/utilities/workflow.ts
  libs/vscode-extension/src/lib/services/Workflow.ts
Labels: pr-validated

#7585 feat(designer): Dynamically update connection and deployment model when model type is updated
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/useCognitiveService.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/helpers.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
Labels: pr-validated

#7573 fix(vscode): Update template fetching for net8 compatibility for "switch to DotNet project"
  apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts
  apps/vs-code-designer/src/app/templates/dotnet/DotnetTemplateProvider.ts
  apps/vs-code-designer/src/app/utils/dotnet/executeDotnetTemplateCommand.ts
  apps/vs-code-designer/src/constants.ts
Labels: Risk:Low, pr-validated, bug

#7589 fix(vscode): Update error handle on HTTP Post API call
  libs/vscode-extension/src/lib/services/__test__/httpClient.spec.ts
  libs/vscode-extension/src/lib/services/httpClient.ts
Labels: pr-validated

#7584 fix(vscode): use correct tenant in getAuthorizationToken
  apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/HybridLogicAppsSteps/ConnectEnvironmentStep.ts
  apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/HybridLogicAppsSteps/HybridAppCreateStep.ts
  apps/vs-code-designer/src/app/commands/deploy/deploy.ts
  apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/index.ts
  apps/vs-code-designer/src/app/commands/workflows/exportLogicApp.ts
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForAzureResource.ts
  apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForAzureResource.ts
  apps/vs-code-designer/src/app/commands/workflows/openOverview.ts
  apps/vs-code-designer/src/app/utils/codeless/connection.ts
  apps/vs-code-designer/src/app/utils/codeless/getAuthorizationToken.ts
  apps/vs-code-designer/src/app/utils/subscription.ts
Labels: Risk:Medium, pr-validated

#7597 fix(designer): Center Graph on Mount
  libs/designer/src/lib/ui/Designer.tsx
Labels: pr-validated

#7596 fix(designer): Agent Instruction Value Type set incorrectly
  libs/designer-ui/src/lib/agentinstruction/index.tsx
Labels: pr-validated

#7603 feat(templates): Refactoring methods to handle rollback and saving for add/edit
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/state/templates/panelSlice.ts
  libs/designer/src/lib/core/state/templates/tabSlice.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
  libs/logic-apps-shared/src/designer-client-services/lib/templateresource.ts
Labels: pr-validated

#7606 feat(Templates): Workflows Panel - Batch&Individual Edit Support
  Localize/lang/strings.json
  libs/designer/src/lib/core/state/templates/panelSlice.ts
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/edit/editWorkflowsPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
Labels: pr-validated

#7608 feat(Designer): ConnectionsPanel improvements
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
  libs/designer-ui/src/lib/styles/connectionContainer.ts
  libs/designer/src/lib/core/state/panel/panelSlice.ts
  libs/designer/src/lib/core/state/panel/panelTypes.ts
  libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/allConnections.less
  libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/allConnections.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/allConnectionsEmptyState.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/connectionEntry.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/connectorConnectionsCard.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/allConnections/nodeLinkButton.tsx
Labels: Risk:Low, pr-validated

#7604 fix(vscode): Update getWorkspaceFolder to always return WorkspaceFolder
  apps/vs-code-designer/src/app/commands/createCodeful/CodefulWorkflowCreateStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/__test__/ConvertToWorkspace.test.ts
  apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/FolderListStep.ts
  apps/vs-code-designer/src/app/utils/__test__/workspace.test.ts
  apps/vs-code-designer/src/app/utils/workspace.ts
Labels: Risk:Low, pr-validated

#7614 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 909
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7613 fix(Designer): Fix Agentic workflows output in Hybrid
  libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
Labels: Risk:Low, pr-validated

#7618 fix(localization): update placeholder syntax for milliseconds in Polish strings
  Localize/lang/strings.pl.json
  Localize/loc/pl/strings.json.lcl
Labels: pr-validated

#7620 chore: update Vite to v6.3.5 and Vitest to v3.2.4
  Localize/lang/strings.json
  apps/Standalone/package.json
  apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/__test__/WorkflowCreateStepBase.spec.ts
  apps/vs-code-designer/src/app/utils/__test__/unitTestUtils.test.ts
  e2e/designer/real-api/agentic/workflow.json
  libs/designer-ui/src/lib/card/addActionCard/__test__/__snapshots__/addActionCard.spec.tsx.snap
  libs/designer-ui/src/lib/flyout/__test__/__snapshots__/flyout.spec.tsx.snap
  libs/designer-ui/src/lib/flyout2/__test__/__snapshots__/flyout2.spec.tsx.snap
  libs/designer-ui/src/lib/imagewithfallback/__test__/imagewithfallback.spec.tsx
  libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheadercomment.spec.tsx.snap
  libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheadertitle.spec.tsx.snap
  package.json
  pnpm-lock.yaml
Labels: pr-validated

#7621 fix(designer): Adding agent tool in state only when user selects operation
  libs/designer/src/lib/core/actions/bjsworkflow/add.ts
  libs/designer/src/lib/core/state/panel/panelSelectors.ts
  libs/designer/src/lib/core/state/panel/panelSlice.ts
  libs/designer/src/lib/core/state/panel/panelTypes.ts
  libs/designer/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
  libs/designer/src/lib/ui/panel/recommendation/actionSpotlight.tsx
  libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
Labels: pr-validated

#7627 fix(designer): Fix Nested Complex arrays not serializing
  Localize/lang/strings.json
  libs/designer-ui/src/lib/arrayeditor/util/util.ts
Labels: pr-validated

#7628 feat(Templates): Support limiting resource selection
  libs/designer/src/lib/ui/templates/basics/multiworkflow.tsx
  libs/designer/src/lib/ui/templates/basics/resourcepicker.tsx
  libs/designer/src/lib/ui/templates/basics/singleworkflow.tsx
  libs/logic-apps-shared/src/utils/src/lib/models/template.ts
Labels: pr-validated

#7610 fix(templates): Minor changes in content and ordering in custom templates
  Localize/lang/strings.json
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/parametersTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/summaryTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/workflowsTab.tsx
Labels: pr-validated

#7625 fix(vscode): Upgrade Codeful SDK to 1.127.21.3-preview and enhance workflow debugging support in VS Code Designer
  apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeNetHostProcess.test.ts
  apps/vs-code-designer/src/app/commands/createCodeful/CodefulWorkflowCreateStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/NewCodeProjectTypeStep.ts
  apps/vs-code-designer/src/app/commands/createWorkflow/createWorkflow.ts
  apps/vs-code-designer/src/app/commands/initProjectForVSCode/InitVSCodeStepBase.ts
  apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
  apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
  apps/vs-code-designer/src/constants.ts
  libs/vscode-extension/src/lib/models/project.ts
Labels: pr-validated

#7635 fix(designer): Add opaque backgrounds to React Flow control buttons
  libs/designer/src/lib/ui/styles.less
Labels: pr-validated

#7644 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 911
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7626 Added telemetry for when codeful workflow is created in a new project
  apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/ProjectCreateStepBase.ts
Labels: Risk:Low, pr-validated

#7646 feat(Templates): Added telemetry for successful resource + state update
  Localize/lang/strings.json
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
Labels: pr-validated

#7643 fix(designer): Fix panel accessibility at 400% zoom by optimizing comment section
  Localize/lang/strings.json
  e2e/designer/recurrence.spec.ts
  libs/designer-ui/src/lib/panel/__test__/__snapshots__/panelcontainer.spec.tsx.snap
  libs/designer-ui/src/lib/panel/__test__/panelcontainer.spec.tsx
  libs/designer-ui/src/lib/panel/panel.less
  libs/designer-ui/src/lib/panel/panelcontainer.tsx
  libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheader.spec.tsx.snap
  libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheadercomment.spec.tsx.snap
  libs/designer-ui/src/lib/panel/panelheader/__test__/panelheadercomment.spec.tsx
  libs/designer-ui/src/lib/panel/panelheader/panelheader.tsx
  libs/designer-ui/src/lib/panel/panelheader/panelheadercomment.tsx
  package.json
Labels: pr-validated

#7655 Feat(designer): Dynamic Output not updating titles of view model editors
  Localize/lang/strings.json
  libs/designer/src/lib/core/state/__test__/operation/operationMetadataSlice.spec.ts
  libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
Labels: pr-validated

#7670 fix(designer): Remove all references to Mock Python Operation
  libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts
Labels: pr-validated

#7669 fix(designer): Remove all references to Mock Python Operation
  libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/search.ts
Labels: pr-validated

#7619 feat(Designer): Monitoring Parameters UX Update
  Localize/lang/strings.json
  libs/designer-ui/src/lib/colorizer/__test__/__snapshots__/colorizer.spec.tsx.snap
  libs/designer-ui/src/lib/colorizer/__test__/colorizer.spec.tsx
  libs/designer-ui/src/lib/colorizer/colorizer.less
  libs/designer-ui/src/lib/colorizer/index.tsx
  libs/designer-ui/src/lib/editor/initializevariable/variableEditor.less
  libs/designer-ui/src/lib/monitoring/errorsection/__test__/errorsection.spec.tsx
  libs/designer-ui/src/lib/monitoring/errorsection/index.tsx
  libs/designer-ui/src/lib/monitoring/index.tsx
  libs/designer-ui/src/lib/monitoring/monitoring.less
  libs/designer-ui/src/lib/monitoring/requestpanel/__test__/__snapshots__/request.spec.tsx.snap
  libs/designer-ui/src/lib/monitoring/requestpanel/__test__/__snapshots__/requestpanel.spec.tsx.snap
  libs/designer-ui/src/lib/monitoring/requestpanel/__test__/request.spec.tsx
  libs/designer-ui/src/lib/monitoring/requestpanel/__test__/requestpanel.spec.tsx
  libs/designer-ui/src/lib/monitoring/requestpanel/__test__/response.spec.tsx
  libs/designer-ui/src/lib/monitoring/requestpanel/__test__/securedatasection.spec.tsx
  libs/designer-ui/src/lib/monitoring/requestpanel/index.tsx
  libs/designer-ui/src/lib/monitoring/requestpanel/request.tsx
  libs/designer-ui/src/lib/monitoring/requestpanel/response.tsx
  libs/designer-ui/src/lib/monitoring/requestpanel/types.ts
  libs/designer-ui/src/lib/monitoring/retrypanel/__test__/__snapshots__/retrypanel.spec.tsx.snap
  libs/designer-ui/src/lib/monitoring/secureDataSection/index.tsx
  libs/designer-ui/src/lib/monitoring/values/__test__/__snapshots__/raw.spec.tsx.snap
  libs/designer-ui/src/lib/monitoring/values/__test__/__snapshots__/values.spec.tsx.snap
  libs/designer-ui/src/lib/monitoring/values/__test__/__snapshots__/xml.spec.tsx.snap
  libs/designer-ui/src/lib/monitoring/values/__test__/values.spec.tsx
  libs/designer-ui/src/lib/monitoring/valuespanel/__test__/valuelink.spec.tsx
  libs/designer-ui/src/lib/monitoring/valuespanel/__test__/valuelist.spec.tsx
  libs/designer-ui/src/lib/monitoring/valuespanel/__test__/valuespanel.spec.tsx
  libs/designer-ui/src/lib/monitoring/valuespanel/index.tsx
  libs/designer-ui/src/lib/monitoring/valuespanel/valuelink.tsx
  libs/designer-ui/src/lib/panel/panelheader/panelheadercomment.tsx
  libs/designer-ui/src/lib/panel/recommendationpanel/operationGroupDetails/index.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/monitoringTab/__tests__/__snapshots__/inputsPanel.spec.tsx.snap
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/monitoringTab/__tests__/__snapshots__/outputsPanel.spec.tsx.snap
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/requestTab.tsx
  libs/logic-apps-shared/src/utils/src/lib/models/logicAppsV2.ts
Labels: Risk:Medium, pr-validated
