Repository Azure/LogicAppsUX, pull requests merged in 2025-01, with the labels that each got.

#6249 feat(designer): Update status pill spinner for only running actions
  Localize/lang/strings.json
  libs/designer-ui/src/lib/card/__test__/__snapshots__/card.spec.tsx.snap
  libs/designer-ui/src/lib/card/card.less
  libs/designer-ui/src/lib/card/graphContainer/index.tsx
  libs/designer-ui/src/lib/card/index.tsx
  libs/designer-ui/src/lib/card/scopeCard/index.tsx
  libs/designer-ui/src/lib/card/subgraphCard/index.tsx
  libs/designer-ui/src/lib/monitoring/statuspill/__test__/__snapshots__/statusicon.spec.tsx.snap
  libs/designer-ui/src/lib/monitoring/statuspill/__test__/statusicon.spec.tsx
  libs/designer-ui/src/lib/monitoring/statuspill/index.tsx
  libs/designer-ui/src/lib/monitoring/statuspill/statusicon.tsx
  libs/designer-ui/src/lib/utils/utils.ts
  libs/designer/src/lib/ui/CustomNodes/GraphContainerNode.tsx
  libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
  libs/designer/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
Labels: Monitoring

#6414 fix(Designer): Fixed issues with loop component memoization
  libs/designer/src/lib/ui/CanvasSizeMonitor.tsx
  libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
  libs/designer/src/lib/ui/common/LoopsPager/LoopsPager.tsx
Labels: Performance

#6463 fix(designer): Render copied tooltip properly
  e2e/designer/mock-copypastescope.spec.ts
  libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
  libs/designer/src/lib/ui/common/DesignerContextualMenu/CopyTooltip.tsx
  libs/designer/src/lib/ui/common/DesignerContextualMenu/DesignerContextualMenu.tsx
  libs/designer/src/lib/ui/common/DesignerContextualMenu/__test__/CopyTooltip.spec.tsx
  libs/designer/src/lib/ui/common/DesignerContextualMenu/__test__/__snapshots__/CopyTooltip.spec.tsx.snap
Labels: Cosmetic
