Repository Azure/LogicAppsUX, pull requests merged in 2025-04, with the labels that each got.

#6897 fix(vscode): .Net 8 custom code debugger fix
  apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeNetHostProcess.test.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/CreateNewProjectInternal.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppFilesStep.ts
  apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
  apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesigner.ts
  apps/vs-code-designer/src/app/debug/validatePreDebug.ts
  apps/vs-code-designer/src/constants.ts
  apps/vs-code-designer/src/package.json
Labels: Risk:Medium

#6929 feat(Designer): Exported 2 extra state methods for templates
  libs/designer/src/lib/core/index.ts
Labels: Risk:Low

#6925 fix(template): Hide connection section for standard SKU if LA is not provided
  libs/designer/src/lib/ui/panel/templatePanel/__tests__/quickViewPanel.spec.tsx
  libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/summaryTab.tsx
Labels: Risk:Low

#6803 Fix(Data Mapper): Fixed scroll cutting off bottom
  libs/data-mapper-v2/src/components/schema/styles.ts
Labels: Risk:Low

#6932 chore: Update CODEOWNERS
  .github/CODEOWNERS
Labels: Risk:Low

#6928 feat(designer): Implement links for tools and agents in chat
  apps/vs-code-react/src/main.tsx
  libs/designer-ui/src/lib/chatbot/components/conversationItem.ts
  libs/designer-ui/src/lib/chatbot/components/toolReply.tsx
  libs/designer/src/lib/core/queries/runs.ts
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
Labels: Risk:Low

#6931 fix(designer): Small Agent Parameter Cosmetic Changes
  Localize/lang/strings.json
  e2e/designer/editors/dictionary.spec.ts
  e2e/designer/variables/multiVariable.spec.ts
  e2e/designer/variables/variableEditor.spec.ts
  libs/designer-ui/src/lib/editor/initializevariable/__test__/__snapshots__/VariableEditor.spec.tsx.snap
  libs/designer-ui/src/lib/editor/initializevariable/index.tsx
  libs/designer-ui/src/lib/editor/initializevariable/variableEditor.tsx
Labels: Risk:Low

#6942 feat(designer): Add resizer to agent chat and remove footer
  libs/chatbot/src/lib/ui/ChatbotUi.tsx
  libs/designer-ui/src/lib/chatbot/chatbot.less
  libs/designer-ui/src/lib/chatbot/components/chatBubble.tsx
  libs/designer-ui/src/lib/chatbot/components/conversationItem.ts
  libs/designer-ui/src/lib/chatbot/components/conversationMessage.tsx
  libs/designer-ui/src/lib/panel/panelResizer.tsx
  libs/designer/src/lib/ui/Designer.tsx
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
Labels: Risk:Low

#6888 feat(Templates): Workflows Tab Configuration and Initialization
  Localize/lang/strings.json
  libs/designer/src/lib/core/actions/bjsworkflow/__test__/configuretemplate.spec.ts
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/configuretemplate/ConfigureTemplateWizard.tsx
  libs/designer/src/lib/core/configuretemplate/utils/queries.ts
  libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/tabs/workflowsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/selectWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/configureWorkflowsPanel.tsx
  libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/tabs/customizeWorkflowsTab.tsx
  libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/tabs/selectWorkflowsTab.tsx
  libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/usePanelTabs.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/resource.ts
Labels: Risk:Low

#6945 fix(designer): Couple of cosmetic changes on Agent
  libs/designer-ui/src/lib/agentinstruction/agentinstruction.less
  libs/designer-ui/src/lib/agentinstruction/util.ts
Labels: Risk:Low

#6948 feat(Templates): Removing template bundling from packages
  e2e/templates/app.spec.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/template.ts
  package.json
Labels: Risk:Low

#6939 fix(vscode): logic app name validation misses duplicate name
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/SetLogicAppNameStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/__test__/SetLogicAppNameStep.test.ts
  apps/vs-code-designer/test-setup.ts
Labels: Risk:Low

#6955 feat(designer): Updating hotfix branch with latest from main
  Localize/lang/strings.json
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/SetLogicAppNameStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/__test__/SetLogicAppNameStep.test.ts
  apps/vs-code-designer/test-setup.ts
  e2e/designer/editors/dictionary.spec.ts
  e2e/designer/variables/multiVariable.spec.ts
  e2e/designer/variables/variableEditor.spec.ts
  e2e/templates/app.spec.ts
  libs/chatbot/src/lib/ui/ChatbotUi.tsx
  libs/designer-ui/src/lib/agentinstruction/agentinstruction.less
  libs/designer-ui/src/lib/agentinstruction/util.ts
  libs/designer-ui/src/lib/chatbot/chatbot.less
  libs/designer-ui/src/lib/chatbot/components/chatBubble.tsx
  libs/designer-ui/src/lib/chatbot/components/conversationItem.ts
  libs/designer-ui/src/lib/chatbot/components/conversationMessage.tsx
  libs/designer-ui/src/lib/editor/initializevariable/__test__/__snapshots__/VariableEditor.spec.tsx.snap
  libs/designer-ui/src/lib/editor/initializevariable/index.tsx
  libs/designer-ui/src/lib/editor/initializevariable/variableEditor.tsx
  libs/designer-ui/src/lib/panel/panelResizer.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/__test__/configuretemplate.spec.ts
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/configuretemplate/ConfigureTemplateWizard.tsx
  libs/designer/src/lib/core/configuretemplate/utils/queries.ts
  libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/ui/Designer.tsx
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/tabs/workflowsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/selectWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
  libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/configureWorkflowsPanel.tsx
  libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/tabs/customizeWorkflowsTab.tsx
  libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/tabs/selectWorkflowsTab.tsx
  libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/usePanelTabs.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/resource.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/template.ts
  package.json
Labels: Risk:Low

#6957 fix(Designer): Fixed issue with arrow visibility
  libs/designer/src/lib/ui/connections/edge.tsx
Labels: Risk:Low

#6958 fix(designer): Agentic Loops - Agent parameter button styling fix
  libs/designer-ui/src/lib/editor/base/editor.less
  libs/designer-ui/src/lib/editor/base/plugins/tokenpickerbutton/agentParameterButton.tsx
Labels: Risk:Low

#6962 fix(designer): Fix panel resize
  libs/designer-ui/src/lib/panel/panelResizer.tsx
  libs/designer-ui/src/lib/panel/panelcontainer.tsx
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
Labels: Risk:Low

#6960 fix(designer): Fix minor cosmetic fixes for chat
  Localize/lang/strings.json
  libs/chatbot/src/lib/ui/ChatbotUi.tsx
  libs/designer-ui/src/lib/chatbot/chatbot.less
  libs/designer-ui/src/lib/chatbot/components/conversationItem.ts
  libs/designer-ui/src/lib/chatbot/components/conversationMessage.tsx
  libs/designer-ui/src/lib/html/htmleditor.less
  libs/designer/src/lib/ui/panel/agentChat/__tests__/__snapshots__/agentChatHeader.spec.tsx.snap
  libs/designer/src/lib/ui/panel/agentChat/__tests__/agentChatHeader.spec.tsx
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
  libs/designer/src/lib/ui/panel/agentChat/agentChatHeader.tsx
Labels: Risk:Low

#6959 fix(Designer): Restructured the initialize variables component UX
  libs/designer-ui/src/lib/editor/initializevariable/__test__/__snapshots__/VariableEditor.spec.tsx.snap
  libs/designer-ui/src/lib/editor/initializevariable/index.tsx
  libs/designer-ui/src/lib/editor/initializevariable/variableEditor.less
  libs/designer-ui/src/lib/editor/initializevariable/variableEditor.tsx
  libs/designer-ui/src/lib/workflowparameters/workflowparameter.tsx
Labels: Risk:Low

#6949 fix(designer): Agentic Loop - Hide Add as Connector
  Localize/lang/strings.json
  libs/designer-ui/src/lib/panel/recommendationpanel/operationGroupDetails/index.tsx
Labels: Risk:Low

#6944 fix(designer): Prevent Uncast from ocurring by default
  libs/designer-ui/src/lib/querybuilder/Row.tsx
  libs/designer/src/lib/common/constants.ts
  libs/designer/src/lib/core/utils/__test__/segment.spec.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/designer/src/lib/core/utils/parameters/segment.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Labels: Risk:Low

#6964 feat(Designer): Cert based multi-auth
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
  libs/logic-apps-shared/src/utils/src/lib/helpers/connections.ts
  package.json
Labels: Risk:Low

#6963 fix(designer): Agent chat fixes
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  libs/chatbot/src/lib/ui/ChatbotUi.tsx
  libs/designer-ui/src/lib/chatbot/chatbot.less
  libs/designer-ui/src/lib/chatbot/components/chatBubble.tsx
  libs/designer-ui/src/lib/chatbot/components/conversationItem.ts
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
Labels: Risk:Low

#6961 fix(vscode): bug in function name/function app name/function app namespace input validation, update context when creating new functions project
  apps/vs-code-designer/src/app/commands/createCustomCodeFunction/createCustomCodeFunction.ts
  apps/vs-code-designer/src/app/commands/createCustomCodeFunction/createCustomCodeFunctionSteps/FunctionNameStep.ts
  apps/vs-code-designer/src/app/commands/createCustomCodeFunction/createCustomCodeFunctionSteps/__test__/FunctionNameStep.test.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/CreateNewProjectInternal.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/__test__/LogicAppNameStep.test.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppNameStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppNamespaceStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/__test__/FunctionAppNameStep.test.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/__test__/FunctionAppNamespaceStep.test.ts
  apps/vs-code-designer/test-setup.ts
Labels: Risk:Low

#6977 fix(vscode): Delete statusCode from root def
  apps/vs-code-designer/src/app/utils/__test__/UnitTesting/unitTestUtils.test.ts
  apps/vs-code-designer/src/app/utils/unitTests.ts
Labels: Risk:Low

#6978 feat(designer): Add parameters to agent action
  libs/designer-ui/src/lib/agentinstruction/index.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low

#6980 feat(designer): Add max and min validation for number/integers inputs
  Localize/lang/strings.json
  libs/designer/src/lib/core/utils/parameters/__test__/validation.spec.ts
  libs/designer/src/lib/core/utils/validation.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low

#6987 feat(designer): Add operation-option for Operation fail in agentic workflow
  Localize/lang/strings.json
  libs/designer/src/lib/common/constants.ts
  libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
  libs/designer/src/lib/core/actions/bjsworkflow/settings.ts
  libs/designer/src/lib/ui/settings/index.tsx
  libs/designer/src/lib/ui/settings/sections/general.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
  libs/logic-apps-shared/src/utils/src/lib/models/operationmanifest.ts
Labels: Risk:Low

#6992 feat(designer): Add agentic section in standalone and introduce empty workflow
  Localize/lang/strings.json
  __mocks__/workflows/BlankAgent.json
  apps/Standalone/src/designer/app/LocalDesigner/LogicAppSelector/LogicAppSelector.tsx
Labels: Risk:Low

#6993 feat(designer): Update agent run index and add advanced settings message
  Localize/lang/strings.json
  libs/designer-ui/src/lib/agentinstruction/agentinstruction.less
  libs/designer-ui/src/lib/agentinstruction/index.tsx
  libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
  libs/designer/src/lib/ui/settings/__tests__/__snapshots__/advancedSettingsMessage.spec.tsx.snap
  libs/designer/src/lib/ui/settings/__tests__/advancedSettingsMessage.spec.tsx
  libs/designer/src/lib/ui/settings/advancedSettingsMessage.tsx
  libs/designer/src/lib/ui/settings/settingsection.tsx
Labels: Risk:Low

#6972 feat(Templates): Custom Templates Parameters Tab
  Localize/lang/strings.json
  libs/designer-ui/src/lib/templates/templatesSection.tsx
  libs/designer-ui/src/lib/templates/templatesSectionModel.ts
  libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
  libs/designer/src/lib/core/configuretemplate/configuretemplateselectors.tsx
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/ui/configuretemplate/parameters/customizeParameter.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/parameterslist.tsx
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/tabs/parametersTab.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/panel/configureTemplatePanel/customizeParameterPanel/customizeParameterPanel.tsx
Labels: Risk:Low

#6996 feat(designer): Update agent action manifest
  libs/designer-ui/src/lib/searchabledropdown/index.tsx
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low

#7005 fix(designer): Fix close button default value for assistant chat
  libs/chatbot/src/lib/ui/ChatbotUi.tsx
Labels: Risk:Low

#7008 fix(designer): Fix run history crash with channels setup
  libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
Labels: Risk:Low

#7010 fix(designer): revert Support parsedocumentwithmetadat in standard
  libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
Labels: Risk:Low

#6165 meta(repo): Extra parameter validation for the `production-build.yml` workflow
  .github/workflows/production-build.yml
Labels: Risk:Low

#7014 fix(designer): Memoize selectors and fix run data from agent
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
  libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
Labels: Risk:Low

#7006 fix(designer): Array Editor Bugfixes
  libs/designer-ui/src/lib/agentinstruction/index.tsx
  libs/designer-ui/src/lib/arrayeditor/expandedsimplearray.tsx
  libs/designer-ui/src/lib/arrayeditor/index.tsx
  libs/designer-ui/src/lib/dictionary/dictionaryeditor.less
  libs/designer/src/lib/core/utils/parameters/__test__/segment.spec.ts
  libs/designer/src/lib/core/utils/parameters/__test__/uncast.spec.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/designer/src/lib/core/utils/parameters/segment.ts
  libs/designer/src/lib/core/utils/parameters/uncast.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low

#7018 feat(designer): Wire up input channel with chat
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/HttpClient.ts
  libs/designer/src/lib/core/queries/runs.ts
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
Labels: Risk:Low

#7015 fix(designer): Update messages styles in chat
  libs/designer-ui/src/lib/chatbot/chatbot.less
  libs/designer-ui/src/lib/chatbot/components/chatBubble.tsx
  libs/designer-ui/src/lib/chatbot/components/conversationItem.ts
  libs/designer-ui/src/lib/chatbot/components/conversationMessage.tsx
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
Labels: Risk:Low

#7022 feat(designer): Experimental Flags + Parse Document Functionality
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  libs/designer/src/lib/ui/panel/recommendation/hooks.ts
  libs/designer/src/lib/ui/panel/recommendation/operationGroupDetailView.tsx
  libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
  libs/logic-apps-shared/src/designer-client-services/index.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/experimentation.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/operations/dataoperations.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/parsedocumentwithmetadata.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/operationmanifest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/search.ts
  libs/logic-apps-shared/src/designer-client-services/lib/experimentationFlags.ts
  libs/logic-apps-shared/src/utils/src/lib/mocks/connectorsSearchResultsMock.ts
Labels: Risk:Low

#7021 feat(designer): Experimental Flags + Parse Document Functionality
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  libs/designer/src/lib/ui/panel/recommendation/hooks.ts
  libs/designer/src/lib/ui/panel/recommendation/operationGroupDetailView.tsx
  libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
  libs/logic-apps-shared/src/designer-client-services/index.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/experimentation.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/experimentationFlags.ts
  libs/logic-apps-shared/src/utils/src/lib/mocks/connectorsSearchResultsMock.ts
Labels: Risk:Low

#7024 fix(designer): Add waiting for input and update output channel to be optional
  Localize/lang/strings.json
  libs/designer-ui/src/lib/settings/settings.less
  libs/designer/src/lib/core/queries/runs.ts
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/ChannelContent.tsx
Labels: Risk:Low

#7025 fix(designer): Move parse chat history to helper and fix callback re-render
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  apps/Standalone/src/designer/state/workflowLoadingSlice.ts
  libs/chatbot/src/lib/ui/ChatbotUi.tsx
  libs/chatbot/src/lib/ui/CopilotChatbot.tsx
  libs/designer/src/lib/ui/panel/agentChat/__tests__/helper.spec.ts
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
  libs/designer/src/lib/ui/panel/agentChat/helper.ts
Labels: Risk:Low

#7017 feat(Templates): Move summary tab before workflow tab
  libs/designer/src/lib/core/templates/utils/helper.ts
Labels: Risk:Low

#7026 fix(designer): Update workflow condition for Agent chat
  Localize/lang/strings.json
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/index.tsx
Labels: Risk:Low

#6997 feat(Templates): Custom Templates Tab Management
  libs/designer-ui/src/lib/templates/model.ts
  libs/designer-ui/src/lib/templates/templatesContent.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/state/templates/panelSlice.ts
  libs/designer/src/lib/core/state/templates/tabSlice.ts
  libs/designer/src/lib/ui/configuretemplate/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/model.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/parametersTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/profileTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/publishTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/reviewPublishTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/workflowsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/tabs/customizeWorkflowsTab.tsx
  libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/tabs/selectWorkflowsTab.tsx
  libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/basicsTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/parametersTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/reviewCreateTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/summaryTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/workflowTab.tsx
Labels: Risk:Low

#7027 fix(vscode): Delete statusCode from root def
  apps/vs-code-designer/src/app/utils/__test__/UnitTesting/unitTestUtils.test.ts
  apps/vs-code-designer/src/app/utils/unitTests.ts
Labels: Risk:Low

#7028 feat(designer): Implement adding tool and action in a single click
  libs/designer-ui/src/lib/panel/panelcontainer.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/add.ts
  libs/designer/src/lib/core/state/panel/panelSlice.ts
  libs/designer/src/lib/core/state/panel/panelTypes.ts
  libs/designer/src/lib/core/state/undoRedo/undoRedoTypes.ts
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
  libs/designer/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
Labels: Risk:Low

#7016 feat(Templates): Custom Templates Review + Publish tab Implementation
  Localize/lang/strings.json
  libs/designer-ui/src/lib/templates/templatesSection.tsx
  libs/designer-ui/src/lib/templates/templatesSectionModel.ts
  libs/designer/src/lib/ui/configuretemplate/connections/connectionslist.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/parameterslist.tsx
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/parametersTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/profileTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/publishTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/reviewPublishTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/workflowsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/templateprofile/manifestform.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/quickViewPanel.tsx
  libs/designer/src/lib/ui/templates/connections/connector.tsx
  libs/designer/src/lib/ui/templates/templateoverview.tsx
  libs/designer/src/lib/ui/templates/templatesStrings.ts
Labels: Risk:Low

#7030 fix(designer): Refactor to remove redundancy, add disabled and dirty state for Agentic channels
  Localize/lang/strings.json
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/ChannelContent.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/index.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low

#7031 feat(vscode): Add "file a bug" button in vscode
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForAzureResource.ts
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
  apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForAzureResource.ts
  apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForLocal.ts
  apps/vs-code-react/src/app/designer/DesignerCommandBar/index.tsx
  apps/vs-code-react/tsconfig.json
  libs/vscode-extension/src/lib/models/extensioncommand.ts
  libs/vscode-extension/src/lib/models/workflow.ts
Labels: Risk:Low

#7034 feat(Templates): Exported 3 templates actions
  libs/designer/src/lib/core/index.ts
Labels: Risk:Low

#7035 feat(Templates): Markdown template description + exports
  libs/designer/src/lib/core/index.ts
  libs/designer/src/lib/ui/panel/templatePanel/panel.less
  libs/designer/src/lib/ui/templates/templateDisplay.tsx
Labels: Risk:Low

#7036 feat(designer): Add expand/collapse all button to controls and rework controls appearance
  Localize/lang/strings.json
  e2e/designer/contextMenus.spec.ts
  e2e/designer/errorsPanel.spec.ts
  e2e/designer/fixtures/real-api.ts
  e2e/designer/queryCache.spec.ts
  e2e/designer/utils/GoToWorkflow.ts
  e2e/designer/variables/multiVariable.spec.ts
  e2e/designer/variables/variableEditor.spec.ts
  libs/designer-ui/src/lib/unitTesting/assertionsPanel/__tests__/__snapshots__/assertion.spec.tsx.snap
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
  libs/designer/src/lib/ui/Controls.tsx
  libs/designer/src/lib/ui/common/controls/collapseExpandControl.tsx
  libs/designer/src/lib/ui/common/teachingPopup/index.tsx
  libs/designer/src/lib/ui/styles.less
  playwright.config.ts
Labels: Risk:Low

#7038 fix(deigner): Position nodes at top of designer on start instead of middle
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
  libs/designer/src/lib/core/utils/designerLayoutHelpers/index.ts
  libs/designer/src/lib/ui/CanvasFinder.tsx
  libs/designer/src/lib/ui/Designer.tsx
  libs/logic-apps-shared/src/utils/src/lib/helpers/hooks.ts
  libs/logic-apps-shared/src/utils/src/lib/models/graphics.ts
  libs/logic-apps-shared/src/utils/src/lib/models/index.ts
Labels: Risk:Low

#7039 fix(designer): Fix issue where retry policy error wouldn't disappear when retry policy changed
  libs/designer/src/lib/ui/settings/validation/validation.ts
Labels: Risk:Low

#7037 feat(designer): Update pinned node to alternated selected node
  e2e/designer/operationPanel.spec.ts
  libs/designer-ui/src/lib/panel/__test__/panelcontainer.spec.tsx
  libs/designer-ui/src/lib/panel/panel.less
  libs/designer-ui/src/lib/panel/panelcontainer.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/add.ts
  libs/designer/src/lib/core/index.ts
  libs/designer/src/lib/core/state/panel/panelSelectors.ts
  libs/designer/src/lib/core/state/panel/panelSlice.ts
  libs/designer/src/lib/core/state/panel/panelTypes.ts
  libs/designer/src/lib/ui/common/DesignerContextualMenu/DesignerContextualMenu.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelNodeData.ts
Labels: Risk:Medium

#7044 fix(designer): Add styles for code tags inside the chat bubble
  libs/designer-ui/src/lib/chatbot/chatbot.less
Labels: Risk:Low

#7046 fix(designer): Agent workflow fixes
  libs/designer-ui/src/lib/agentinstruction/agentinstruction.less
  libs/designer-ui/src/lib/editor/initializevariable/index.tsx
  libs/designer-ui/src/lib/editor/initializevariable/styles.ts
  libs/designer-ui/src/lib/label/label.less
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/ChannelContent.tsx
Labels: Risk:Low

#7045 feat(vscode): Automatically update function core tools and dotnet binaries
  apps/vs-code-designer/src/app/commands/dotnet/validateDotNetIsLatest.ts
  apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
  apps/vs-code-designer/src/app/utils/binaries.ts
  apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
  apps/vs-code-designer/src/app/utils/funcCoreTools/funcVersion.ts
  apps/vs-code-designer/src/package.json
Labels: Risk:Low

#7051 fix(designer): Do not serialize user messages if empty
  libs/designer-ui/src/lib/agentinstruction/util.ts
Labels: Risk:Low

#7052 feat(vscode): Automatically update function core tools and dotnet binaries
  apps/vs-code-designer/src/app/commands/dotnet/validateDotNetIsLatest.ts
  apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
  apps/vs-code-designer/src/app/utils/binaries.ts
  apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
  apps/vs-code-designer/src/app/utils/funcCoreTools/funcVersion.ts
  apps/vs-code-designer/src/package.json
Labels: Risk:Low

#7047 feat(Templates): Infer TriggerType from workflow json
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
  libs/designer/src/lib/ui/configuretemplate/templateprofile/manifestform.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/selectWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/summaryTab.tsx
  libs/designer/src/lib/ui/settings/validation/validation.ts
  libs/designer/src/lib/ui/templates/basics/multiworkflow.tsx
  libs/designer/src/lib/ui/templates/templateoverview.tsx
  libs/designer/src/lib/ui/templates/templatesStrings.ts
Labels: Risk:Low

#7054 fix(designer): Update value in services to support stateful in agentic
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
Labels: Risk:Low

#7055 fix(designer): Load agent run data from general run data
  libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
Labels: Risk:Low

#7056 fix(vscode): Add unit test name validation check for existing test/folder with same name
  apps/vs-code-designer/src/app/utils/__test__/UnitTesting/unitTestUtils.test.ts
  apps/vs-code-designer/src/app/utils/unitTests.ts
Labels: Risk:Low

#7057 feat(designer): Add logic to not validate freshly created agent workflow
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
  libs/designer/src/lib/core/utils/connectors/connections.ts
Labels: Risk:Low

#7058 feat(Templates): Added trigger description input on basics + review steps
  Localize/lang/strings.json
  apps/Standalone/src/templates/app/LocalTemplates.tsx
  apps/Standalone/src/templates/app/TemplatesConsumption.tsx
  apps/Standalone/src/templates/app/TemplatesStandard.tsx
  apps/Standalone/vite.config.ts
  apps/Standalone/vite.e2e.config.ts
  e2e/templates/app.spec.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/ui/configuretemplate/workflows/selectWorkflows.tsx
  libs/designer/src/lib/ui/templates/basics/resource.tsx
  libs/designer/src/lib/ui/templates/review/ReviewAddPanel.tsx
  libs/designer/src/lib/ui/templates/templatesStrings.ts
Labels: Risk:Low

#7063 fix(vscode): Add validation for data map name
  apps/vs-code-designer/src/app/commands/dataMapper/DataMapperExt.ts
  apps/vs-code-designer/src/constants.ts
  libs/designer/src/lib/core/utils/connectors/connections.ts
Labels: VSCode, Data Mapper, Risk:Low

#7064 feat(Templates): Added template trigger description validation
  libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/ui/templates/basics/resource.tsx
Labels: Risk:Low

#7062 feat(Templates): Custom Templates UI Enhancements
  libs/designer-ui/src/lib/templates/templatesPanelFooter.tsx
  libs/designer/src/lib/core/configuretemplate/ConfigureTemplateWizard.tsx
  libs/designer/src/lib/ui/configuretemplate/connections/connectionslist.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/customizeParameter.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/parameterslist.tsx
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/publishTab.tsx
  libs/designer/src/lib/ui/configuretemplate/templateprofile/manifestform.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/templates/styles.less
Labels: Risk:Low

#7067 fix(Templates): Fixed template trigger description validation
  Localize/lang/strings.json
  libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
Labels: Risk:Low

#7072 fix(designer): Update agent settings and intl text
  Localize/lang/strings.json
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
  libs/designer/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low

#7073 fix(vscode): Remove user-facing commands for automated testing
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/constants.ts
  apps/vs-code-designer/src/package.json
Labels: Risk:Low

#7074 fix(vscode): Unit test fixes
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/SetWorkspaceSettings.ts
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/commands/workflows/unitTest/__test__/saveBlankUnitTest.test.ts
  apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
  apps/vs-code-designer/src/app/commands/workflows/unitTest/saveBlankUnitTest.ts
  apps/vs-code-designer/src/app/utils/__test__/UnitTesting/unitTestUtils.test.ts
  apps/vs-code-designer/src/app/utils/unitTests.ts
  apps/vs-code-designer/src/assets/UnitTestTemplates/TestBlankClassFile
  apps/vs-code-designer/src/assets/UnitTestTemplates/TestClassFile
  apps/vs-code-designer/src/assets/UnitTestTemplates/TestClassFileWithoutActions
  apps/vs-code-designer/src/constants.ts
  apps/vs-code-designer/src/package.json
Labels: Risk:Low

#7077 fix(designer): Update channels tab to be more information and abstract out details not required right now
  Localize/lang/strings.json
  libs/designer-ui/src/lib/settings/settings.less
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/ChannelContent.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/index.tsx
Labels: Risk:Low

#7078 fix(vscode): Standardize commands titles
  apps/vs-code-designer/src/package.json
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
Labels: Risk:Low

#7066 fix(designer): Edit pass on agent UX strings. Replace "Click" with the more accessible term, "Select".
  Localize/lang/strings.json
  e2e/designer/app.spec.ts
  libs/designer-ui/src/lib/agentinstruction/index.tsx
  libs/designer-ui/src/lib/agentinstruction/util.ts
  libs/designer-ui/src/lib/card/subgraphCard/index.tsx
  libs/designer-ui/src/lib/checkbox/index.tsx
  libs/designer-ui/src/lib/editor/base/plugins/tokenpickerbutton/agentParameterButton.tsx
  libs/designer-ui/src/lib/editor/base/plugins/tokenpickerbutton/index.tsx
  libs/designer-ui/src/lib/editor/initializevariable/index.tsx
  libs/designer-ui/src/lib/editor/initializevariable/variableEditor.tsx
  libs/designer-ui/src/lib/monitoring/requestpanel/__test__/__snapshots__/request.spec.tsx.snap
  libs/designer-ui/src/lib/monitoring/values/__test__/__snapshots__/values.spec.tsx.snap
  libs/designer-ui/src/lib/monitoring/values/bodylink.tsx
  libs/designer-ui/src/lib/panel/panelheader/panelheadercomment.tsx
  libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchGroup/index.tsx
  libs/designer-ui/src/lib/picker/filepickerPopoverHeader.tsx
  libs/designer-ui/src/lib/querybuilder/SimpleQueryBuilder.tsx
  libs/designer-ui/src/lib/settings/settingsection/dictionary/simpledictionaryitem.tsx
  libs/designer-ui/src/lib/staticResult/StaticResult.tsx
  libs/designer-ui/src/lib/tokenpicker/tokenpickersection/agentparameter/CreateAgentParameter.tsx
  libs/designer-ui/src/lib/tokenpicker/tokenpickersection/agentparameter/NoAgentParameter.tsx
  libs/designer-ui/src/lib/tokenpicker/tokenpickersection/agentparameter/SelectAgentParameter.tsx
  libs/designer-ui/src/lib/tokenpicker/tokenpickersection/tokenpickeroption.tsx
  libs/designer/src/lib/core/utils/tokens.ts
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
  libs/designer/src/lib/ui/common/EdgeContextualMenu/EdgeContextualMenu.tsx
  libs/designer/src/lib/ui/menuItems/commentMenuItem.tsx
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/index.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/createWorkflowPanel.tsx
  libs/designer/src/lib/ui/settings/__tests__/__snapshots__/settingsection.spec.tsx.snap
  libs/designer/src/lib/ui/settings/advancedSettingsMessage.tsx
  libs/designer/src/lib/ui/settings/settingsection.tsx
Labels: Risk:Low

#7080 feat(vscode): Update Rules Engine files and remove preview
  apps/vs-code-designer/src/README.md
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/CreateNewProjectInternal.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/setLogicAppType.ts
  apps/vs-code-designer/src/assets/RuleSetProjectTemplate/RulesFunctionsFile
  apps/vs-code-designer/src/assets/RuleSetProjectTemplate/RulesFunctionsProj
  apps/vs-code-designer/src/assets/RuleSetProjectTemplate/SchemaUser
Labels: Risk:Low

#7084 docs(vscode): Update Readme - unit test announcement
  apps/vs-code-designer/src/README.md
Labels: Risk:Low

#7081 fix(vscode): Custom code telemetry, error handling
  Localize/lang/strings.json
  apps/vs-code-designer/src/app/commands/__test__/buildCustomCodeFunctionsProject.test.ts
  apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeNetHostProcess.test.ts
  apps/vs-code-designer/src/app/commands/buildCustomCodeFunctionsProject.ts
  apps/vs-code-designer/src/app/commands/createCustomCodeFunction/createCustomCodeFunction.ts
  apps/vs-code-designer/src/app/commands/createCustomCodeFunction/createCustomCodeFunctionSteps/FunctionFilesStep.ts
  apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
Labels: Risk:Low

#7085 fix(vscode): prompt appearing when empty workspace opened
  apps/vs-code-designer/src/app/commands/__test__/parameterizeConnections.test.ts
  apps/vs-code-designer/src/app/commands/binaries/validateAndInstallBinaries.ts
  apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts
  apps/vs-code-designer/src/app/commands/parameterizeConnections.ts
  apps/vs-code-designer/src/app/utils/__test__/workspace.test.ts
  apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
  apps/vs-code-designer/src/app/utils/dotnet/dotnet.ts
  apps/vs-code-designer/src/app/utils/workspace.ts
  apps/vs-code-designer/src/assets/UnitTestTemplates/TestBlankClassFile
Labels: Risk:Medium

#7083 fix(designer): Update messages strings for operation deserializer
  libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
Labels: Risk:Low

#6940 fix(vscode): Custom code papercuts
  apps/Standalone/src/designer/state/historyHelpers.ts
  apps/vs-code-designer/src/app/commands/__test__/buildCustomCodeFunctionsProject.test.ts
  apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeNetHostProcess.test.ts
  apps/vs-code-designer/src/app/commands/buildCustomCodeFunctionsProject.ts
  apps/vs-code-designer/src/app/commands/createCustomCodeFunction/createCustomCodeFunction.ts
  apps/vs-code-designer/src/app/commands/createCustomCodeFunction/createCustomCodeFunctionSteps/FunctionFilesStep.ts
  apps/vs-code-designer/src/app/commands/createCustomCodeFunction/createCustomCodeFunctionSteps/FunctionNameStep.ts
  apps/vs-code-designer/src/app/commands/createCustomCodeFunction/createCustomCodeFunctionSteps/__test__/FunctionNameStep.test.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ConvertToWorkspace.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/CreateNewProjectInternal.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/LogicAppNameStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/LogicAppTypeStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/NewCodeProjectTypeStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/WorkspaceContentsStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/WorkspaceNameStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/WorkspaceSettingsStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/__test__/ConvertToWorkspace.test.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/__test__/LogicAppNameStep.test.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/cloudToLocal.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppFilesStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppNameStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppNamespaceStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionConfigFile.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/InvokeFunctionProjectSetup.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/TargetFrameworkStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/__test__/FunctionAppNameStep.test.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/__test__/FunctionAppNamespaceStep.test.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/setNamepSpace.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/CodeProjectWorkflowStateTypeStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/CodelessFunctionWorkflow.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createNewCodeProject.ts
  apps/vs-code-designer/src/app/commands/createNewProject/createNewProject.ts
  apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/NewProjectLogicAppTypeStep.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/azureScriptWizard.ts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
  apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
  apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesigner.ts
  apps/vs-code-designer/src/app/commands/workflows/unitTest/__test__/saveBlankUnitTest.test.ts
  apps/vs-code-designer/src/app/commands/workflows/unitTest/createUnitTest.ts
  apps/vs-code-designer/src/app/commands/workflows/unitTest/saveBlankUnitTest.ts
  apps/vs-code-designer/src/app/utils/__test__/customCodeUtils.test.ts
  apps/vs-code-designer/src/app/utils/customCodeUtils.ts
  apps/vs-code-designer/src/app/utils/verifyIsProject.ts
  apps/vs-code-designer/src/app/utils/workspace.ts
  apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsProjNet8
  apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsProjNet8New
  apps/vs-code-designer/src/assets/FunctionProjectTemplate/FunctionsProjNetFx
  apps/vs-code-designer/src/constants.ts
  apps/vs-code-designer/src/main.ts
  apps/vs-code-designer/src/package.json
  apps/vs-code-designer/test-setup.ts
  libs/designer/src/lib/core/configuretemplate/utils/__test__/helper.spec.ts
  libs/vscode-extension/src/lib/models/project.ts
Labels: Risk:Medium

#7087 feat(Templates): Review and Publish Re-ordering
  Localize/lang/strings.json
  libs/designer/src/lib/common/constants.ts
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/profileTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/publishTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/reviewTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/templateprofile/manifestform.tsx
  libs/designer/src/lib/ui/configuretemplate/toasters.tsx
  libs/designer/src/lib/ui/templates/styles.less
Labels: Risk:Low

#7092 fix(Templates): Workflows tab content fixes
  Localize/lang/strings.json
  libs/designer/src/lib/ui/configuretemplate/workflows/selectWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/panel/configureTemplatePanel/configureWorkflowsPanel/configureWorkflowsPanel.tsx
  libs/designer/src/lib/ui/templates/basics/resourcepicker.tsx
Labels: Risk:Low

#7091 fix(desinger): Add validation for agent tool name
  Localize/lang/strings.json
  libs/designer-ui/src/lib/editor/initializevariable/util.ts
  libs/designer-ui/src/lib/panel/panelheader/panelheadertitle.tsx
  libs/designer/src/lib/core/utils/graph.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
Labels: Risk:Low

#7095 fix(templates): Using test storage account and removing endpoint checkbox from test pages
  apps/Standalone/src/templates/app/LocalTemplates.tsx
  apps/Standalone/src/templates/app/TemplatesConsumption.tsx
  apps/Standalone/src/templates/app/TemplatesStandard.tsx
  apps/Standalone/src/templates/components/DevToolbox.tsx
  apps/Standalone/src/templates/state/WorkflowLoader.ts
  apps/Standalone/vite.config.ts
  e2e/templates/app.spec.ts
Labels: Risk:Low

#7094 fix(designer): Fix required in agent parameters
  libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
Labels: Risk:Low

#7097 feat(designer): Add "maximumTokenCountReduction" as default in agent settings
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low

#7100 feat(Templates): Add third button support to footer & save button for profile
  Localize/lang/strings.json
  libs/designer-ui/src/lib/templates/templates.less
  libs/designer-ui/src/lib/templates/templatesPanelFooter.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/profileTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/workflowsTab.tsx
Labels: Risk:Low

#7101 fix(designer): Remove agent in non-agent flow
  libs/designer/src/lib/ui/panel/recommendation/actionSpotlight.tsx
Labels: Risk:Low

#7102 fix(designer): Remove agent in non-agent flow
  libs/designer/src/lib/ui/panel/recommendation/actionSpotlight.tsx
Labels: Risk:Low

#7105 fix(designer): Reset id replacements when reset designer dirty state
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  libs/designer/src/lib/core/state/global.ts
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
Labels: Risk:Low

#7109 feat(templates): Adding template backend api integration
  apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/HttpClient.ts
  apps/Standalone/src/designer/app/LocalDesigner/httpClient.ts
  libs/designer/src/lib/__test__/mock-http-client.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/__test__/configuretemplate.spec.ts
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/configuretemplate/utils/helper.ts
  libs/designer/src/lib/core/configuretemplate/utils/queries.ts
  libs/designer/src/lib/core/state/templates/panelSlice.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/configureWorkflowsPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/tabs/customizeWorkflowsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/tabs/selectWorkflowsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/customizeParameterPanel/customizeParameterPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/parameterslist.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/selectWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
  libs/logic-apps-shared/src/designer-client-services/lib/httpClient.ts
  libs/logic-apps-shared/src/designer-client-services/lib/templateresource.ts
  libs/logic-apps-shared/src/parsers/lib/models/operation.ts
  libs/logic-apps-shared/src/utils/src/lib/models/template.ts
  libs/vscode-extension/src/lib/services/httpClient.ts
Labels: Risk:Low

#7118 fix(designer): Reset id replacements when reset designer dirty state
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  libs/designer/src/lib/core/state/global.ts
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
Labels: Risk:Low

#7103 fix(designer): Cosmetic Change on Agent Conditions/ Update Templates
  downloadTemplates.js
  libs/designer-ui/src/lib/card/subgraphCard/index.tsx
  libs/designer-ui/src/lib/card/subgraphCard/subgraphCard.less
Labels: Risk:Low

#7104 fix(designer): Cosmetic Change on Agent Conditions/ Update Templates
  downloadTemplates.js
  libs/designer-ui/src/lib/card/subgraphCard/index.tsx
  libs/designer-ui/src/lib/card/subgraphCard/subgraphCard.less
Labels: Risk:Low

#7119 fix(Templates): Modified template workflow name validation error message
  Localize/lang/strings.json
  libs/designer/src/lib/core/templates/utils/__test__/validation.spec.ts
  libs/designer/src/lib/core/templates/utils/helper.ts
Labels: Risk:Low

#7120 fix(designer): Update agent initial template and add connection label
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  apps/vs-code-designer/src/app/utils/codeless/templates.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/connectionInline.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low

#7122 feat(templates): Loading existing template and its workflows data on wizard load
  apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/configuretemplate/utils/queries.ts
  libs/designer/src/lib/core/state/templates/panelSlice.ts
  libs/designer/src/lib/core/state/templates/tabSlice.ts
  libs/designer/src/lib/core/state/templates/templateOptionsSlice.ts
  libs/designer/src/lib/core/state/templates/workflowSlice.ts
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
  libs/logic-apps-shared/src/designer-client-services/lib/templateresource.ts
Labels: Risk:Low

#7123 fix(designer): Bugs in Initialize Variable Editor
  Localize/lang/strings.json
  libs/designer-ui/src/lib/editor/initializevariable/index.tsx
  libs/designer-ui/src/lib/editor/initializevariable/util.ts
  libs/designer-ui/src/lib/settings/settings.less
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Labels: Risk:Low

#7125 fix(designer): Bugs in Initialize Variable Editor
  Localize/lang/strings.json
  libs/designer-ui/src/lib/editor/initializevariable/index.tsx
  libs/designer-ui/src/lib/editor/initializevariable/util.ts
  libs/designer-ui/src/lib/settings/settings.less
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Labels: Risk:Low

#7131 feat(vscode): New debug config provider for logic app project with custom code
  apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeNetHostProcess.test.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/CreateNewProjectInternal.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppFilesStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/initLogicAppCodeProjectVScode/InitCodeProject.ts
  apps/vs-code-designer/src/app/commands/debugLogicApp.ts
  apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
  apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/utils/__test__/customCodeUtils.test.ts
  apps/vs-code-designer/src/app/utils/azurite/activateAzurite.ts
  apps/vs-code-designer/src/app/utils/customCodeUtils.ts
  apps/vs-code-designer/src/constants.ts
  apps/vs-code-designer/src/main.ts
  apps/vs-code-designer/src/package.json
Labels: Risk:Medium

#7132 fix(desinger): Move Hybrid Api versions to a single location in Libraries
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureStandardLogicAppSelector.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Utilities/HybridAppUtilities.ts
  apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/cleanResources.ts
  apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/index.ts
  apps/vs-code-designer/src/app/utils/codeless/hybridLogicApp/connectedEnvironment.ts
  apps/vs-code-designer/src/app/utils/codeless/hybridLogicApp/hybridApp.ts
  apps/vs-code-designer/src/constants.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connector.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/hybrid.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/operationmanifest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/search.ts
Labels: Risk:Low

#7133 fix(designer): Move Hybrid Api versions to a single location in Libraries
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureStandardLogicAppSelector.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Utilities/HybridAppUtilities.ts
  apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/cleanResources.ts
  apps/vs-code-designer/src/app/commands/deploy/hybridLogicApp/index.ts
  apps/vs-code-designer/src/app/utils/codeless/hybridLogicApp/connectedEnvironment.ts
  apps/vs-code-designer/src/app/utils/codeless/hybridLogicApp/hybridApp.ts
  apps/vs-code-designer/src/constants.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connector.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/hybrid.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/operationmanifest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/search.ts
Labels: Risk:Low

#7136 fix(designer): Remove default, rename tab and update channel
  Localize/lang/strings.json
  libs/designer-ui/src/lib/editor/initializevariable/index.tsx
  libs/designer-ui/src/lib/panel/panelUtil.ts
  libs/designer-ui/src/lib/settings/settings.less
  libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/index.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low
