Repository Azure/LogicAppsUX, pull requests merged in 2025-05, with the labels that each got.

#7130 fix(designer): disable designer 'Save' after saving, disable 'Create unit test' when designer state dirty
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
  apps/vs-code-react/src/app/designer/DesignerCommandBar/index.tsx
  apps/vs-code-react/src/run-service/types.ts
  apps/vs-code-react/src/webviewCommunication.tsx
  libs/vscode-extension/src/lib/models/extensioncommand.ts
Labels: Risk:Low

#7128 feat(designer): Add header actions buttons for agent chat
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
  apps/vs-code-react/src/app/designer/app.tsx
  libs/designer/src/lib/core/queries/runs.ts
  libs/designer/src/lib/ui/panel/agentChat/__tests__/__snapshots__/agentChatHeader.spec.tsx.snap
  libs/designer/src/lib/ui/panel/agentChat/__tests__/agentChatHeader.spec.tsx
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
  libs/designer/src/lib/ui/panel/agentChat/agentChatHeader.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
Labels: Risk:Low

#7139 fix(designer): Increment package version to the correct minor version
  apps/vs-code-designer/src/package.json
  apps/vs-code-react/package.json
  libs/chatbot/package.json
  libs/data-mapper-v2/package.json
  libs/data-mapper/package.json
  libs/designer-ui/package.json
  libs/designer/package.json
  libs/logic-apps-shared/package.json
  libs/vscode-extension/package.json
  package.json
Labels: Risk:Low

#7140 fix(designer): Remove Pin on Deleting Node
  libs/designer/src/lib/core/actions/bjsworkflow/delete.ts
Labels: Risk:Low

#7098 feat(Templates): Add Error Labeling for tabs
  Localize/lang/strings.json
  libs/designer/src/lib/core/templates/utils/__test__/validation.spec.ts
  libs/designer/src/lib/core/templates/utils/helper.ts
  libs/designer/src/lib/ui/configuretemplate/parameters/parameterslist.tsx
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/publishTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/templates/styles.less
Labels: Risk:Low

#7143 fix(Templates): Refactored `filteredTemplateNames` out of state / into selector
  libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
  libs/designer/src/lib/core/state/templates/manifestSlice.ts
  libs/designer/src/lib/core/state/templates/templateselectors.ts
  libs/designer/src/lib/core/templates/TemplatesDataProvider.tsx
  libs/designer/src/lib/ui/templates/gallery/templatesgallery.tsx
Labels: Risk:Low

#7142 fix(designer): Refactor and remove unsupported types from Agent parameter creation
  libs/designer-ui/src/lib/tokenpicker/tokenpickersection/agentparameter/CreateAgentParameter.tsx
Labels: Risk:Low

#7144 fix(Templates): Templates cherry-picks (validation error, dark mode, race condition
  Localize/lang/strings.json
  libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
  libs/designer/src/lib/core/state/templates/manifestSlice.ts
  libs/designer/src/lib/core/state/templates/templateselectors.ts
  libs/designer/src/lib/core/templates/TemplatesDataProvider.tsx
  libs/designer/src/lib/core/templates/utils/__test__/validation.spec.ts
  libs/designer/src/lib/core/templates/utils/helper.ts
  libs/designer/src/lib/ui/panel/templatePanel/panel.less
  libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/summaryTab.tsx
  libs/designer/src/lib/ui/templates/cards/templateCard.less
  libs/designer/src/lib/ui/templates/cards/templateCard.tsx
  libs/designer/src/lib/ui/templates/connections/connector.tsx
  libs/designer/src/lib/ui/templates/gallery/templatesgallery.tsx
  libs/designer/src/lib/ui/templates/parameters/displayParameters.tsx
  libs/designer/src/lib/ui/templates/styles.less
Labels: Risk:Low

#7141 feat(templates): Adding loading of user templates in the gallery
  Localize/lang/strings.json
  apps/Standalone/src/templates/app/LocalTemplates.tsx
  apps/Standalone/src/templates/app/TemplatesConsumption.tsx
  apps/Standalone/src/templates/app/TemplatesStandard.tsx
  e2e/designer/variables/multiVariable.spec.ts
  e2e/templates/app.spec.ts
  e2e/templates/templateFilters.spec.ts
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
  libs/designer/src/lib/core/configuretemplate/utils/helper.ts
  libs/designer/src/lib/core/index.ts
  libs/designer/src/lib/core/state/templates/manifestSlice.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/core/templates/TemplatesDataProvider.tsx
  libs/designer/src/lib/core/templates/TemplatesDesignerContext.tsx
  libs/designer/src/lib/core/templates/utils/queries.ts
  libs/designer/src/lib/ui/templates/cards/templateCard.less
  libs/designer/src/lib/ui/templates/cards/templateCard.tsx
  libs/designer/src/lib/ui/templates/filters/templatesearchfilters.tsx
  libs/designer/src/lib/ui/templates/templateview.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/template.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
  libs/logic-apps-shared/src/designer-client-services/lib/helpers.ts
  libs/logic-apps-shared/src/designer-client-services/lib/template.ts
Labels: Risk:Medium

#7148 fix(designer): Add cognitive account dropdown and auto-fill the values for Agentic connections
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/customConnectionParameterEditorService.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
  apps/Standalone/src/designer/app/LocalDesigner/customConnection/customConnectionParameterEditorService.tsx
  apps/Standalone/src/designer/app/LocalDesigner/localDesigner.tsx
  apps/vs-code-react/src/app/designer/servicesHelper.ts
  libs/designer/src/lib/core/state/designerOptions/designerOptionsInterfaces.ts
  libs/designer/src/lib/core/state/designerOptions/designerOptionsSlice.ts
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/styles.ts
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/useCognitiveService.ts
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/formInputs/universalConnectionParameter.tsx
  libs/designer/src/lib/ui/panel/index.tsx
  libs/logic-apps-shared/src/designer-client-services/index.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/cognitiveService.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/index.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/resource.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/template.ts
  libs/logic-apps-shared/src/designer-client-services/lib/cognitiveService.ts
  libs/logic-apps-shared/src/designer-client-services/lib/common/azure.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentLoopConnector.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/guid.ts
Labels: Risk:Low

#7152 fix(Designer): Fixed standalone oauth for testing
  apps/Standalone/public/authredirect.html
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/OAuthService.ts
Labels: Risk:Low

#7154 fix(designer): Dropdown items for deployment names
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Models/Workflow.ts
  libs/designer-ui/src/lib/dropdown/index.tsx
  libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
  libs/designer/src/lib/common/utilities/Utils.ts
  libs/designer/src/lib/core/state/connection/connectionSelector.ts
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/useCognitiveService.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/cognitiveService.ts
  libs/logic-apps-shared/src/designer-client-services/lib/cognitiveService.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
  libs/logic-apps-shared/src/utils/src/lib/models/connector.ts
Labels: Risk:Low

#7157 fix(designer): Set properties per Model and add a subscription filter
  Localize/lang/strings.json
  libs/designer/src/lib/common/constants.ts
  libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/useCognitiveService.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/cognitiveService.ts
  libs/logic-apps-shared/src/designer-client-services/lib/cognitiveService.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
  libs/logic-apps-shared/src/parsers/lib/models/operation.ts
Labels: Risk:Low

#7156 feat(Templates): Support Multi-button structure for footer
  Localize/lang/strings.json
  apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
  libs/designer-ui/src/lib/templates/templatesPanelFooter.tsx
  libs/designer/src/lib/core/configuretemplate/ConfigureTemplateWizard.tsx
  libs/designer/src/lib/core/templates/utils/helper.ts
  libs/designer/src/lib/ui/configuretemplate/connections/connectionslist.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/configureWorkflowsPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/tabs/customizeWorkflowsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/tabs/selectWorkflowsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/customizeParameterPanel/customizeParameterPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/parameterslist.tsx
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/parametersTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/profileTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/publishTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/reviewTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/workflowsTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/createWorkflowPanel.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/basicsTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/parametersTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/reviewCreateTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/quickViewPanel.tsx
  libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/summaryTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/workflowTab.tsx
  libs/designer/src/lib/ui/templates/templateoverview.tsx
  libs/logic-apps-shared/src/utils/src/lib/models/template.ts
Labels: Risk:Medium

#7159 fix(designer): Browse Action Spotlight to Local Storage
  libs/designer-ui/src/lib/panel/recommendationpanel/recommendation.less
  libs/designer/src/lib/ui/panel/recommendation/actionSpotlight.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/localStorage.ts
Labels: Risk:Low

#7160 fix(designer): Browse Action Spotlight to Local Storage
  libs/designer-ui/src/lib/panel/recommendationpanel/recommendation.less
  libs/designer/src/lib/ui/panel/recommendation/actionSpotlight.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/localStorage.ts
Labels: Risk:Low

#7161 docs(verdaccio): Add registry config for verdaccio development
  apps/docs/docs/Development/portal.mdx
Labels: Risk:Low

#7162 fix(designer): Add skip batch to HttpRequestOptions
  libs/logic-apps-shared/src/designer-client-services/lib/base/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/httpClient.ts
Labels: Risk:Low

#7163 fix(designer): Add skip batch to HttpRequestOptions
  libs/logic-apps-shared/src/designer-client-services/lib/base/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/httpClient.ts
Labels: Risk:Low

#7164 fix(designer): Add MSI support for Agent connections
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/formInputs/universalConnectionParameter.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentLoopConnector.ts
Labels: Risk:Low

#7167 fix(designer): Cherry-pick for MSI and cognitive service resourceId
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/formInputs/universalConnectionParameter.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentLoopConnector.ts
Labels: Risk:Low

#7169 fix(designer): [CP] Add create new for OpenAI resource and update strings
  Localize/lang/strings.json
  libs/designer-ui/src/lib/agentinstruction/index.tsx
  libs/designer-ui/src/lib/index.ts
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/styles.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/connectionInline.tsx
Labels: Risk:Low

#7171 fix(designer): Prevent error for undefined cognitiveServiceAccountId
  libs/designer-ui/src/lib/searchabledropdown/__test__/searchabledropdown.spec.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/useCognitiveService.ts
Labels: Risk:Low

#7173 fix(designer): Update Agent Tool Filtering
  libs/designer/src/lib/ui/panel/recommendation/actionSpotlight.tsx
  libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
Labels: Risk:Low

#7174 fix(designer): Update Agent Tool Filtering
  libs/designer/src/lib/ui/panel/recommendation/actionSpotlight.tsx
  libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
Labels: Risk:Low

#7177 fix(Designer): Non-latin characters in action name breaking designer
  libs/designer/src/lib/ui/connections/edge.tsx
Labels: Risk:Low

#7178 fix(Designer): Non-latin characters in action name breaking designer
  libs/designer/src/lib/ui/connections/edge.tsx
Labels: Risk:Low

#7176 feat(designer): Update 'maximumTokenCount' and 'messageCountLimit' settings as required
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low

#7182 fix(designer): Disable channels for the second agent (or other agents if it is enabled for 1)
  Localize/lang/strings.json
  libs/designer/src/lib/core/state/designerOptions/designerOptionsSelectors.ts
  libs/designer/src/lib/core/utils/agent.ts
  libs/designer/src/lib/ui/common/EdgeContextualMenu/EdgeContextualMenu.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/channelsTab/index.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
Labels: Risk:Low

#7180 fix(designer): Update expression JSON validation
  libs/designer/src/lib/core/utils/validation.ts
Labels: Risk:Low

#7183 feat(designer): Adding Support for NextPage when fetching LegacyDynamicContent
  Localize/lang/strings.json
  libs/logic-apps-shared/src/designer-client-services/lib/base/connector.ts
Labels: Risk:Low

#7190 feat(vscode): New debug config provider for logic app project with custom code
  apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeNetHostProcess.test.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/CreateNewProjectInternal.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppFilesStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/initLogicAppCodeProjectVScode/InitCodeProject.ts
  apps/vs-code-designer/src/app/commands/debugLogicApp.ts
  apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
  apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/utils/__test__/customCodeUtils.test.ts
  apps/vs-code-designer/src/app/utils/azurite/activateAzurite.ts
  apps/vs-code-designer/src/app/utils/customCodeUtils.ts
  apps/vs-code-designer/src/constants.ts
  apps/vs-code-designer/src/main.ts
  apps/vs-code-designer/src/package.json
Labels: Risk:Medium

#7191 fix(vscode): Fix for Create Workspace from Package to properly create a workspace on deployment
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ExtractPackageStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ProcessPackageStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/cloudToLocal.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/cloudToLocalHelper.ts
Labels: Risk:Low

#7192 fix(Templates): Fixed query issue in Templates
  libs/designer/src/lib/core/templates/utils/queries.ts
  libs/designer/src/lib/ui/templates/review/ResourceDisplay.tsx
Labels: Risk:Low

#7193 fix(Templates): Fixed query issue in Templates
  libs/designer/src/lib/core/templates/utils/queries.ts
  libs/designer/src/lib/ui/templates/review/ResourceDisplay.tsx
Labels: Risk:Low

#7189 feat(Templates): Summary Tab + Publish & Unpublish Button with Logic handling
  Localize/lang/strings.json
  libs/designer/src/lib/common/constants.ts
  libs/designer/src/lib/core/configuretemplate/ConfigureTemplateWizard.tsx
  libs/designer/src/lib/core/configuretemplate/utils/helper.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/core/templates/utils/__test__/validation.spec.ts
  libs/designer/src/lib/core/templates/utils/helper.ts
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/model.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/profileTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/publishTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/summaryTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/templateprofile/connectors.tsx
  libs/designer/src/lib/ui/configuretemplate/templateprofile/manifestform.tsx
  libs/logic-apps-shared/src/utils/src/lib/models/template.ts
Labels: Risk:Low

#7197 fix(vscode): Fix for Create Workspace from Package to properly create a workspace on deployment
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ExtractPackageStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ProcessPackageStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/cloudToLocal.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/cloudToLocalHelper.ts
Labels: Risk:Low

#7205 feat(designer): Revert - Update 'maximumTokenCount' and 'messageCountLimit' settings as required
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low

#7201 feat(Templates): Download template button with downloadable content
  Localize/lang/strings.json
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/tabs/summaryTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
Labels: Risk:Low

#7203 feat(Templates): Split button for publish for workflow & parameter tabs
  libs/designer-ui/src/lib/templates/templatesPanelFooter.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/configureWorkflowsPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/tabs/customizeWorkflowsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/customizeParameterPanel/customizeParameterPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
  libs/logic-apps-shared/src/designer-client-services/lib/templateresource.ts
Labels: Risk:Low

#7204 fix(designer): Update error category to button
  libs/designer/src/lib/ui/panel/errorsPanel/errorCategory.tsx
Labels: Risk:Low

#7208 fix(designer): Revert of Reset id replacements when reset designer dirty state
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  libs/designer/src/lib/core/state/global.ts
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
Labels: Risk:Low

#7209 fix(designer): Revert of Reset id replacements when reset designer dirty state
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  libs/designer/src/lib/core/state/global.ts
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
Labels: Risk:Low

#7129 feat(Templates): Workflow Selection with User Input Resource Id & Duplicate Validation and handling
  Localize/lang/strings.json
  libs/designer-ui/src/lib/templates/model.ts
  libs/designer-ui/src/lib/templates/templatesContent.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/core/templates/utils/__test__/validation.spec.ts
  libs/designer/src/lib/core/templates/utils/helper.ts
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/configureWorkflowsPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/tabs/customizeWorkflowsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/selectWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
Labels: Risk:Low

#7212 fix(designer): Use the correct service for List Subscriptions
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
Labels: Risk:Low

#7213 fix(designer): Use the correct service for List Subscriptions
  Localize/lang/strings.json
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
Labels: Risk:Low

#7210 fix(designer): simple query builder `@not(contains(` being deserialized as as `@notcontains(`
  libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
Labels: Risk:Low

#7202 fix(designer): Fixed issue with \ in Dictionary editor serialization
  .gitignore
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureConsumptionLogicAppSelector.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureStandardLogicAppSelector.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Queries/FetchConsumptionApps.ts
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Queries/FetchStandardApps.ts
  apps/Standalone/src/designer/app/DesignerShell/designer.tsx
  apps/Standalone/src/environments/environment.ts
  libs/designer-ui/src/lib/editor/base/utils/keyvalueitem.ts
  libs/designer-ui/src/lib/flyout2/__test__/flyout2.spec.tsx
  libs/designer-ui/src/lib/tokenpicker/index.tsx
  libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Labels: Risk:Low

#7215 feat(vscode): Upload settings automatically after deployment
  apps/vs-code-designer/src/app/commands/appSettings/uploadAppSettings.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/cloudToLocalHelper.ts
  apps/vs-code-designer/src/app/commands/deploy/deploy.ts
  apps/vs-code-designer/src/app/commands/deploy/notifyDeployComplete.ts
  apps/vs-code-designer/src/app/tree/LogicAppResourceTree.ts
  apps/vs-code-designer/src/app/utils/codeless/hybridLogicApp/hybridApp.ts
  apps/vs-code-designer/src/constants.ts
Labels: Risk:Low

#7218 fix(designer): Update chat scrollbar styles
  libs/chatbot/src/lib/ui/styles.less
Labels: Cosmetic, Risk:Low

#7217 fix(designer): Create Exception of whitespace check on #
  libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Labels: Risk:Low

#7219 fix(designer): Fixing Search not showing operations in Agentic Loops
  libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
Labels: Risk:Low

#7220 fix(designer): Fixing Search not showing operations in Agentic Loops
  libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
Labels: Risk:Low

#7221 feat(templates): Minor css and interface changes in template wizard for integration
  apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
  libs/designer-ui/src/lib/templates/templatesSection.tsx
  libs/designer-ui/src/lib/templates/templatesSectionModel.ts
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/configuretemplate/ConfigureTemplateWizard.tsx
  libs/designer/src/lib/core/index.ts
  libs/designer/src/lib/ui/configuretemplate/toasters.tsx
  libs/designer/src/lib/ui/index.tsx
  libs/designer/src/lib/ui/templates/styles.less
  libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
  libs/logic-apps-shared/src/designer-client-services/lib/templateresource.ts
Labels: Risk:Low

#7179 feat(vscode): Unit Test GA
  apps/vs-code-designer/src/README.md
  apps/vs-code-designer/src/assets/UnitTestTemplates/TestProjectFile
  apps/vs-code-react/src/app/designer/DesignerCommandBar/index.tsx
Labels: Risk:Low

#7228 fix(vscode): Add fallback for function core tools installation
  apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts
  apps/vs-code-designer/src/app/commands/nodeJs/validateNodeJsIsLatest.ts
  apps/vs-code-designer/src/app/utils/__test__/binaries.test.ts
  apps/vs-code-designer/src/app/utils/binaries.ts
  apps/vs-code-designer/src/app/utils/nodeJs/nodeJsVersion.ts
  apps/vs-code-designer/src/constants.ts
Labels: Risk:Low

#7229 fix(vscode): Add fallback for function core tools installation
  apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts
  apps/vs-code-designer/src/app/commands/nodeJs/validateNodeJsIsLatest.ts
  apps/vs-code-designer/src/app/utils/__test__/binaries.test.ts
  apps/vs-code-designer/src/app/utils/binaries.ts
  apps/vs-code-designer/src/app/utils/nodeJs/nodeJsVersion.ts
  apps/vs-code-designer/src/constants.ts
Labels: Risk:Low

#7227 feat(templates): Adding rollback functionality in batch save methods and download template
  Localize/lang/strings.json
  apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
  libs/designer-ui/src/lib/templates/templatesPanelFooter.tsx
  libs/designer/package.json
  libs/designer/src/lib/core/actions/bjsworkflow/__test__/configuretemplate.spec.ts
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/configuretemplate/utils/helper.ts
  libs/designer/src/lib/core/configuretemplate/utils/queries.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/summaryTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/selectWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/templates/styles.less
  libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
  libs/logic-apps-shared/src/designer-client-services/lib/templateresource.ts
  libs/logic-apps-shared/src/utils/src/lib/models/template.ts
  pnpm-lock.yaml
Labels: Risk:Low

#7233 feat(templates): Fit and Finish of custom templates with exporting methods for portal
  Localize/lang/strings.json
  libs/designer-ui/src/lib/templates/templatesPanelFooter.tsx
  libs/designer/src/lib/core/configuretemplate/utils/helper.ts
  libs/designer/src/lib/core/index.ts
  libs/designer/src/lib/ui/configuretemplate/common.tsx
  libs/designer/src/lib/ui/configuretemplate/connections/connectionslist.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/tabs/customizeWorkflowsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/tabs/selectWorkflowsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/customizeParameterPanel/customizeParameterPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/customizeParameter.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/parameterslist.tsx
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/parametersTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/profileTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/summaryTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/workflowsTab.tsx
  libs/designer/src/lib/ui/configuretemplate/templateprofile/connectors.tsx
  libs/designer/src/lib/ui/configuretemplate/templateprofile/manifestform.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/selectWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/basicsTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/parametersTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/tabs/reviewCreateTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/summaryTab.tsx
  libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/tabs/workflowTab.tsx
  libs/logic-apps-shared/src/utils/src/lib/models/template.ts
Labels: Risk:Low

#7238 fix(vscode): Add tenant ID to get auth token on generate IaC scripts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
Labels: Risk:Low

#7245 fix(designer): Update string and channels condition
  libs/designer-ui/src/lib/settings/settingsection/settingslider.tsx
  libs/designer-ui/src/lib/settings/settingsection/settingtoggle.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low

#7246 fix(designer): Update string and channels condition (#7245)
  libs/designer-ui/src/lib/settings/settingsection/settingslider.tsx
  libs/designer-ui/src/lib/settings/settingsection/settingtoggle.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low

#6968 Feat(VSCode): able to create codeful workflows
  apps/vs-code-designer/src/app/commands/createCodeful/CodefulWorkflowCreateStep.ts
  apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/CodelessWorkflowCreateStep.ts
  apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/WorkflowCreateStepBase.ts
  apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/WorkflowStateTypeStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/NewCodeProjectTypeStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/CodelessFunctionWorkflow.ts
  apps/vs-code-designer/src/app/commands/createWorkflow/WorkflowCodeTypeStep.ts
  apps/vs-code-designer/src/app/commands/createWorkflow/createWorkflow.ts
  apps/vs-code-designer/src/app/commands/dotnet/validateDotNetInstalled.ts
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts
  apps/vs-code-designer/src/app/utils/appSettings/localSettings.ts
  apps/vs-code-designer/src/app/utils/codeless/common.ts
  apps/vs-code-designer/src/app/utils/codeless/connection.ts
  apps/vs-code-designer/src/app/utils/codeless/parameter.ts
  apps/vs-code-designer/src/app/utils/codeless/templates.ts
  apps/vs-code-designer/src/app/utils/codeless/updateBuildFile.ts
  apps/vs-code-designer/src/app/utils/dotnet/executeDotnetTemplateCommand.ts
  apps/vs-code-designer/src/app/utils/verifyIsProject.ts
  apps/vs-code-designer/src/assets/CodefulWorkflowTemplate/codefulTemplate.cs
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.DotNet.Cli.CommandLine.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Abstractions.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Cli.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Core.Contracts.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Core.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Edge.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.JsonCli.deps.json
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.JsonCli.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.JsonCli.runtimeconfig.json
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Orchestrator.RunnableProjects.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateEngine.Utils.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Microsoft.TemplateSearch.Common.dll
  apps/vs-code-designer/src/assets/dotnetJsonCli/net8.0/Newtonsoft.Json.dll
  apps/vs-code-designer/src/constants.ts
  apps/vs-code-designer/src/package.json
  libs/vscode-extension/src/lib/models/functions.ts
Labels: Risk:Low

#7243 fix(vscode): Fixed error when generating deployment scripts
  apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
Labels: Risk:Low

#7256 fix(vscode): Unit Test Sanitize Logic App name
  apps/vs-code-designer/src/app/utils/__test__/unitTestUtils.test.ts
  apps/vs-code-designer/src/app/utils/unitTests.ts
Labels: Risk:Low

#7248 feat(templates): Adding error handling from save failure and showing them at appropriate sections in the UI
  Localize/lang/strings.json
  apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/HttpClient.ts
  libs/designer-ui/src/lib/templates/templatesSection.tsx
  libs/designer/src/lib/common/images/templates/openbook.svg
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/actions/bjsworkflow/templates.ts
  libs/designer/src/lib/core/configuretemplate/utils/errors.ts
  libs/designer/src/lib/core/state/templates/templateSlice.ts
  libs/designer/src/lib/core/templates/utils/__test__/validation.spec.ts
  libs/designer/src/lib/core/templates/utils/helper.ts
  libs/designer/src/lib/ui/configuretemplate/common.tsx
  libs/designer/src/lib/ui/configuretemplate/connections/connectionslist.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/customizeParameter.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/parameterslist.tsx
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/templateprofile/connectors.tsx
  libs/designer/src/lib/ui/configuretemplate/templateprofile/manifestform.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/templateresource.ts
Labels: Risk:Low

#7266 fix(designer): Reverting part of https://github.com/Azure/LogicAppsUX/pull/7006
  libs/designer/src/lib/core/utils/parameters/__test__/segment.spec.ts
  libs/designer/src/lib/core/utils/parameters/segment.ts
Labels: Risk:Low

#7267 fix(designer): Reverting part of https://github.com/Azure/LogicAppsUX/pull/7006
  libs/designer/src/lib/core/utils/parameters/__test__/segment.spec.ts
  libs/designer/src/lib/core/utils/parameters/segment.ts
Labels: Risk:Low

#7268 fix(designer): Enable colorization and auto-indentation in Expression Editor
  libs/designer-ui/src/lib/editor/monaco/index.tsx
  libs/designer-ui/src/lib/expressioneditor/index.tsx
  libs/designer-ui/src/lib/workflow/languageservice/workflowlanguageservice.ts
Labels: Risk:Low

#7271 chore: Add Copilot Instructions
  .github/copilot-instructions.md
Labels: Risk:Low

#7274 feat(templates): Adding created and last modified column in workflows and toaster
  Localize/lang/strings.json
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/configuretemplate/utils/helper.ts
  libs/designer/src/lib/core/configuretemplate/utils/queries.ts
  libs/designer/src/lib/core/templates/utils/createhelper.ts
  libs/designer/src/lib/ui/configuretemplate/connections/connectionslist.tsx
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/templateprofile/connectors.tsx
  libs/designer/src/lib/ui/configuretemplate/toasters.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/logic-apps-shared/src/utils/src/lib/helpers/connectors.ts
  libs/logic-apps-shared/src/utils/src/lib/models/armresource.ts
Labels: Risk:Low

#7279 fix(vscode): Auto update function core tools for major version difference
  apps/vs-code-designer/src/app/commands/funcCoreTools/validateFuncCoreToolsIsLatest.ts
Labels: Risk:Low

#7277 feat(vscode): Unit Test Status Code
  apps/vs-code-designer/src/app/utils/__test__/unitTestUtils.test.ts
  apps/vs-code-designer/src/app/utils/unitTests.ts
Labels: Risk:Low

#7254 feat(designer): Add agent foundry service integration connection
  Localize/lang/strings.json
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionWrapper.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/useCognitiveService.ts
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/formInputs/universalConnectionParameter.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/connectionInline.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/helpers.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/hooks.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/cognitiveService.ts
  libs/logic-apps-shared/src/designer-client-services/lib/cognitiveService.ts
  libs/logic-apps-shared/src/designer-client-services/lib/experimentationFlags.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/index.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low

#7297 fix(templates): Adding info bubble support and text for workflow customization wizard
  Localize/lang/strings.json
  libs/designer-ui/src/lib/templates/templatesSection.tsx
  libs/designer-ui/src/lib/templates/templatesSectionModel.ts
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
Labels: Risk:Low

#7291 fix(Templates): UI fixes to enforce consistency & Remove placeholder links
  Localize/lang/strings.json
  apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
  libs/designer/src/lib/core/configuretemplate/utils/helper.ts
  libs/designer/src/lib/core/templates/utils/__test__/validation.spec.ts
  libs/designer/src/lib/core/templates/utils/helper.ts
  libs/designer/src/lib/ui/configuretemplate/common.tsx
  libs/designer/src/lib/ui/configuretemplate/connections/connectionslist.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/customizeParameterPanel/customizeParameterPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/customizeParameter.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/parameterslist.tsx
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/profileTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/templateprofile/manifestform.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/templates/styles.less
Labels: Risk:Low

#7300 fix(Templates): Fixed connection name and type not showing up in review tab
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
Labels: Risk:Low

#7301 fix(Templates): Updating hotfix branch with three fixes
  Localize/lang/strings.json
  apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
  libs/designer-ui/src/lib/templates/templatesSection.tsx
  libs/designer-ui/src/lib/templates/templatesSectionModel.ts
  libs/designer/src/lib/core/configuretemplate/utils/helper.ts
  libs/designer/src/lib/core/templates/utils/__test__/validation.spec.ts
  libs/designer/src/lib/core/templates/utils/helper.ts
  libs/designer/src/lib/ui/configuretemplate/common.tsx
  libs/designer/src/lib/ui/configuretemplate/connections/connectionslist.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/customizeParameterPanel/customizeParameterPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/customizeParameter.tsx
  libs/designer/src/lib/ui/configuretemplate/parameters/parameterslist.tsx
  libs/designer/src/lib/ui/configuretemplate/resources.ts
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/profileTab.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/templateprofile/manifestform.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/workflowslist.tsx
  libs/designer/src/lib/ui/templates/styles.less
Labels: Risk:Low

#7303 fix(designer): Agents in Hybrid not working
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
Labels: Risk:Low

#7306 fix(designer): Update open AI endpoint for foundry connections
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
Labels: Risk:Low

#7311 fix(vscode): Initialize custom connection parameter editor service
  Localize/lang/strings.json
  apps/vs-code-react/src/app/designer/services/customConnectionParameterEditorService.ts
  apps/vs-code-react/src/app/designer/servicesHelper.ts
  apps/vs-code-react/src/app/services/Logger.ts
  libs/vscode-extension/src/lib/services/__test__/httpClient.spec.ts
  libs/vscode-extension/src/lib/services/httpClient.ts
Labels: Risk:Low

#7313 fix(vscode): Initialize custom connection parameter editor service
  apps/vs-code-react/src/app/designer/services/customConnectionParameterEditorService.ts
  apps/vs-code-react/src/app/designer/servicesHelper.ts
  apps/vs-code-react/src/app/services/Logger.ts
  libs/vscode-extension/src/lib/services/__test__/httpClient.spec.ts
  libs/vscode-extension/src/lib/services/httpClient.ts
Labels: Risk:Low

#7325 fix(Designer): Variable/Hybrid Cherry picks
  libs/designer-ui/src/lib/editor/initializevariable/__test__/util.spec.tsx
  libs/designer-ui/src/lib/editor/initializevariable/index.tsx
  libs/designer-ui/src/lib/editor/initializevariable/util.ts
  libs/designer-ui/src/lib/tokenpicker/index.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Labels: Risk:Low

#7326 fix(designer): Cherry Pick Initialize Variable
  libs/designer-ui/src/lib/editor/initializevariable/__test__/util.spec.tsx
  libs/designer-ui/src/lib/editor/initializevariable/index.tsx
  libs/designer-ui/src/lib/editor/initializevariable/util.ts
  libs/designer-ui/src/lib/tokenpicker/index.tsx
  libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/stringFunctions.spec.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/stringFunctions.ts
Labels: Risk:Low

#7330 fix(Templates): Fix typo in description
  Localize/lang/strings.json
  libs/designer/src/lib/ui/configuretemplate/connections/connectionslist.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/selectWorkflows.tsx
Labels: Risk:Low

#7328 fix(Templates): Fix typo in description
  Localize/lang/strings.json
  libs/designer/src/lib/ui/configuretemplate/connections/connectionslist.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/selectWorkflows.tsx
Labels: Risk:Low

#7345 fix(Templates): Update parameter blocked on error
  Localize/lang/strings.json
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/configureWorkflowsPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/customizeParameterPanel/customizeParameterPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
Labels: Risk:Low

#7357 feat(designer): Add UX support for chunktextwithmetadata in standard
  libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
Labels: Risk:Low

#7375 fix(vscode): Add noAuth to run trigger
  libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
Labels: Risk:Low

#7377 fix(vscode): Add noAuth to run trigger (#7375)
  libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
Labels: Risk:Low

#7389 fix(templates): Fixing saving template manifest when workflows change
  apps/Standalone/src/configuretemplate/app/LocalConfigureTemplate.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/configuretemplate.ts
  libs/designer/src/lib/core/configuretemplate/utils/queries.ts
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/review/TemplateReviewList.tsx
  libs/designer/src/lib/ui/configuretemplate/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/configuretemplate/workflows/customizeWorkflows.tsx
Labels: Risk:Low

#7288 docs(repo): Update README file
  README.md
Labels: Risk:Low

#7393 chore(vscode): Remove access token from run service
  apps/vs-code-react/src/app/designer/servicesHelper.ts
  apps/vs-code-react/src/app/overview/app.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/index.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
  libs/vscode-extension/src/lib/models/connection.ts
Labels: Risk:Low
