Repository Azure/LogicAppsUX, pull requests merged in 2025-10, with the labels that each got.

#8308 chore(ci): add changelog update pipeline
  .github/workflows/update-changelog.yml
Labels: Risk:Low, pr-validated

#8307 fix(vscode): Build custom code on deploy, handle error when fails to attach to custom code worker
  apps/vs-code-designer/src/app/commands/__test__/buildCustomCodeFunctionsProject.test.ts
  apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeWorkerProcess.test.ts
  apps/vs-code-designer/src/app/commands/buildCustomCodeFunctionsProject.ts
  apps/vs-code-designer/src/app/commands/debugLogicApp.ts
  apps/vs-code-designer/src/app/commands/deploy/deploy.ts
  apps/vs-code-designer/src/app/commands/pickCustomCodeWorkerProcess.ts
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesigner.ts
Labels: VSCode, Risk:Low, pr-validated, bug

#8315 fix(vscode): Build custom code on deploy, handle error when fails to attach to custom code worker
  apps/vs-code-designer/src/app/commands/__test__/buildCustomCodeFunctionsProject.test.ts
  apps/vs-code-designer/src/app/commands/__test__/pickCustomCodeWorkerProcess.test.ts
  apps/vs-code-designer/src/app/commands/buildCustomCodeFunctionsProject.ts
  apps/vs-code-designer/src/app/commands/debugLogicApp.ts
  apps/vs-code-designer/src/app/commands/deploy/deploy.ts
  apps/vs-code-designer/src/app/commands/pickCustomCodeWorkerProcess.ts
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesigner.ts
Labels: Risk:Low, pr-validated

#8316 docs: update changelog for release
  CHANGELOG.md
Labels: Risk:Low, pr-validated

#8317 chore(ci): generate release notes from target branch head
  .github/workflows/update-changelog.yml
Labels: Risk:Low, pr-validated

#8322 chore(vscode): remove authentication API proposal flag
  apps/vs-code-designer/src/package.json
Labels: Risk:Low, pr-validated

#8310 feat(mcp): Adding capability of setting connector and logic app from caller in mcp wizard
  Localize/lang/strings.json
  apps/Standalone/src/mcp/app/McpStandard.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/mcp.ts
  libs/designer/src/lib/core/mcp/McpDataProvider.tsx
  libs/designer/src/lib/core/state/mcp/mcpOptions/mcpOptionsSlice.ts
  libs/designer/src/lib/core/state/mcp/mcpselectionslice.ts
  libs/designer/src/lib/core/state/mcp/panel/mcpPanelSlice.ts
  libs/designer/src/lib/core/state/mcp/resourceSlice.ts
  libs/designer/src/lib/ui/mcp/connectors/ListConnectors.tsx
  libs/designer/src/lib/ui/mcp/details/logicAppSelector.tsx
  libs/designer/src/lib/ui/mcp/details/styles.ts
  libs/designer/src/lib/ui/mcp/panel/connector/usePanelTabs.tsx
  libs/designer/src/lib/ui/mcp/panel/logicapp/usepaneltabs.tsx
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Labels: Risk:Medium, pr-validated

#8325 fix(vscode): improve extension bundle path parsing for multi-line command output
  apps/vs-code-designer/src/app/utils/__test__/bundleFeed.test.ts
  apps/vs-code-designer/src/app/utils/bundleFeed.ts
Labels: Risk:Medium, pr-validated

#8338 docs(vscode): update main changelog with v5.185.7 and v5.185.6 releases
  CHANGELOG.md
Labels: Risk:Low, pr-validated

#8339 fix(Standalone): Fixed standalone `onRunSelected` variable reference issue
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerV2.tsx
Labels: Risk:Low, pr-validated

#8345 fix(vscode): Start runtime api in background on designer open for each project
  apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
  apps/vs-code-designer/src/app/debug/validatePreDebug.ts
  apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
  apps/vs-code-designer/src/app/utils/startRuntimeApi.ts
  apps/vs-code-designer/src/extensionVariables.ts
Labels: VSCode, Risk:Medium, pr-validated, bug

#8341 feat(designerv2): Add run draft for non A2A workflows
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerV2.tsx
  libs/designer-v2/src/lib/ui/FloatingRunButton/index.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
Labels: Risk:Low, pr-validated

#8348 fix(designer): Hide Agent Loop Behind Connector + Fix Agentic in Consumption
  apps/Standalone/src/vscode/services/mockConnectorData/agent.ts
  apps/Standalone/src/vscode/services/mockConnectorData/index.ts
  libs/designer/src/lib/core/state/designerView/designerViewSelectors.ts
  libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
  libs/designer/src/lib/ui/panel/recommendation/hooks.ts
  libs/designer/src/lib/ui/panel/recommendation/operationGroupDetailView.tsx
  libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/experimentation.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/manifests/agentLoopConnector.ts
  libs/logic-apps-shared/src/designer-client-services/lib/experimentationFlags.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
Labels: Risk:Low, pr-validated

#8350 fix(vscode): temporarily remove validatePartial, startRuntimeApi to mitigate designer issues
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
Labels: VSCode, Risk:Medium, pr-validated, bug
