Repository Azure/LogicAppsUX, pull requests merged in 2025-07, with the labels that each got.

#7673 fix(designer): Simplify Simple Query Builder state to eliminate prop/segment sync issues
  libs/designer-ui/src/lib/editor/initializevariable/__test__/util.spec.tsx
  libs/designer-ui/src/lib/querybuilder/Row.tsx
  libs/designer-ui/src/lib/querybuilder/SimpleQueryBuilder.tsx
  libs/designer-ui/src/lib/querybuilder/__test__/QueryBuilderEditor.spec.tsx
  libs/designer-ui/src/lib/querybuilder/__test__/integration.spec.tsx
  libs/designer-ui/src/lib/querybuilder/__test__/test-utils.tsx
  libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
  libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
  libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
Labels: pr-validated

#7680 fix(designer): Modify OAuth to accept parameter Name
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/OAuthService.ts
  apps/vs-code-react/src/app/designer/services/oAuth.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/connection.ts
  libs/logic-apps-shared/src/designer-client-services/lib/oAuth.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connection.ts
Labels: pr-validated

#7676 fix(templates): Migrate templates gallery to makeStyles and fix alignment issues
  libs/designer/src/lib/ui/templates/filters/templatesearchfilters.styles.ts
  libs/designer/src/lib/ui/templates/filters/templatesearchfilters.tsx
  libs/designer/src/lib/ui/templates/gallery/templatesgallery.styles.ts
  libs/designer/src/lib/ui/templates/gallery/templatesgallery.tsx
  libs/designer/src/lib/ui/templates/gallery/templatesgallerywithsearch.styles.ts
  libs/designer/src/lib/ui/templates/styles.less
Labels: pr-validated

#7678 feat(designer-ui): Migrate addActionCard component to Fluent UI v9
  libs/designer-ui/src/lib/card/addActionCard/__test__/__snapshots__/addActionCard.spec.tsx.snap
  libs/designer-ui/src/lib/card/addActionCard/__test__/addActionCard.spec.tsx
  libs/designer-ui/src/lib/card/addActionCard/addActionCard.styles.ts
  libs/designer-ui/src/lib/card/addActionCard/index.tsx
Labels: pr-validated

#7681 fix(Designer): Fixed missed handle instances
  libs/designer/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
Labels: Risk:Low, pr-validated

#7647 fix(vscode): Update servicesHelper configuration and connector service inheritance
  apps/vs-code-react/src/app/designer/services/connector.ts
  apps/vs-code-react/src/app/designer/servicesHelper.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/connector.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/index.ts
  libs/logic-apps-shared/src/utils/src/lib/models/operationmanifest.ts
Labels: pr-validated

#7686 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250702112029863 to main
  Localize/loc/de/strings.json.lcl
  Localize/loc/fr/strings.json.lcl
  Localize/loc/hu/strings.json.lcl
  Localize/loc/id/strings.json.lcl
  Localize/loc/ja/strings.json.lcl
  Localize/loc/ru/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7682 fix(vscode): Always upload app settings during Logic App deployment
  apps/vs-code-designer/src/app/commands/deploy/deploy.ts
Labels: Risk:Low

#7685 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250702051922065 to main
  Localize/loc/ko/strings.json.lcl
  Localize/loc/zh-Hans/strings.json.lcl
  Localize/loc/zh-Hant/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7692 feat(vscode): Add multi-initialize support based on extension bundle ID
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
  apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForLocal.ts
  apps/vs-code-designer/src/app/utils/__test__/getDebugSymbolDll.test.ts
  apps/vs-code-designer/src/app/utils/getDebugSymbolDll.ts
  apps/vs-code-react/src/app/designer/app.tsx
  apps/vs-code-react/src/app/designer/servicesHelper.ts
  libs/vscode-extension/src/lib/models/workflow.ts
Labels: pr-validated

#7694 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250702172024802 to main
  Localize/loc/es/strings.json.lcl
  Localize/loc/nl/strings.json.lcl
  Localize/loc/pl/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7693 fix(vscode): "Use connectors from Azure" for workspace with multiple logic apps
  apps/vs-code-designer/src/app/commands/workflows/enableAzureConnectors.ts
Labels: pr-validated

#7640 fix(vscode): Update flow validation call in VSCode designer to utilize new validation API route
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
Labels: Risk:Low, pr-validated, bug

#7697 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250702232808048 to main
  Localize/loc/cs/strings.json.lcl
  Localize/loc/it/strings.json.lcl
  Localize/loc/pt-BR/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7698 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250703021848214 to main
  Localize/loc/sv/strings.json.lcl
  Localize/loc/tr/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7701 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 917
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7703 fix(Designer): Update control buttons style to use content-box sizing
  libs/designer/src/lib/ui/styles.less
Labels: pr-validated

#7704 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250703141930799 to main
  Localize/loc/fr/strings.json.lcl
  Localize/loc/ja/strings.json.lcl
  Localize/loc/pt-PT/strings.json.lcl
  Localize/loc/sv/strings.json.lcl
  Localize/loc/zh-Hans/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7699 feat(Designer): Add visible close button to template panels
  Localize/lang/strings.json
  e2e/templates/app.spec.ts
  e2e/templates/viewtemplate.spec.ts
  libs/designer-ui/src/lib/templates/templatesPanelHeader.styles.ts
  libs/designer-ui/src/lib/templates/templatesPanelHeader.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/configureWorkflowsPanel/configureWorkflowsPanel.tsx
  libs/designer/src/lib/ui/configuretemplate/panels/customizeParameterPanel/customizeParameterPanel.tsx
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/createWorkflowPanel.styles.ts
  libs/designer/src/lib/ui/panel/templatePanel/createWorkflowPanel/createWorkflowPanel.tsx
  libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/quickViewPanel.styles.ts
  libs/designer/src/lib/ui/panel/templatePanel/quickViewPanel/quickViewPanel.tsx
Labels: pr-validated

#7705 feat(vscode): Add multi-initialize support based on extension bundle ID
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
  apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForLocal.ts
  apps/vs-code-designer/src/app/utils/__test__/getDebugSymbolDll.test.ts
  apps/vs-code-designer/src/app/utils/getDebugSymbolDll.ts
  apps/vs-code-react/src/app/designer/app.tsx
  apps/vs-code-react/src/app/designer/servicesHelper.ts
  libs/vscode-extension/src/lib/models/workflow.ts
Labels: pr-validated

#7684 feat(Designer): Introducing A2A Workflows
  Localize/lang/strings.json
  __mocks__/workflows/Agents.json
  __mocks__/workflows/BlankAgents.json
  apps/Standalone/src/designer/app/LocalDesigner/LogicAppSelector/LogicAppSelector.tsx
  apps/vs-code-designer/src/constants.ts
  libs/designer-ui/src/lib/card/__test__/__snapshots__/card.spec.tsx.snap
  libs/designer-ui/src/lib/card/addActionCard/index.tsx
  libs/designer-ui/src/lib/card/card.less
  libs/designer-ui/src/lib/card/index.tsx
  libs/designer-ui/src/lib/card/utils.ts
  libs/designer-ui/src/lib/constants.ts
  libs/designer-ui/src/lib/documentationlinkitem/images/defaulticon.svg
  libs/designer-ui/src/lib/imagewithfallback/__test__/imagewithfallback.spec.tsx
  libs/designer-ui/src/lib/imagewithfallback/index.tsx
  libs/designer-ui/src/lib/index.ts
  libs/designer-ui/src/lib/mixedinputeditor/__tests__/mixedinputeditor.spec.tsx
  libs/designer-ui/src/lib/mixedinputeditor/mixedinputeditor.tsx
  libs/designer-ui/src/lib/mixedinputeditor/mixedinputeditorhelper.tsx
  libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
  libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
  libs/designer/src/lib/ui/common/DesignerContextualMenu/DesignerContextualMenu.tsx
  libs/designer/src/lib/ui/common/EdgeContextualMenu/EdgeContextualMenu.tsx
  libs/designer/src/lib/ui/common/EdgeContextualMenu/customMenu.tsx
  libs/designer/src/lib/ui/connections/dropzone.tsx
  libs/designer/src/lib/ui/connections/helpers.ts
  libs/designer/src/lib/ui/menuItems/deleteMenuItem.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
  libs/designer/src/lib/ui/panel/recommendation/operationGroupDetailView.tsx
  libs/designer/src/lib/ui/panel/recommendation/searchView.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/manifests/a2arequest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/operationmanifest.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/localStorage.ts
  libs/logic-apps-shared/src/utils/src/lib/models/dropdownMenuItem.ts
Labels: pr-validated

#7709 feat(Mcp): Skeleton standalone initial setup
  apps/Standalone/src/App.tsx
  apps/Standalone/src/mcp/app/McpShell.tsx
  apps/Standalone/src/mcp/app/McpStandard.tsx
  apps/Standalone/src/mcp/components/DevToolbox.tsx
  apps/Standalone/src/mcp/state/Store.ts
  apps/Standalone/src/mcp/state/WorkflowLoader.ts
  libs/designer/src/lib/core/index.ts
  libs/designer/src/lib/core/mcp/McpDataProvider.tsx
  libs/designer/src/lib/core/mcp/McpWizardContext.ts
  libs/designer/src/lib/core/mcp/McpWizardProvider.tsx
  libs/designer/src/lib/ui/index.tsx
  libs/designer/src/lib/ui/mcp/McpWizard.tsx
  libs/designer/src/lib/ui/mcp/index.tsx
Labels: pr-validated

#7710 fix(designer): Create new deployment model resource modal styles and close functionality
  libs/designer-ui/src/lib/settings/settingsection/styles.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/custom/deploymentModelResource.tsx
Labels: pr-validated

#7716 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250703231905624 to main
  Localize/loc/id/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7718 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 918
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7723 feat(vscode): Add .NET 8 in-process settings to Logic Apps creation
  Localize/lang/strings.json
  apps/vs-code-designer/src/app/commands/createCodeless/createCodelessSteps/CodelessWorkflowCreateStep.ts
  apps/vs-code-designer/src/app/commands/createLogicApp/createLogicAppSteps/LogicAppCreateStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/CodelessFunctionWorkflow.ts
  apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/ScriptProjectCreateStep.ts
  apps/vs-code-designer/src/app/commands/dataMapper/FxWorkflowRuntime.ts
  apps/vs-code-designer/src/app/commands/syncCloudSettings.ts
  apps/vs-code-designer/src/app/utils/appSettings/__test__/localSettings.test.ts
  apps/vs-code-designer/src/app/utils/appSettings/localSettings.ts
  apps/vs-code-designer/src/app/utils/codeless/hybridLogicApp/hybridApp.ts
  apps/vs-code-designer/src/app/utils/codeless/startDesignTimeApi.ts
  apps/vs-code-designer/src/constants.ts
Labels: pr-validated

#7731 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 920
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7734 fix(Designer): Fixed nested loop issue stemming from timeline component changes
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
Labels: Risk:Low, pr-validated

#7735 fix(Designer): Fixed nested loop issue stemming from timeline component changes
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
Labels: pr-validated

#7738 fix(designer): Properly handling converting view model back into parameter value
  libs/designer-ui/src/lib/editor/initializevariable/__test__/util.spec.tsx
  libs/designer-ui/src/lib/editor/shared/testtokensegment.ts
  libs/designer-ui/src/lib/flyout/__test__/__snapshots__/flyout.spec.tsx.snap
  libs/designer-ui/src/lib/flyout2/__test__/__snapshots__/flyout2.spec.tsx.snap
  libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheadercomment.spec.tsx.snap
  libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheadertitle.spec.tsx.snap
  libs/designer/src/lib/core/utils/parameters/__test__/helper.spec.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
Labels: pr-validated

#7633 Fixed broken Data Mapper deserialization tests
  Localize/lang/strings.json
  libs/data-mapper-v2/src/__mocks__/schemas/ComprehensiveSourceSchema.json
  libs/data-mapper-v2/src/__mocks__/schemas/ComprehensiveSourceSchema.ts
  libs/data-mapper-v2/src/__mocks__/schemas/ComprehensiveTargetSchema.ts
  libs/data-mapper-v2/src/__mocks__/schemas/DeepNestedSequenceAndObj.json
  libs/data-mapper-v2/src/__mocks__/schemas/DeepNestedSequenceAndObjXsd.ts
  libs/data-mapper-v2/src/__mocks__/schemas/SourceSchema.json
  libs/data-mapper-v2/src/__mocks__/schemas/SourceSchemaJson.ts
  libs/data-mapper-v2/src/__mocks__/schemas/SourceSchemaXsd.ts
  libs/data-mapper-v2/src/__mocks__/schemas/TargetSchema.json
  libs/data-mapper-v2/src/__mocks__/schemas/TargetSchemaJson.json
  libs/data-mapper-v2/src/__mocks__/schemas/TargetSchemaJson.ts
  libs/data-mapper-v2/src/__mocks__/schemas/TargetSchemaXsd.ts
  libs/data-mapper-v2/src/__mocks__/schemas/index.ts
  libs/data-mapper-v2/src/mapHandling/__test__/MapDefinitionDeserializer.spec.ts
  libs/data-mapper-v2/src/mapHandling/__test__/MapHandlingTestUtilis.ts
Labels: Risk:Low, pr-validated

#7729 feat(mcp): Starting Connectors on MCP
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/LogicAppSelectionSetting/AzureStandardLogicAppSelector.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
  apps/Standalone/src/mcp/app/McpShell.tsx
  apps/Standalone/src/mcp/app/McpStandard.tsx
  apps/Standalone/src/mcp/app/styles.ts
  apps/Standalone/src/mcp/components/DevToolbox.tsx
  apps/Standalone/src/mcp/components/styles.ts
  apps/Standalone/src/mcp/state/WorkflowLoader.ts
  libs/designer-ui/src/lib/connectorsummarycard/index.tsx
  libs/designer-ui/src/lib/panel/recommendationpanel/browseResults.tsx
  libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchHeader/index.tsx
  libs/designer-ui/src/lib/panel/recommendationpanel/recommendationPanelCard/index.tsx
  libs/designer/src/lib/core/mcp/McpDataProvider.tsx
  libs/designer/src/lib/core/mcp/McpWizardProvider.tsx
  libs/designer/src/lib/core/state/mcp/mcpOptions/mcpOptionsInterface.ts
  libs/designer/src/lib/core/state/mcp/mcpOptions/mcpOptionsSelector.ts
  libs/designer/src/lib/core/state/mcp/mcpOptions/mcpOptionsSlice.ts
  libs/designer/src/lib/core/state/mcp/panel/mcpPanelSlice.ts
  libs/designer/src/lib/core/state/mcp/store.ts
  libs/designer/src/lib/ui/index.tsx
  libs/designer/src/lib/ui/mcp/McpWizard.tsx
  libs/designer/src/lib/ui/mcp/index.tsx
  libs/designer/src/lib/ui/mcp/panel/ConnectorBrowseView.tsx
  libs/designer/src/lib/ui/mcp/panel/ConnectorSelectionPanel.tsx
  libs/designer/src/lib/ui/mcp/panel/connectorSelectionStyles.ts
  libs/designer/src/lib/ui/mcp/panel/mcpPanelRoot.tsx
  libs/designer/src/lib/ui/mcp/panel/styles.ts
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
  libs/designer/src/lib/ui/mcp/wizard/styles.ts
Labels: pr-validated

#7745 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250709051925011 to main
  Localize/loc/de/strings.json.lcl
  Localize/loc/fr/strings.json.lcl
  Localize/loc/zh-Hans/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7757 feat(Mcp): Connector panel structure with tabs navigation
  Localize/lang/strings.json
  libs/designer-ui/src/lib/index.ts
  libs/designer-ui/src/lib/mcp/index.ts
  libs/designer-ui/src/lib/mcp/model.ts
  libs/designer/src/lib/common/constants.ts
  libs/designer/src/lib/core/state/mcp/panel/mcpPanelSlice.ts
  libs/designer/src/lib/ui/mcp/connectors/ConnectorBrowseView.tsx
  libs/designer/src/lib/ui/mcp/connectors/SelectConnectors.tsx
  libs/designer/src/lib/ui/mcp/connectors/connectorSelectionStyles.ts
  libs/designer/src/lib/ui/mcp/operations/SelectOperations.tsx
  libs/designer/src/lib/ui/mcp/panel/ConnectorSelectionPanel.tsx
  libs/designer/src/lib/ui/mcp/panel/OperationSelectionPanel.tsx
  libs/designer/src/lib/ui/mcp/panel/connectorPanel/ConnectorPanel.tsx
  libs/designer/src/lib/ui/mcp/panel/connectorPanel/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/mcp/panel/connectorPanel/tabs/connectorsTab.tsx
  libs/designer/src/lib/ui/mcp/panel/connectorPanel/tabs/operationsTab.tsx
  libs/designer/src/lib/ui/mcp/panel/connectorPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/mcp/panel/mcpPanelRoot.tsx
  libs/designer/src/lib/ui/mcp/panel/styles.ts
Labels: pr-validated

#7760 chore(vscode): Update vscode-azext-azureutils to 0.3.9-beta
  apps/vs-code-designer/package.json
  apps/vs-code-designer/src/main.ts
  pnpm-lock.yaml
Labels: pr-validated

#7767 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 922
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7764 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250710022123545 to main
  Localize/loc/tr/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7762 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250709231920728 to main
  Localize/loc/es/strings.json.lcl
  Localize/loc/ja/strings.json.lcl
  Localize/loc/pl/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7766 feat(mcp): Initial changes to serialize workflows from selected operations
  libs/designer/src/lib/core/actions/bjsworkflow/add.ts
  libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
  libs/designer/src/lib/core/mcp/utils/helper.ts
  libs/designer/src/lib/core/mcp/utils/serializer.ts
  libs/designer/src/lib/core/queries/operation.ts
  libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
  libs/designer/src/lib/core/state/operation/operationSelector.ts
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/operationmanifest.ts
Labels: pr-validated

#7763 feat(Mcp): Add initial operations panel, operations section UI, and panel state handling
  Localize/lang/strings.json
  libs/designer/src/lib/core/state/mcp/panel/mcpPanelSlice.ts
  libs/designer/src/lib/ui/mcp/connectors/SelectConnectors.tsx
  libs/designer/src/lib/ui/mcp/operations/EditOperation.tsx
  libs/designer/src/lib/ui/mcp/operations/ListOperations.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/ConnectorPanelInner.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/tabs/connectorsTab.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/tabs/operationsTab.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/usePanelTabs.tsx
  libs/designer/src/lib/ui/mcp/panel/mcpPanelRoot.tsx
  libs/designer/src/lib/ui/mcp/panel/operation/EditOperationPanelInner.tsx
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Labels: pr-validated

#7777 feat(Designer): Handoff tools are hidden from the graph
  libs/designer/src/lib/common/constants.ts
  libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
Labels: Risk:Low, pr-validated

#7779 feat(mcp): Adding connection selection UI in connections tab
  Localize/lang/strings.json
  libs/designer/src/lib/core/state/mcp/selector.ts
  libs/designer/src/lib/ui/mcp/connections/connectionselection.tsx
  libs/designer/src/lib/ui/mcp/connections/styles.ts
  libs/designer/src/lib/ui/mcp/panel/connector/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/usePanelTabs.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/connectionsPanel.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/selectConnection/connectionTable.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/selectConnection/selectConnection.tsx
Labels: pr-validated

#7780 fix(designer): Duplicate tenantID parameter on Connection Creation
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
Labels: pr-validated

#7776 feat(Mcp): Logic App Selection + empty logic app fetch support
  Localize/lang/strings.json
  apps/Standalone/src/mcp/app/McpStandard.tsx
  libs/designer/src/lib/core/mcp/utils/queries.ts
  libs/designer/src/lib/core/state/mcp/resourceSlice.ts
  libs/designer/src/lib/ui/mcp/details/logicAppSelector.tsx
  libs/designer/src/lib/ui/mcp/details/styles.ts
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/resource.ts
  libs/logic-apps-shared/src/designer-client-services/lib/resource.ts
Labels: pr-validated

#7781 feat(mcp): Adding register server handler to create workflows in mcp
  apps/Standalone/src/mcp/app/McpStandard.tsx
  libs/designer/src/lib/core/configuretemplate/utils/helper.ts
  libs/designer/src/lib/core/configuretemplate/utils/queries.ts
  libs/designer/src/lib/core/index.ts
  libs/designer/src/lib/core/mcp/utils/queries.ts
  libs/designer/src/lib/core/mcp/utils/serializer.ts
  libs/designer/src/lib/core/utils/createhelper.ts
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Labels: pr-validated

#7782 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 923
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7783 feat(mcp): Adding connection initialization with operation navigation
  Localize/lang/strings.json
  apps/Standalone/src/mcp/app/McpStandard.tsx
  apps/Standalone/src/mcp/components/DevToolbox.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/add.ts
  libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
  libs/designer/src/lib/core/actions/bjsworkflow/mcp.ts
  libs/designer/src/lib/core/state/connection/connectionSlice.ts
  libs/designer/src/lib/core/state/mcp/panel/mcpPanelSlice.ts
  libs/designer/src/lib/core/state/mcp/selector.ts
  libs/designer/src/lib/core/utils/connectors/connections.ts
  libs/designer/src/lib/ui/mcp/connections/connectionselection.tsx
  libs/designer/src/lib/ui/mcp/operations/OperationSelectionGrid.tsx
  libs/designer/src/lib/ui/mcp/operations/SelectOperations.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/tabs/operationsTab.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/usePanelTabs.tsx
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Labels: pr-validated

#7786 feat(Mcp): Main wizard page UI
  Localize/lang/strings.json
  apps/Standalone/src/mcp/app/styles.ts
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
  libs/designer/src/lib/ui/mcp/wizard/styles.ts
Labels: pr-validated

#7787 feat(designer): Hooking of Connnector Selection With Main Wizard Page
  Localize/lang/strings.json
  libs/designer/src/lib/core/state/__test__/operation/operationMetadataSlice.spec.ts
  libs/designer/src/lib/core/state/mcp/connector/connectorSlice.ts
  libs/designer/src/lib/core/state/mcp/panel/mcpPanelSlice.ts
  libs/designer/src/lib/core/state/mcp/store.ts
  libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
  libs/designer/src/lib/ui/mcp/connectors/SelectConnectors.tsx
  libs/designer/src/lib/ui/mcp/details/logicAppSelector.tsx
  libs/designer/src/lib/ui/mcp/operations/SelectOperations.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/tabs/connectionsTab.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/usePanelTabs.tsx
  libs/designer/src/lib/ui/mcp/wizard/ConnectorItem.tsx
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
  libs/designer/src/lib/ui/mcp/wizard/OperationItem.tsx
  libs/designer/src/lib/ui/mcp/wizard/styles.ts
Labels: pr-validated

#7789 fix(mcp): Fixing serialization of connections.json
  libs/designer/src/lib/core/mcp/utils/serializer.ts
Labels: pr-validated

#7790 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 924
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7588 refactor(vscode): Migrate VS Code React app from Fluent UI v8 to v9 components - Part 1
  Localize/lang/strings.json
  apps/vs-code-react/src/app/export/export.less
  apps/vs-code-react/src/app/export/export.tsx
  apps/vs-code-react/src/app/export/exportStyles.ts
  apps/vs-code-react/src/app/export/instanceSelection/instanceSelection.tsx
  apps/vs-code-react/src/app/export/navigation/navigation.tsx
  apps/vs-code-react/src/app/export/status/status.tsx
  apps/vs-code-react/src/app/export/summary/managedConnections.tsx
  apps/vs-code-react/src/app/export/summary/newResourceGroup.tsx
  apps/vs-code-react/src/app/export/summary/summary.tsx
  apps/vs-code-react/src/app/export/validation/validation.tsx
  apps/vs-code-react/src/app/export/workflowsSelection/advancedOptions.tsx
  apps/vs-code-react/src/app/export/workflowsSelection/selectedList.tsx
  apps/vs-code-react/src/app/overview/app.tsx
  apps/vs-code-react/src/app/overview/overview.less
  apps/vs-code-react/src/app/overview/overviewStyles.ts
Labels: pr-validated

#7793 feat(vscode): Update worker runtime to .NET and add func binary permissions
  apps/vs-code-designer/src/app/commands/createNewProject/createProjectSteps/ScriptProjectCreateStep.ts
  apps/vs-code-designer/src/app/commands/dataMapper/FxWorkflowRuntime.ts
  apps/vs-code-designer/src/app/utils/appSettings/localSettings.ts
  apps/vs-code-designer/src/app/utils/binaries.ts
Labels: pr-validated

#7795 fix(Mcp): Restore and update Mcp Wizard button and layout styles as per design review
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Labels: pr-validated

#7796 feat(vscode): Add telemetry tracking for VS Code designer actions
  Localize/lang/strings.json
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
  apps/vs-code-designer/src/app/utils/codeless/connection.ts
  apps/vs-code-designer/src/app/utils/unitTests.ts
Labels: pr-validated

#7799 Cherry-pick commit to fix debug select process for custom code into release
  apps/vs-code-designer/src/app/commands/createCodeful/CodefulWorkflowCreateStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppFilesStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/initLogicAppCodeProjectVScode/InitCodeProject.ts
  apps/vs-code-designer/src/app/commands/debugLogicApp.ts
  apps/vs-code-designer/src/app/commands/pickCustomCodeNetHostProcess.ts
  apps/vs-code-designer/src/app/commands/pickFuncProcess.ts
  apps/vs-code-designer/src/package.json
Labels: needs-pr-update

#7797 chore(vscode): migrate export component from LESS to makeStyles
  Localize/lang/strings.json
  apps/vs-code-react/src/app/export/export.less
  apps/vs-code-react/src/app/export/exportStyles.ts
  apps/vs-code-react/src/app/export/workflowsSelection/filters.tsx
  apps/vs-code-react/src/app/export/workflowsSelection/selectedList.tsx
  apps/vs-code-react/src/app/export/workflowsSelection/workflowsSelection.tsx
Labels: pr-validated

#7801 fix(mcp): Fixing the workflow name and operation description in definition
  libs/designer/src/lib/core/mcp/utils/helper.ts
  libs/designer/src/lib/core/mcp/utils/serializer.ts
  libs/designer/src/lib/core/state/operation/operationMetadataSlice.ts
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Labels: pr-validated

#7808 feat(Mcp): Add Close Blade Support + Revised Register Mcp Server Call
  apps/Standalone/src/mcp/app/McpStandard.tsx
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Labels: pr-validated

#7813 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250716111931964 to main
  Localize/loc/de/strings.json.lcl
  Localize/loc/fr/strings.json.lcl
  Localize/loc/nl/strings.json.lcl
  Localize/loc/ru/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7810 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250716053634506 to main
  Localize/loc/pt-BR/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7811 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 926
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7817 feat(Designer): Handoff panel tab
  Localize/lang/strings.json
  libs/designer/src/lib/common/constants.ts
  libs/designer/src/lib/core/actions/bjsworkflow/add.ts
  libs/designer/src/lib/core/actions/bjsworkflow/delete.ts
  libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
  libs/designer/src/lib/core/parsers/addNodeToWorkflow.ts
  libs/designer/src/lib/core/state/operation/operationSelector.ts
  libs/designer/src/lib/core/state/panel/panelSlice.ts
  libs/designer/src/lib/core/state/panel/panelTypes.ts
  libs/designer/src/lib/core/state/workflow/workflowInterfaces.ts
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
  libs/designer/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
  libs/designer/src/lib/ui/Designer.tsx
  libs/designer/src/lib/ui/common/DeleteModal/DeleteModal.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/handoffTab/HandoffSelector.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/handoffTab/HandoffToolEntry.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/handoffTab/handoffTab.styles.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/handoffTab/index.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/settings/sections/runafterconfiguration/runafterActionSelector.tsx
  libs/designer/src/lib/ui/settings/sections/runafterconfiguration/runafterconfiguration.less
  libs/logic-apps-shared/src/utils/src/lib/models/logicAppsV2.ts
Labels: Performance, Risk:Medium, pr-validated

#7820 refactor(vscode): replace SVG icons with Fluent UI icons in ReviewList component
  Localize/lang/strings.json
  apps/vs-code-react/src/app/components/reviewList/reviewList.tsx
  apps/vs-code-react/src/app/components/reviewList/reviewListStyles.ts
  apps/vs-code-react/src/app/export/workflowsSelection/workflowsSelection.tsx
  apps/vs-code-react/src/resources/Caution.svg
  apps/vs-code-react/src/resources/Error.svg
  apps/vs-code-react/src/resources/Success.svg
Labels: pr-validated

#7822 feat(mcp): Adding server info in create payload from connector
  apps/Standalone/src/mcp/app/McpStandard.tsx
  libs/designer/src/lib/core/index.ts
  libs/designer/src/lib/core/mcp/utils/serializer.ts
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Labels: pr-validated

#7823 fix(vscode): improve resolveConnectionsReferences to handle multiple identical references
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Utilities/Workflow.ts
  apps/vs-code-react/src/app/designer/utilities/workflow.ts
  libs/vscode-extension/src/lib/services/Workflow.ts
  libs/vscode-extension/src/lib/services/__test__/Workflow.spec.ts
Labels: Risk:Low, pr-validated

#7826 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250717021915775 to main
  Localize/loc/pl/strings.json.lcl
  Localize/loc/tr/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7828 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 927
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7821 feat(mcp): Creating Paramters Tab for MCP Operations
  Localize/lang/strings.json
  e2e/designer/editors/password.spec.ts
  libs/designer-ui/src/lib/editor/base/index.tsx
  libs/designer-ui/src/lib/searchabledropdown/__test__/__snapshots__/searchabledropdown.spec.tsx.snap
  libs/designer-ui/src/lib/searchabledropdown/__test__/searchabledropdown.spec.tsx
  libs/designer-ui/src/lib/searchabledropdown/index.tsx
  libs/designer-ui/src/lib/searchabledropdown/searchabledropdown.styles.ts
  libs/designer-ui/src/lib/searchabledropdownWithAddAll/__test__/__snapshots__/searchabledropdownWithAddAll.spec.tsx.snap
  libs/designer-ui/src/lib/searchabledropdownWithAddAll/__test__/searchabledropdownWithAddAll.spec.tsx
  libs/designer-ui/src/lib/searchabledropdownWithAddAll/index.tsx
  libs/designer-ui/src/lib/searchabledropdownWithAddAll/searchabledropdownWithAddAll.styles.ts
  libs/designer-ui/src/lib/token/inputToken.tsx
  libs/designer/src/lib/core/state/mcp/connector/connectorSlice.ts
  libs/designer/src/lib/core/state/mcp/panel/mcpPanelSlice.ts
  libs/designer/src/lib/ui/mcp/connectors/ListConnectors.tsx
  libs/designer/src/lib/ui/mcp/operations/EditOperation.tsx
  libs/designer/src/lib/ui/mcp/operations/ListOperations.tsx
  libs/designer/src/lib/ui/mcp/panel/mcpPanelRoot.tsx
  libs/designer/src/lib/ui/mcp/panel/operation/EditOperationPanelInner.tsx
  libs/designer/src/lib/ui/mcp/parameters/EditOperation.tsx
  libs/designer/src/lib/ui/mcp/parameters/styles.ts
  libs/designer/src/lib/ui/settings/settingsection.tsx
Labels: Risk:Medium, pr-validated

#7835 fix(ci): Add label change triggers to AI PR validation workflow
  .github/workflows/pr-ai-validation.yml
Labels: Risk:Low, pr-validated

#7834 chore(designer): Consolidate resolve connections references into shared library
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Utilities/Workflow.ts
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  apps/Standalone/src/templates/app/TemplatesStandard.tsx
  apps/vs-code-designer/src/app/commands/deploy/deploy.ts
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerBase.ts
  apps/vs-code-designer/src/app/utils/codeless/connection.ts
  apps/vs-code-react/src/app/designer/servicesHelper.ts
  apps/vs-code-react/src/app/designer/utilities/workflow.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/connections.spec.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/connections.ts
  libs/logic-apps-shared/src/utils/src/lib/models/logicAppsV2.ts
  libs/vscode-extension/src/lib/services/Workflow.ts
  libs/vscode-extension/src/lib/services/__test__/Workflow.spec.ts
  libs/vscode-extension/src/lib/services/index.ts
Labels: Risk:Low, pr-validated

#7832 fix(mcp): Move Edit Operation changes from local state to redux store/ restore by saving original parameters
  Localize/lang/strings.json
  libs/designer/src/lib/core/mcp/utils/hooks.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/designer/src/lib/ui/mcp/panel/operation/EditOperationPanelInner.tsx
  libs/designer/src/lib/ui/mcp/parameters/EditOperation.tsx
Labels: Risk:Medium, pr-validated

#7838 fix(designer): A2A run-after + deletion logic fix
  __mocks__/workflows/BasicA2A.json
  __mocks__/workflows/LoopTest.json
  apps/Standalone/src/designer/app/LocalDesigner/LogicAppSelector/LogicAppSelector.tsx
  libs/designer/src/lib/ui/common/DesignerContextualMenu/DesignerContextualMenu.tsx
  libs/designer/src/lib/ui/menuItems/deleteMenuItem.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
  libs/designer/src/lib/ui/settings/sections/runafter.tsx
  libs/designer/src/lib/ui/settings/sections/runafterconfiguration/runafterActionSelector.tsx
Labels: Risk:Low, pr-validated

#7846 test(designer): Adding test to fetching next page on dynamic data
  libs/logic-apps-shared/src/designer-client-services/lib/base/__test__/connector.spec.ts
Labels: Risk:Low, pr-validated

#7850 fix(vscode): Fix workflow dirty state management after saving parameters
  Localize/lang/strings.json
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
  apps/vs-code-react/src/run-service/types.ts
  apps/vs-code-react/src/webviewCommunication.tsx
  libs/vscode-extension/src/lib/models/extensioncommand.ts
Labels: Risk:Low, pr-validated

#7849 fix(vscode): Extension startup optimizations
  apps/vs-code-designer/src/app/commands/__test__/parameterizeConnections.test.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ConvertToWorkspace.ts
  apps/vs-code-designer/src/app/commands/parameterizeConnections.ts
  apps/vs-code-designer/src/app/utils/binaries.ts
  apps/vs-code-designer/src/app/utils/bundleFeed.ts
  apps/vs-code-designer/src/main.ts
Labels: Performance, Risk:Medium, pr-validated

#7855 Removed codeful step for v5.130 release
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/NewCodeProjectTypeStep.ts
Labels: Risk:Low, pr-validated

#7860 fix(designer): Remove limit count setting for agent loop actions inside agent workflows
  Localize/lang/strings.json
  libs/designer/src/lib/core/actions/bjsworkflow/settings.ts
Labels: Risk:Low, pr-validated

#7863 feat(mcp): Add dynamic combobox and file picker editors for parameter values in designer UI
  libs/designer/src/lib/core/state/selectors/actionMetadataSelector.ts
  libs/designer/src/lib/ui/mcp/connections/connectionselection.tsx
  libs/designer/src/lib/ui/mcp/parameters/EditOperation.tsx
  libs/designer/src/lib/ui/mcp/parameters/ParameterEditor.tsx
Labels: Risk:Low, pr-validated

#7861 feat(designer): improve handoff agent UX with better labeling and auto-panel navigation
  Localize/lang/strings.json
  libs/designer/src/lib/core/actions/bjsworkflow/add.ts
  libs/designer/src/lib/core/actions/bjsworkflow/handoff.ts
  libs/designer/src/lib/ui/common/EdgeContextualMenu/EdgeContextualMenu.tsx
Labels: Risk:Low, pr-validated

#7778 feat(designer): Move Agent Service dropdown under Connections
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionInternal.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionWrapper.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/openAIConnector.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/formInputs/universalConnectionParameter.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/connectionInline.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentLoopConnector.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
  libs/logic-apps-shared/src/utils/src/lib/models/connector.ts
Labels: Risk:Medium, pr-validated

#7870 feat(Mcp): Add different editor support for parameters in Mcp
  libs/designer-ui/src/lib/arrayeditor/collapsedarray.tsx
  libs/designer-ui/src/lib/arrayeditor/expandedcomplexarray.tsx
  libs/designer-ui/src/lib/arrayeditor/expandedsimplearray.tsx
  libs/designer-ui/src/lib/arrayeditor/index.tsx
  libs/designer-ui/src/lib/dictionary/index.tsx
  libs/designer/src/lib/ui/mcp/parameters/ParameterEditor.tsx
Labels: Risk:Medium, pr-validated

#7873 fix(designer): Add runtime properties for Dynamic Connections
  Localize/lang/strings.json
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnectionInternal.tsx
  libs/logic-apps-shared/src/utils/src/lib/models/connection.ts
Labels: Risk:Medium, pr-validated

#7875 fix(designer): Remove default action count
  libs/designer/src/lib/ui/settings/sections/general.tsx
Labels: Risk:Low, pr-validated

#7871 feat(designer): Enable className styling on parameter editors on outer-most component
  libs/designer-ui/src/lib/arrayeditor/index.tsx
  libs/designer-ui/src/lib/authentication/index.tsx
  libs/designer-ui/src/lib/combobox/index.tsx
  libs/designer-ui/src/lib/dictionary/index.tsx
  libs/designer-ui/src/lib/dropdown/index.tsx
  libs/designer-ui/src/lib/html/index.tsx
  libs/designer-ui/src/lib/picker/filepickerEditor.tsx
  libs/designer-ui/src/lib/schemaeditor/index.tsx
  libs/designer-ui/src/lib/searchabledropdownWithAddAll/__test__/__snapshots__/searchabledropdownWithAddAll.spec.tsx.snap
  libs/designer-ui/src/lib/searchabledropdownWithAddAll/searchabledropdownWithAddAll.styles.ts
  libs/designer-ui/src/lib/table/index.tsx
  libs/designer/src/lib/ui/mcp/parameters/EditOperation.tsx
  libs/designer/src/lib/ui/mcp/parameters/ParameterEditor.tsx
  libs/designer/src/lib/ui/mcp/parameters/styles.ts
Labels: Risk:Medium, pr-validated

#7807 feat(designer): implement chat history and timeline enhancements for A2A agent workflows
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/DesignerCommandBar.tsx
  apps/vs-code-react/src/app/designer/app.tsx
  libs/designer-ui/src/lib/chatbot/chatbot.less
  libs/designer-ui/src/lib/chatbot/components/toolReply.tsx
  libs/designer-ui/src/lib/monitoring/statuspill/images/index.tsx
  libs/designer/src/lib/core/queries/runs.ts
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
  libs/designer/src/lib/ui/MonitoringTimeline/TimelineContent.tsx
  libs/designer/src/lib/ui/MonitoringTimeline/TimelineNode.tsx
  libs/designer/src/lib/ui/MonitoringTimeline/__tests__/helpers.test.ts
  libs/designer/src/lib/ui/MonitoringTimeline/helpers.ts
  libs/designer/src/lib/ui/MonitoringTimeline/hooks.ts
  libs/designer/src/lib/ui/MonitoringTimeline/index.tsx
  libs/designer/src/lib/ui/connections/runAfterIndicator/styles.less
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
  libs/designer/src/lib/ui/panel/agentChat/helper.ts
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
  libs/logic-apps-shared/src/utils/src/lib/models/operationmanifest.ts
Labels: Risk:Medium, pr-validated

#7854 fix(designer): Center graph on remount
  libs/designer/src/lib/ui/DesignerReactFlow.tsx
  libs/designer/src/lib/ui/common/DragPanMonitor/DragPanMonitor.tsx
Labels: Risk:Low, pr-validated

#7877 fix(standalone): Race condition causing fetching childworkflows in parallel to miss flows
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/ChildWorkflow.ts
Labels: Risk:Low, pr-validated

#7881 fix(designer): Fix localization in ACA Session Connector
  Localize/lang/strings.json
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/custom/acasessionConnector.tsx
Labels: Risk:Low, pr-validated

#7882 fix(designer): When creating agent tool to properly set the right active node
  libs/designer/src/lib/core/actions/bjsworkflow/add.ts
Labels: Risk:Low, pr-validated

#7885 fix(designer): Update agent chat header and text
  Localize/lang/strings.json
  libs/designer/src/lib/ui/panel/agentChat/agentChat.tsx
Labels: Risk:Low, pr-validated

#7888 feat(Mcp): Support search filtering and sorting for operations selection
  Localize/lang/strings.json
  libs/designer/src/lib/ui/mcp/connectors/SelectConnectors.tsx
  libs/designer/src/lib/ui/mcp/connectors/styles.ts
  libs/designer/src/lib/ui/mcp/operations/OperationSelectionGrid.tsx
  libs/designer/src/lib/ui/mcp/operations/SelectOperations.tsx
  libs/designer/src/lib/ui/mcp/operations/styles.ts
Labels: Risk:Low, pr-validated

#7891 fix(designer/mcp): Fixing Browse not picking up all connectors
  libs/designer/src/lib/ui/mcp/connectors/ConnectorBrowseView.tsx
  libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
Labels: Risk:Low, pr-validated

#7898 feat(standalone): Custom code adding powershell AppSetting + save in parallel
  __mocks__/workflows/BasicA2A.json
  __mocks__/workflows/NewA2A.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
Labels: Risk:Low, pr-validated

#7900 fix(mcp): Fixing serialization with transforming the swagger schema and dynamic inputs null ref fix
  libs/designer-ui/src/lib/editor/models/parameter.ts
  libs/designer/src/lib/core/actions/bjsworkflow/add.ts
  libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
  libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
  libs/designer/src/lib/core/mcp/utils/hooks.ts
  libs/designer/src/lib/core/mcp/utils/serializer.ts
  libs/designer/src/lib/core/state/mcp/store.ts
  libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/designer/src/lib/ui/mcp/connectors/ListConnectors.tsx
  libs/designer/src/lib/ui/mcp/operations/ListOperations.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/usePanelTabs.tsx
  libs/designer/src/lib/ui/mcp/panel/operation/EditOperationPanel.tsx
  libs/designer/src/lib/ui/mcp/parameters/EditOperation.tsx
  libs/designer/src/lib/ui/mcp/parameters/ParameterEditor.tsx
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Labels: Risk:Medium, pr-validated

#7905 fix(designer): prevent agent operations from displaying trigger info
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
Labels: Risk:Low, pr-validated

#7883 fix(Mcp): Panel showing previous instead of close without previous tab
  libs/designer/src/lib/core/state/mcp/mcpselectionslice.ts
  libs/designer/src/lib/core/state/mcp/store.ts
  libs/designer/src/lib/ui/mcp/connectors/ListConnectors.tsx
  libs/designer/src/lib/ui/mcp/connectors/SelectConnectors.tsx
  libs/designer/src/lib/ui/mcp/operations/ListOperations.tsx
  libs/designer/src/lib/ui/mcp/operations/SelectOperations.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/SelectionPanel.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/tabs/connectorsTab.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/tabs/operationsTab.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/usePanelTabs.tsx
  libs/designer/src/lib/ui/mcp/panel/operation/EditOperationPanel.tsx
  libs/designer/src/lib/ui/mcp/parameters/EditOperation.tsx
Labels: Risk:Low, pr-validated

#7909 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250730022337357 to main
  Localize/loc/cs/strings.json.lcl
  Localize/loc/de/strings.json.lcl
  Localize/loc/es/strings.json.lcl
  Localize/loc/fr/strings.json.lcl
  Localize/loc/hu/strings.json.lcl
  Localize/loc/id/strings.json.lcl
  Localize/loc/it/strings.json.lcl
  Localize/loc/ja/strings.json.lcl
  Localize/loc/ko/strings.json.lcl
  Localize/loc/nl/strings.json.lcl
  Localize/loc/pl/strings.json.lcl
  Localize/loc/pt-BR/strings.json.lcl
  Localize/loc/pt-PT/strings.json.lcl
  Localize/loc/ru/strings.json.lcl
  Localize/loc/sv/strings.json.lcl
  Localize/loc/tr/strings.json.lcl
  Localize/loc/zh-Hans/strings.json.lcl
  Localize/loc/zh-Hant/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7915 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250730141906626 to main
  Localize/loc/de/strings.json.lcl
  Localize/loc/es/strings.json.lcl
  Localize/loc/ja/strings.json.lcl
  Localize/loc/pt-PT/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7916 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250730172124270 to main
  Localize/loc/fr/strings.json.lcl
  Localize/loc/it/strings.json.lcl
  Localize/loc/ko/strings.json.lcl
  Localize/loc/sv/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7918 fix(a2a): comprehensive icon improvements for A2A and agent triggers
  libs/logic-apps-shared/src/designer-client-services/lib/base/manifests/a2arequest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/operations/agent.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
Labels: Risk:Low, pr-validated

#7921 feat(Designer): Agent handoff message input
  libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
  libs/designer/src/lib/core/utils/graph.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/handoffTab/HandoffToolEntry.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/handoff.ts
Labels: Risk:Low, pr-validated

#7924 fix(mcp): Revisions on wizard and parameters panel with forward link updates.
  Localize/lang/strings.json
  libs/designer/src/lib/common/images/mcp/addconnector.svg
  libs/designer/src/lib/ui/mcp/connectors/ListConnectors.tsx
  libs/designer/src/lib/ui/mcp/parameters/EditOperation.tsx
  libs/designer/src/lib/ui/mcp/parameters/styles.ts
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Labels: Risk:Low, pr-validated

#7908 Data Mapper: Fixed auto-layout to trigger and lay out action nodes when metadata is not found
  apps/Standalone/src/dataMapperV1/mapDefinitions/FullTranscriptMapDefinition.ts
  apps/vs-code-designer/src/constants.ts
  apps/vs-code-designer/src/package.json
  libs/data-mapper-v2/src/components/canvas/ReactFlow.tsx
  libs/data-mapper-v2/src/core/state/DataMapSlice.ts
  libs/data-mapper-v2/src/ui/hooks/useAutoLayout.ts
  libs/data-mapper-v2/src/utils/Metadata.utils.ts
Labels: Risk:Medium, pr-validated

#7927 ci(vscode): Azure DevOps environment name to VSCodeDeployLAUX
  .azure-pipelines/1esmain.yml
  .azure-pipelines/release.yml
Labels: Risk:Low, pr-validated

#7928 feat(Designer): Added `x-ms-is-node-id` input parameter property
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/handoff.ts
Labels: Risk:Low, pr-validated

#7934 fix(pipeline): Add missing closing quote in stage-artifacts template
  .azure-pipelines/templates/stage-artifacts.yml
Labels: Risk:Low, pr-validated
