Repository Azure/LogicAppsUX, pull requests merged in 2025-08, with the labels that each got.

#7939 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250801111917547 to main
  Localize/loc/cs/strings.json.lcl
  Localize/loc/ja/strings.json.lcl
  Localize/loc/ko/strings.json.lcl
  Localize/loc/pt-PT/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7937 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 938
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7940 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250801142408574 to main
  Localize/loc/id/strings.json.lcl
  Localize/loc/ru/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7935 feat(mcp): Adding support for dynamic schema operations in parameters panel
  Localize/lang/strings.json
  libs/designer/src/lib/core/actions/bjsworkflow/mcp.ts
  libs/designer/src/lib/core/mcp/utils/helper.ts
  libs/designer/src/lib/core/utils/outputs.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/designer/src/lib/ui/mcp/operations/ListOperations.tsx
  libs/designer/src/lib/ui/mcp/operations/operationprogress.tsx
  libs/designer/src/lib/ui/mcp/operations/styles.ts
  libs/designer/src/lib/ui/mcp/panel/connector/usePanelTabs.tsx
  libs/designer/src/lib/ui/mcp/panel/operation/EditOperationPanel.tsx
  libs/designer/src/lib/ui/mcp/parameters/EditOperation.tsx
  libs/designer/src/lib/ui/mcp/parameters/parameterfield.tsx
  libs/designer/src/lib/ui/mcp/parameters/styles.ts
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Labels: Risk:Medium, pr-validated

#7930 feat(vscode): Complete Fluent UI v8 to v9 migration for VS Code export workflows
  LESS_FILES_MIGRATION_ANALYSIS.md
  LESS_TO_MAKESTYLES_MIGRATION_PLAN.md
  MIGRATION_DEPENDENCY_GRAPH.md
  apps/vs-code-react/src/app/components/reviewList/helper.ts
  apps/vs-code-react/src/app/components/searchableDropdown/index.tsx
  apps/vs-code-react/src/app/export/exportStyles.ts
  apps/vs-code-react/src/app/export/instanceSelection/instanceSelection.tsx
  apps/vs-code-react/src/app/export/status/status.tsx
  apps/vs-code-react/src/app/export/summary/helper.ts
  apps/vs-code-react/src/app/export/summary/managedConnections.tsx
  apps/vs-code-react/src/app/export/summary/newResourceGroup.tsx
  apps/vs-code-react/src/app/export/summary/summary.tsx
  apps/vs-code-react/src/app/export/workflowsSelection/advancedOptions.tsx
  apps/vs-code-react/src/app/export/workflowsSelection/filters.tsx
  apps/vs-code-react/src/app/export/workflowsSelection/helper.ts
  apps/vs-code-react/src/app/export/workflowsSelection/workflowsSelection.tsx
  apps/vs-code-react/src/index.html
  apps/vs-code-react/src/styles.less
  apps/vs-code-react/test-setup.ts
Labels: Risk:Medium, pr-validated

#7946 feat(mcp): Searchable Logic App Selector
  Localize/lang/strings.json
  libs/designer/src/lib/ui/mcp/details/logicAppSelector.tsx
  libs/designer/src/lib/ui/mcp/details/styles.ts
Labels: Risk:Low, pr-validated

#7943 feat(ci): add version management and telemetry steps to Azure DevOps package template
  .azure-pipelines/templates/package.yml
  .github/workflows/private-vsix-build.yml
  scripts/README.md
  scripts/calculate-next-version.ts
  scripts/get-current-version.ts
  scripts/update-versions.js
  scripts/version-utils.ts
Labels: Risk:Low, pr-validated

#7947 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250801210211804 to main
  Localize/loc/de/strings.json.lcl
  Localize/loc/fr/strings.json.lcl
  Localize/loc/nl/strings.json.lcl
  Localize/loc/pl/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7948 feat(designer): improve handoff naming with unique GUIDs
  libs/designer/src/lib/core/actions/bjsworkflow/handoff.ts
  libs/designer/src/lib/ui/connections/handoffEdge.tsx
  libs/logic-apps-shared/src/utils/src/lib/helpers/__test__/guid.spec.ts
Labels: Risk:Low, pr-validated

#7944 feat(mcp): Error handling in connections,operations and connections
  Localize/lang/strings.json
  libs/designer-ui/src/lib/mcp/model.ts
  libs/designer/src/lib/core/actions/bjsworkflow/mcp.ts
  libs/designer/src/lib/core/mcp/utils/helper.ts
  libs/designer/src/lib/core/state/mcp/mcpselectionslice.ts
  libs/designer/src/lib/ui/configuretemplate/common.tsx
  libs/designer/src/lib/ui/mcp/connectors/ListConnectors.tsx
  libs/designer/src/lib/ui/mcp/operations/OperationSelectionGrid.tsx
  libs/designer/src/lib/ui/mcp/operations/SelectOperations.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/tabs/operationsTab.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/usePanelTabs.tsx
Labels: Risk:Medium, pr-validated

#7955 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 939
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7953 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250802022510143 to main
  Localize/loc/sv/strings.json.lcl
  Localize/loc/tr/strings.json.lcl
Labels: pr-validated, auto-localization-update

#7952 fix(mcp): Revert Max Width of Logic App Selector
  libs/designer/src/lib/ui/mcp/details/styles.ts
Labels: Risk:Low, pr-validated

#7958 fix(ci): update replace-in-file command syntax in Azure pipeline
  .azure-pipelines/templates/package.yml
Labels: Risk:Low, pr-validated

#7961 fix(ci): update Azure pipeline script to use PowerShell for cross-platform JSON manipulation
  .azure-pipelines/templates/package.yml
Labels: Risk:Low, pr-validated

#7959 feat(Mcp): Redesign of parameters and dynamic parameter badge
  Localize/lang/strings.json
  libs/designer/src/lib/ui/mcp/connectors/ListConnectors.tsx
  libs/designer/src/lib/ui/mcp/panel/operation/EditOperationPanel.tsx
  libs/designer/src/lib/ui/mcp/parameters/EditOperation.tsx
  libs/designer/src/lib/ui/mcp/parameters/parameterfield.tsx
  libs/designer/src/lib/ui/mcp/parameters/styles.ts
  libs/designer/src/lib/ui/mcp/wizard/styles.ts
Labels: Risk:Medium, pr-validated

#7962 fix(designer): Hide Agent Instructions for A2A Workflows
  __mocks__/workflows/BasicA2A.json
  libs/designer-ui/src/lib/agentinstruction/index.tsx
  libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
  libs/designer/src/lib/common/constants.ts
  libs/designer/src/lib/ui/mcp/details/logicAppSelector.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
  libs/designer/src/lib/ui/panel/recommendation/browseView.tsx
Labels: Risk:Low, pr-validated

#7972 fix(designer): handle string error messages and prevent 'in' operator TypeError
  libs/designer/src/lib/common/utilities/__test__/error.test.ts
  libs/designer/src/lib/common/utilities/error.ts
Labels: Risk:Low, pr-validated

#7975 feat(Designer): Flow structure errors + node disconnect checks
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/LocalDesigner/pseudoCommandBar.tsx
  libs/designer/src/lib/core/state/workflow/workflowInterfaces.ts
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
  libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
  libs/designer/src/lib/ui/CustomNodes/ScopeCardNode.tsx
  libs/designer/src/lib/ui/DesignerReactFlow.tsx
  libs/designer/src/lib/ui/panel/errorsPanel/tabs/errorsTab.hooks.ts
  libs/designer/src/lib/ui/panel/errorsPanel/tabs/errorsTab.tsx
  libs/designer/src/lib/ui/panel/index.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/handoffTab/index.tsx
  libs/designer/src/lib/ui/settings/sections/runafter.tsx
  libs/designer/src/lib/ui/settings/sections/runafterconfiguration/runafterActionSelector.tsx
Labels: Risk:Medium, pr-validated

#7981 fix(mcp): Removing optional parameters as strict dynamic parameters dependencies
  Localize/lang/strings.json
  libs/designer/src/lib/core/actions/bjsworkflow/mcp.ts
  libs/designer/src/lib/core/mcp/utils/helper.ts
  libs/designer/src/lib/core/state/mcp/mcpOptions/mcpOptionsSlice.ts
  libs/designer/src/lib/core/utils/parameters/dynamicdata.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/designer/src/lib/core/utils/swagger/operation.ts
  libs/designer/src/lib/ui/mcp/panel/operation/EditOperationPanel.tsx
  libs/designer/src/lib/ui/mcp/parameters/EditOperation.tsx
  libs/designer/src/lib/ui/mcp/parameters/parameterfield.tsx
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Labels: Risk:Medium, pr-validated

#7983 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 941
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#7985 fix(vscode): resolve file system connection callback and improve type safety
  Localize/lang/strings.json
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
  apps/vs-code-react/src/run-service/types.ts
  apps/vs-code-react/src/state/DesignerSlice.ts
  libs/vscode-extension/src/lib/models/workflow.ts
Labels: Risk:Low, pr-validated

#7971 chore(designer): Update Lexical and enable spellcheck in HTML/Agent Instruction Editors
  Localize/lang/strings.json
  libs/designer-ui/package.json
  libs/designer-ui/src/lib/agentinstruction/index.tsx
  libs/designer-ui/src/lib/combobox/combobox.less
  libs/designer-ui/src/lib/editor/base/index.tsx
  libs/designer-ui/src/lib/editor/base/nodes/extendedTextNode.tsx
  libs/designer-ui/src/lib/editor/base/plugins/PasswordMaskPlugin.tsx
  libs/designer-ui/src/lib/editor/base/plugins/TokenTypeahead.tsx
  libs/designer-ui/src/lib/editor/base/utils/initialConfig.ts
  libs/designer-ui/src/lib/flyout/__test__/__snapshots__/flyout.spec.tsx.snap
  libs/designer-ui/src/lib/flyout2/__test__/__snapshots__/flyout2.spec.tsx.snap
  libs/designer-ui/src/lib/html/index.tsx
  libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheadercomment.spec.tsx.snap
  libs/designer-ui/src/lib/panel/panelheader/__test__/__snapshots__/panelheadertitle.spec.tsx.snap
  libs/designer-ui/src/lib/querybuilder/__test__/Group.spec.tsx
  libs/designer-ui/src/lib/querybuilder/__test__/HybridQueryBuilder.spec.tsx
  libs/designer-ui/src/lib/querybuilder/__test__/QueryBuilderEditor.spec.tsx
  libs/designer-ui/src/lib/querybuilder/__test__/integration.spec.tsx
  libs/designer/src/lib/core/utils/middleware.ts
  package.json
  pnpm-lock.yaml
Labels: Risk:Low, pr-validated

#7987 fix(vscode): resolve file system connection callback and improve type safety
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
  apps/vs-code-react/src/run-service/types.ts
  apps/vs-code-react/src/state/DesignerSlice.ts
  libs/vscode-extension/src/lib/models/workflow.ts
Labels: Risk:Low, pr-validated

#7980 fix(Mcp): Replace and sanitize names of workflows to be created to match format
  apps/Standalone/src/mcp/app/McpStandard.tsx
  libs/designer/src/lib/core/mcp/utils/__test__/serializer.spec.ts
  libs/designer/src/lib/core/mcp/utils/serializer.ts
Labels: Risk:Low, pr-validated

#7990 fix(designer): Enable channel tab by default and add a disable flag instead
  libs/designer/src/lib/common/hooks/experimentation.ts
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/experimentationFlags.ts
Labels: Risk:Low, pr-validated

#7978 Data Mapper- Add notification for V1 users: transition prompt and quick-action to V2 platform
  Localize/lang/strings.json
  apps/vs-code-designer/src/app/commands/dataMapper/DataMapperPanel.ts
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/commands/setDataMapperVersion.ts
  apps/vs-code-designer/src/constants.ts
  apps/vs-code-designer/src/package.json
  apps/vs-code-react/src/app/dataMapper/appV1.tsx
  libs/data-mapper/src/lib/components/deprecationToast/DeprecationToast.tsx
  libs/data-mapper/src/lib/components/deprecationToast/DeprecationToastContent.tsx
  libs/data-mapper/src/lib/components/deprecationToast/index.ts
  libs/data-mapper/src/lib/ui/DataMapperDesigner.tsx
  libs/designer-ui/src/lib/querybuilder/__test__/Group.spec.tsx
  libs/designer-ui/src/lib/querybuilder/__test__/integration.spec.tsx
  libs/vscode-extension/src/lib/models/dataMapper.ts
  libs/vscode-extension/src/lib/models/extensioncommand.ts
Labels: Risk:Low, pr-validated

#7960 Data Mapper v2 GA: Add deprecation toast, update schema mocks to TS, fix deserializer tests, and improve auto-layout
  Localize/lang/strings.json
  apps/Standalone/src/dataMapperV1/mapDefinitions/FullTranscriptMapDefinition.ts
  apps/vs-code-designer/src/app/commands/dataMapper/DataMapperPanel.ts
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/commands/setDataMapperVersion.ts
  apps/vs-code-designer/src/constants.ts
  apps/vs-code-designer/src/package.json
  apps/vs-code-react/src/app/dataMapper/appV1.tsx
  libs/data-mapper-v2/src/__mocks__/schemas/ComprehensiveSourceSchema.json
  libs/data-mapper-v2/src/__mocks__/schemas/ComprehensiveSourceSchema.ts
  libs/data-mapper-v2/src/__mocks__/schemas/ComprehensiveTargetSchema.ts
  libs/data-mapper-v2/src/__mocks__/schemas/DeepNestedSequenceAndObj.json
  libs/data-mapper-v2/src/__mocks__/schemas/DeepNestedSequenceAndObjXsd.ts
  libs/data-mapper-v2/src/__mocks__/schemas/SourceSchema.json
  libs/data-mapper-v2/src/__mocks__/schemas/SourceSchemaJson.ts
  libs/data-mapper-v2/src/__mocks__/schemas/SourceSchemaXsd.ts
  libs/data-mapper-v2/src/__mocks__/schemas/TargetSchema.json
  libs/data-mapper-v2/src/__mocks__/schemas/TargetSchemaJson.json
  libs/data-mapper-v2/src/__mocks__/schemas/TargetSchemaJson.ts
  libs/data-mapper-v2/src/__mocks__/schemas/TargetSchemaXsd.ts
  libs/data-mapper-v2/src/__mocks__/schemas/index.ts
  libs/data-mapper-v2/src/components/canvas/ReactFlow.tsx
  libs/data-mapper-v2/src/core/state/DataMapSlice.ts
  libs/data-mapper-v2/src/mapHandling/__test__/MapDefinitionDeserializer.spec.ts
  libs/data-mapper-v2/src/mapHandling/__test__/MapHandlingTestUtilis.ts
  libs/data-mapper-v2/src/ui/hooks/useAutoLayout.ts
  libs/data-mapper-v2/src/utils/Metadata.utils.ts
  libs/data-mapper/src/lib/components/deprecationToast/DeprecationToast.tsx
  libs/data-mapper/src/lib/components/deprecationToast/DeprecationToastContent.tsx
  libs/data-mapper/src/lib/components/deprecationToast/index.ts
  libs/data-mapper/src/lib/ui/DataMapperDesigner.tsx
  libs/vscode-extension/src/lib/models/dataMapper.ts
  libs/vscode-extension/src/lib/models/extensioncommand.ts
Labels: Risk:High, needs-pr-update

#7979 chore(Mcp): Adding telemetry for user journey
  libs/data-mapper/src/lib/components/deprecationToast/DeprecationToastContent.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/mcp.ts
  libs/designer/src/lib/core/mcp/utils/helper.ts
  libs/designer/src/lib/core/mcp/utils/hooks.ts
  libs/designer/src/lib/core/mcp/utils/serializer.ts
  libs/designer/src/lib/core/state/connection/connectionSlice.ts
  libs/designer/src/lib/ui/mcp/connectors/SelectConnectors.tsx
  libs/designer/src/lib/ui/mcp/operations/ListOperations.tsx
  libs/designer/src/lib/ui/mcp/panel/connector/usePanelTabs.tsx
  libs/designer/src/lib/ui/mcp/panel/operation/EditOperationPanel.tsx
  libs/designer/src/lib/ui/mcp/wizard/McpWizard.tsx
Labels: Risk:Low, pr-validated

#8006 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 942
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#8005 fix(mcp): Disable save and show handling for dynamic inputs errors in parameter panel
  Localize/lang/strings.json
  libs/designer/src/lib/core/state/mcp/mcpselectionslice.ts
  libs/designer/src/lib/core/state/operation/operationSelector.ts
  libs/designer/src/lib/core/utils/parameters/helper.ts
  libs/designer/src/lib/ui/mcp/panel/operation/EditOperationPanel.tsx
  libs/designer/src/lib/ui/mcp/parameters/EditOperation.tsx
Labels: Risk:Low, pr-validated

#7992 fix(designer): Move setValue calls out of render in UniversalConnectionParameter to prevent re-renders
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/formInputs/universalConnectionParameter.tsx
Labels: Risk:Low, pr-validated

#8022 fix(Mcp): Bug bash fixes + telemetry clean up
  apps/Standalone/src/mcp/app/McpStandard.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/mcp.ts
  libs/designer/src/lib/ui/mcp/operations/ListOperations.tsx
  libs/designer/src/lib/ui/mcp/panel/operation/EditOperationPanel.tsx
  libs/designer/src/lib/ui/mcp/wizard/styles.ts
Labels: Risk:Low, pr-validated

#8025 Localized file check-in by OneLocBuild Task: Build definition ID 4: Build ID 943
  Localize/lang/strings.cs.json
  Localize/lang/strings.de.json
  Localize/lang/strings.es.json
  Localize/lang/strings.fr.json
  Localize/lang/strings.hu.json
  Localize/lang/strings.id.json
  Localize/lang/strings.it.json
  Localize/lang/strings.ja.json
  Localize/lang/strings.ko.json
  Localize/lang/strings.nl.json
  Localize/lang/strings.pl.json
  Localize/lang/strings.pt-BR.json
  Localize/lang/strings.pt-PT.json
  Localize/lang/strings.ru.json
  Localize/lang/strings.sv.json
  Localize/lang/strings.tr.json
  Localize/lang/strings.zh-Hans.json
  Localize/lang/strings.zh-Hant.json
Labels: pr-validated

#8029 refactor(ci): simplify version handling in package template
  .azure-pipelines/1esmain.yml
  .azure-pipelines/templates/package.yml
Labels: Risk:Low, pr-validated

#8032 refactor(designer): clear run data only from agent nodes and subgraphs
  libs/designer/src/lib/core/state/workflow/helper.ts
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
Labels: Risk:Low, pr-validated

#8033 fix(designer): Add Agent loop in Stateful behind FF
  libs/designer/src/lib/core/state/designerView/designerViewSelectors.ts
  libs/designer/src/lib/ui/Designer.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/experimentationFlags.ts
Labels: Risk:Low, pr-validated

#8015 fix(designer): Update combobox performance thresholds and fix search completeness
  libs/designer-ui/src/lib/combobox/__test__/combobox.spec.tsx
  libs/designer-ui/src/lib/combobox/index.tsx
Labels: Risk:Low, pr-validated

#8048 fix(Designer): Fixed handoff description dirty state issue
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/handoffTab/HandoffToolEntry.tsx
Labels: Risk:Low, pr-validated

#8052 feat(pipeline): Add VS Code extension staging step and set dryRun default
  .azure-pipelines/release.yml
  .azure-pipelines/templates/stage-artifacts.yml
Labels: Risk:Low, pr-validated

#8053 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250813021911252 to main
  Localize/loc/cs/strings.json.lcl
  Localize/loc/de/strings.json.lcl
  Localize/loc/es/strings.json.lcl
  Localize/loc/fr/strings.json.lcl
  Localize/loc/hu/strings.json.lcl
  Localize/loc/id/strings.json.lcl
  Localize/loc/it/strings.json.lcl
  Localize/loc/ja/strings.json.lcl
  Localize/loc/ko/strings.json.lcl
  Localize/loc/nl/strings.json.lcl
  Localize/loc/pl/strings.json.lcl
  Localize/loc/pt-BR/strings.json.lcl
  Localize/loc/pt-PT/strings.json.lcl
  Localize/loc/ru/strings.json.lcl
  Localize/loc/sv/strings.json.lcl
  Localize/loc/tr/strings.json.lcl
  Localize/loc/zh-Hans/strings.json.lcl
  Localize/loc/zh-Hant/strings.json.lcl
Labels: pr-validated, auto-localization-update

#8061 feat(Designer): Added handoff edge menu
  Localize/lang/strings.json
  libs/designer/src/lib/core/state/designerView/designerViewInterfaces.ts
  libs/designer/src/lib/ui/DesignerReactFlow.tsx
  libs/designer/src/lib/ui/common/EdgeContextualMenu/EdgeContextualMenu.tsx
  libs/designer/src/lib/ui/connections/edge.tsx
  libs/designer/src/lib/ui/connections/edgePathContextMenu.tsx
  libs/designer/src/lib/ui/connections/handoffEdge.tsx
Labels: Risk:Low, pr-validated

#8063 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250813231940304 to main
  Localize/loc/fr/strings.json.lcl
  Localize/loc/id/strings.json.lcl
  Localize/loc/it/strings.json.lcl
Labels: pr-validated, auto-localization-update

#8066 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250814021934565 to main
  Localize/loc/hu/strings.json.lcl
  Localize/loc/nl/strings.json.lcl
  Localize/loc/sv/strings.json.lcl
Labels: pr-validated, auto-localization-update

#8067 LEGO: Pull request from users/loc/juno/hb_e8128129-2d33-4a21-9e80-44e341aa730f_20250814051925835 to main
  Localize/loc/pl/strings.json.lcl
  Localize/loc/zh-Hant/strings.json.lcl
Labels: pr-validated, auto-localization-update

#8062 feat(designer): Add support for A2A Trigger Parameters and migrates the Copyable Editor to Fluent v9
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Models/Workflow.ts
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesigner.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerConsumption.tsx
  libs/designer-ui/src/lib/copyinputcontrol/AgentUrlViewer.tsx
  libs/designer-ui/src/lib/copyinputcontrol/CopyInputControlWithAgent.tsx
  libs/designer-ui/src/lib/copyinputcontrol/__test__/__snapshots__/copyinputcontrol.spec.tsx.snap
  libs/designer-ui/src/lib/copyinputcontrol/__test__/copyinputcontrol.spec.tsx
  libs/designer-ui/src/lib/copyinputcontrol/index.tsx
  libs/designer-ui/src/lib/copyinputcontrol/styles.ts
  libs/designer-ui/src/lib/editor/base/plugins/FloatingLinkEditor.tsx
  libs/designer-ui/src/lib/editor/monaco/index.tsx
  libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
  libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
  libs/designer/src/lib/ui/panel/recommendation/azureResourceSelection.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/manifests/a2arequest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/manifests/request.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/operations/request.ts
  libs/logic-apps-shared/src/designer-client-services/lib/workflow.ts
  libs/logic-apps-shared/src/utils/src/lib/models/a2a.ts
  libs/logic-apps-shared/src/utils/src/lib/models/index.ts
Labels: Risk:Medium, pr-validated

#8071 fix(Designer): File Picker not serializing after selecting item
  libs/designer-ui/src/lib/picker/filepickerEditor.tsx
Labels: Risk:Low, pr-validated

#8079 chore(Designer): Adding telemetry for grantType allowedValues length not one
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
Labels: Risk:Low, pr-validated

#8080 chore(Designer): [v5.157] Adding telemetry for grantType allowedValues length not one
  libs/designer/src/lib/ui/panel/connectionsPanel/createConnection/createConnection.tsx
Labels: Risk:Medium, pr-validated

#8065 feat(designer): Add trimByteOrderMark template function
  Localize/lang/strings.json
  libs/designer-ui/src/lib/workflow/languageservice/templatefunctions.ts
Labels: Risk:Low, pr-validated

#8085 fix(vscode): revert validate API call due to issues with pending validate partial implementation
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
Labels: Risk:Low, pr-validated

#8084 fix(Designer): Added `isTrigger` to nodeMetadata
  apps/Standalone/src/designer/app/LocalDesigner/pseudoCommandBar.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/add.ts
  libs/designer/src/lib/core/actions/bjsworkflow/connections.ts
  libs/designer/src/lib/core/actions/bjsworkflow/initialize.ts
  libs/designer/src/lib/core/actions/bjsworkflow/operationdeserializer.ts
  libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
  libs/designer/src/lib/core/configuretemplate/utils/helper.ts
  libs/designer/src/lib/core/parsers/BJSWorkflow/BJSDeserializer.ts
  libs/designer/src/lib/core/parsers/BJSWorkflow/__test__/scopedWorkflowDefinition.ts
  libs/designer/src/lib/core/parsers/BJSWorkflow/__test__/simpleWorkflowDefinition.ts
  libs/designer/src/lib/core/parsers/BJSWorkflow/__test__/switchWorkflowDefinition.ts
  libs/designer/src/lib/core/parsers/addNodeToWorkflow.ts
  libs/designer/src/lib/core/parsers/deleteNodeFromWorkflow.ts
  libs/designer/src/lib/core/parsers/moveNodeInWorkflow.ts
  libs/designer/src/lib/core/state/__test__/workflowSlice.spec.ts
  libs/designer/src/lib/core/state/workflow/workflowInterfaces.ts
  libs/designer/src/lib/core/state/workflow/workflowSelectors.ts
  libs/designer/src/lib/core/state/workflow/workflowSlice.ts
  libs/designer/src/lib/core/templates/utils/parametershelper.ts
  libs/designer/src/lib/core/utils/__test__/graph.spec.ts
  libs/designer/src/lib/core/utils/__test__/loops.spec.ts
  libs/designer/src/lib/core/utils/graph.ts
  libs/designer/src/lib/ui/CustomNodes/OperationCardNode.tsx
  libs/designer/src/lib/ui/common/DeleteModal/DeleteModal.tsx
  libs/designer/src/lib/ui/common/DesignerContextualMenu/DesignerContextualMenu.tsx
  libs/designer/src/lib/ui/common/EdgeContextualMenu/EdgeContextualMenu.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/nodeDetailsPanel.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/mockResultsTab/mockResultsTab.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/usePanelTabs.tsx
  libs/designer/src/lib/ui/settings/index.tsx
  libs/designer/src/lib/ui/settings/sections/general.tsx
  libs/designer/src/lib/ui/settings/validation/validation.ts
Labels: Risk:Low, pr-validated

#8088 fix(vscode): Add additional conditional to show validate error message
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
Labels: Risk:Low, pr-validated

#8104 fix(localization): Remove duplicate entries from language files
  Localize/loc/de/strings.json.lcl
  Localize/loc/ja/strings.json.lcl
  Localize/loc/ko/strings.json.lcl
  Localize/loc/pt-BR/strings.json.lcl
  Localize/loc/ru/strings.json.lcl
  Localize/loc/tr/strings.json.lcl
  Localize/loc/zh-Hans/strings.json.lcl
Labels: Risk:Low, pr-validated

#8105 fix(vscode): Handle null node parameter in custom code functions build process
  apps/vs-code-designer/src/app/commands/buildCustomCodeFunctionsProject.ts
Labels: Risk:Low, pr-validated

#8107 fix(designer): Fix some strings in A2A trigger
  libs/designer-ui/src/lib/copyinputcontrol/CopyInputControlWithAgent.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/manifests/a2arequest.ts
Labels: Risk:Low, pr-validated

#8112 fix(Designer): Fixed root node run-after setting in scopes
  Localize/lang/strings.json
  libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
Labels: Risk:Low, pr-validated

#8113 fix(Designer): Fixed root node run-after setting in scopes (5.165)
  libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts
Labels: Risk:Low, pr-validated

#8111 feat(Export): Initial skeleton structure with standalone setup
  Localize/lang/strings.json
  apps/Standalone/src/App.tsx
  apps/Standalone/src/exportconsumption/app/exportconsumption.tsx
  apps/Standalone/src/exportconsumption/app/exportshell.tsx
  apps/Standalone/src/exportconsumption/app/styles.ts
  apps/Standalone/src/exportconsumption/components/devtoolbox.tsx
  apps/Standalone/src/exportconsumption/components/styles.ts
  apps/Standalone/src/exportconsumption/state/store.ts
  apps/Standalone/src/exportconsumption/state/workflowloader.ts
  libs/designer/src/lib/core/exportconsumption/exportdataprovider.tsx
  libs/designer/src/lib/core/exportconsumption/exportwizardcontext.ts
  libs/designer/src/lib/core/exportconsumption/exportwizardprovider.tsx
  libs/designer/src/lib/core/index.ts
  libs/designer/src/lib/core/state/exportconsumption/resourceslice.ts
  libs/designer/src/lib/core/state/exportconsumption/store.ts
  libs/designer/src/lib/ui/exportconsumption/wizard/exportwizard.tsx
  libs/designer/src/lib/ui/index.tsx
Labels: Risk:Low, pr-validated

#8121 feat(designer): Adding Additional Template Functions from backend
  Localize/lang/strings.json
  libs/designer-ui/src/lib/workflow/languageservice/templatefunctions.ts
Labels: Risk:Low, pr-validated

#7774 test(vscode): First clickstop for E2E testing infrastructure with ExTester and Mocha
  .github/copilot-instructions.md
  .gitignore
  apps/vs-code-designer/package.json
  apps/vs-code-designer/src/package.json
  apps/vs-code-designer/src/test/ui/README.md
  apps/vs-code-designer/src/test/ui/basic.test.ts
  apps/vs-code-designer/src/test/ui/commands.test.ts
  apps/vs-code-designer/src/test/ui/demo.test.ts
  apps/vs-code-designer/src/test/ui/smoke.test.ts
  apps/vs-code-designer/src/test/ui/standalone.test.ts
  apps/vs-code-designer/tsup.e2e.test.config.ts
  apps/vs-code-designer/vitest.config.ts
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: Risk:Low, pr-validated

#8125 fix(Designer): Update a2a trigger property names
  libs/logic-apps-shared/src/designer-client-services/lib/base/manifests/a2arequest.ts
Labels: Risk:Low, pr-validated

#8126 Add single flag to enable/disable Codeful feature in VS Code Designer
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/NewCodeProjectTypeStep.ts
  apps/vs-code-designer/src/app/commands/createWorkflow/createWorkflow.ts
  apps/vs-code-designer/src/extensionVariables.ts
  apps/vs-code-designer/src/main.ts
Labels: Risk:Low, pr-validated

#8127 feat(Clone): Rename of files to clone + cloneSlice initializaiton with resourcepicker connection
  apps/Standalone/src/App.tsx
  apps/Standalone/src/clonetostandard/app/cloneshell.tsx
  apps/Standalone/src/clonetostandard/app/clonetostandard.tsx
  apps/Standalone/src/clonetostandard/app/styles.ts
  apps/Standalone/src/clonetostandard/components/devtoolbox.tsx
  apps/Standalone/src/clonetostandard/components/styles.ts
  apps/Standalone/src/clonetostandard/state/store.ts
  apps/Standalone/src/clonetostandard/state/workflowloader.ts
  libs/designer/src/lib/core/clonetostandard/clonedataprovider.tsx
  libs/designer/src/lib/core/clonetostandard/clonewizardcontext.ts
  libs/designer/src/lib/core/clonetostandard/clonewizardprovider.tsx
  libs/designer/src/lib/core/index.ts
  libs/designer/src/lib/core/state/clonetostandard/cloneslice.ts
  libs/designer/src/lib/core/state/clonetostandard/resourceslice.ts
  libs/designer/src/lib/core/state/clonetostandard/store.ts
  libs/designer/src/lib/ui/clonetostandard/resourcepicker.tsx
  libs/designer/src/lib/ui/clonetostandard/wizard/clonewizard.tsx
  libs/designer/src/lib/ui/exportconsumption/wizard/exportwizard.tsx
  libs/designer/src/lib/ui/index.tsx
Labels: Risk:Low, pr-validated

#8131 fix(designer): Prevent Adding actions below agent if single agent
  libs/designer/src/lib/ui/common/EdgeContextualMenu/EdgeContextualMenu.tsx
Labels: Risk:Low, pr-validated

#8133 fix(Designer): Removed message param from handoff
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/handoff.ts
Labels: Risk:Low, pr-validated

#8134 fix(Designer): Removed message param from handoff (5.165)
  Localize/lang/strings.json
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/handoff.ts
Labels: Risk:Low, pr-validated

#8143 feat(Clone): Api connection using states with validation and error handling
  apps/Standalone/src/clonetostandard/app/clonetostandard.tsx
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
  libs/designer/src/lib/core/clonetostandard/clonedataprovider.tsx
  libs/designer/src/lib/core/state/clonetostandard/cloneslice.ts
  libs/designer/src/lib/core/state/clonetostandard/resourceslice.ts
  libs/designer/src/lib/ui/clonetostandard/resourcepicker.tsx
  libs/designer/src/lib/ui/clonetostandard/wizard/clonewizard.tsx
Labels: Risk:Low, pr-validated

#8148 test(vscode): refactor debug utilities and add comprehensive unit tests
  apps/vs-code-designer/src/app/commands/createCodeful/CodefulWorkflowCreateStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/FunctionAppFilesStep.ts
  apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/initLogicAppCodeProjectVScode/InitCodeProject.ts
  apps/vs-code-designer/src/app/commands/initProjectForVSCode/InitVSCodeStepBase.ts
  apps/vs-code-designer/src/app/commands/registerCommands.ts
  apps/vs-code-designer/src/app/commands/workflows/openDesigner/openDesignerForLocalProject.ts
  apps/vs-code-designer/src/app/commands/workflows/openMonitoringView/openMonitoringViewForLocal.ts
  apps/vs-code-designer/src/app/utils/__test__/bundleFeed.test.ts
  apps/vs-code-designer/src/app/utils/__test__/debug.test.ts
  apps/vs-code-designer/src/app/utils/bundleFeed.ts
  apps/vs-code-designer/src/app/utils/debug.ts
  apps/vs-code-designer/src/app/utils/getDebugSymbolDll.ts
  apps/vs-code-designer/test-setup.ts
  libs/designer-ui/src/lib/panel/recommendationpanel/operationGroupDetails/searchResult/searchResult.tsx
Labels: Risk:Low, pr-validated

#8154 feat(Clone): Incorporate tab structure + fixed subscription selection to align needs
  Localize/lang/strings.json
  libs/designer/src/lib/common/constants.ts
  libs/designer/src/lib/core/clonetostandard/clonedataprovider.tsx
  libs/designer/src/lib/core/state/clonetostandard/store.ts
  libs/designer/src/lib/core/state/clonetostandard/tabslice.ts
  libs/designer/src/lib/ui/clonetostandard/logicapps/configurelogicapps.tsx
  libs/designer/src/lib/ui/clonetostandard/logicapps/resourcepicker.tsx
  libs/designer/src/lib/ui/clonetostandard/resourcepicker.tsx
  libs/designer/src/lib/ui/clonetostandard/review/clonereviewlist.tsx
  libs/designer/src/lib/ui/clonetostandard/tabs/configuretab.tsx
  libs/designer/src/lib/ui/clonetostandard/tabs/model.tsx
  libs/designer/src/lib/ui/clonetostandard/tabs/reviewtab.tsx
  libs/designer/src/lib/ui/clonetostandard/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/clonetostandard/wizard/clonewizard.tsx
Labels: Risk:Medium, pr-validated

#8157 fix(designer): A2A string updates for different scenarios
  Localize/lang/strings.json
  libs/designer-ui/src/lib/agentinstruction/index.tsx
  libs/designer-ui/src/lib/arrayeditor/index.tsx
  libs/designer-ui/src/lib/settings/settingsection/settingTokenField.tsx
  libs/designer/src/lib/ui/common/EdgeContextualMenu/EdgeContextualMenu.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/handoffTab/HandoffToolEntry.tsx
  libs/designer/src/lib/ui/panel/nodeDetailsPanel/tabs/handoffTab/index.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/base/experimentation.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/manifests/a2arequest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/agentloop.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/manifest/handoff.ts
Labels: Risk:Low, pr-validated

#8159 fix(designer): Inline connection fix in v2
  libs/designer-v2/src/lib/ui/panel/nodeDetailsPanel/tabs/parametersTab/index.tsx
Labels: Risk:Low, pr-validated

#8156 feat(Clone): reflect figma design + support cloned workflow name + front-end validation for tab disabling
  Localize/lang/strings.json
  apps/Standalone/src/clonetostandard/app/clonetostandard.tsx
  libs/designer/src/lib/core/clonetostandard/utils/cloneStrings.ts
  libs/designer/src/lib/core/state/clonetostandard/cloneslice.ts
  libs/designer/src/lib/ui/clonetostandard/logicapps/configurelogicapps.tsx
  libs/designer/src/lib/ui/clonetostandard/logicapps/styles.ts
  libs/designer/src/lib/ui/clonetostandard/review/clonereviewlist.tsx
  libs/designer/src/lib/ui/clonetostandard/tabs/configuretab.tsx
  libs/designer/src/lib/ui/clonetostandard/tabs/model.tsx
  libs/designer/src/lib/ui/clonetostandard/tabs/reviewtab.tsx
  libs/designer/src/lib/ui/clonetostandard/tabs/useWizardTabs.tsx
  libs/designer/src/lib/ui/clonetostandard/wizard/clonewizard.tsx
  libs/designer/src/lib/ui/clonetostandard/wizard/styles.ts
  libs/designer/src/lib/ui/common/resourcepicker/resourcepicker.tsx
  libs/designer/src/lib/ui/common/resourcepicker/resourcestrings.ts
Labels: Risk:Medium, pr-validated

#8167 fix(mcp): Resetting connection store correctly on logic app change
  libs/designer/src/lib/core/actions/bjsworkflow/mcp.ts
  libs/designer/src/lib/ui/mcp/details/logicAppSelector.tsx
Labels: Risk:Low, pr-validated

#8168 feat(Clone): Clone service introduction + workflow name validation within selected resource
  Localize/lang/strings.json
  apps/Standalone/src/clonetostandard/app/clonetostandard.tsx
  libs/designer/src/lib/core/actions/bjsworkflow/clone.ts
  libs/designer/src/lib/core/clonetostandard/utils/cloneStrings.ts
  libs/designer/src/lib/core/index.ts
  libs/designer/src/lib/core/queries/clone.ts
  libs/designer/src/lib/core/state/clonetostandard/cloneslice.ts
  libs/designer/src/lib/ui/clonetostandard/logicapps/configurelogicapps.tsx
  libs/designer/src/lib/ui/clonetostandard/review/clonereviewlist.tsx
  libs/designer/src/lib/ui/clonetostandard/tabs/configuretab.tsx
  libs/designer/src/lib/ui/clonetostandard/tabs/model.tsx
  libs/designer/src/lib/ui/clonetostandard/tabs/reviewtab.tsx
  libs/designer/src/lib/ui/clonetostandard/tabs/useWizardTabs.tsx
  libs/logic-apps-shared/src/designer-client-services/index.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/clone.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/index.ts
  libs/logic-apps-shared/src/designer-client-services/lib/clone.ts
Labels: Risk:Low, pr-validated

#8169 feat(DesignerV2): Run history panel improvements
  Localize/lang/strings.json
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/laDesignerV2.tsx
  libs/designer-v2/src/lib/common/images/status_cancelled.svg
  libs/designer-v2/src/lib/core/queries/runs.ts
  libs/designer-v2/src/lib/ui/Designer.styles.ts
  libs/designer-v2/src/lib/ui/Designer.tsx
  libs/designer-v2/src/lib/ui/MonitoringTimeline/index.tsx
  libs/designer-v2/src/lib/ui/MonitoringTimeline/monitoringTimeline.styles.ts
  libs/designer-v2/src/lib/ui/panel/runHistoryPanel/runHistoryEntry.tsx
  libs/designer-v2/src/lib/ui/panel/runHistoryPanel/runHistoryPanel.styles.ts
  libs/designer-v2/src/lib/ui/panel/runHistoryPanel/runHistoryPanel.tsx
  libs/designer-v2/src/lib/ui/panel/runHistoryPanel/runMenu.tsx
  libs/designer-v2/src/lib/ui/panel/runHistoryPanel/runPopover.tsx
  libs/designer-v2/src/lib/ui/panel/runHistoryPanel/statusIndicator.tsx
  libs/logic-apps-shared/src/designer-client-services/lib/consumption/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/run.ts
  libs/logic-apps-shared/src/designer-client-services/lib/standard/run.ts
Labels: Risk:Low, pr-validated

#8176 fix(designer): Move description under advanced parameters
  libs/designer-ui/src/lib/searchabledropdownWithAddAll/index.tsx
  libs/designer/src/lib/ui/settings/settingsection.tsx
Labels: Risk:Low, pr-validated

#8177 fix(designer): Move description under advanced parameters (#8176)
  libs/designer-ui/src/lib/searchabledropdownWithAddAll/index.tsx
  libs/designer/src/lib/ui/settings/settingsection.tsx
Labels: Risk:Low, pr-validated

#8178 fix(designer): Add try catch for Easy Auth call
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
Labels: Risk:Low, pr-validated

#8181 fix(designer): [Cherry-pick] Add try catch for Easy Auth call (#8178)
  apps/Standalone/src/designer/app/AzureLogicAppsDesigner/Services/WorkflowAndArtifacts.tsx
Labels: Risk:Low, pr-validated

#8174 feat(vscode): Add single flag to enable/disable Codeful feature in VS Code Designer
  apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/NewCodeProjectTypeStep.ts
  apps/vs-code-designer/src/app/commands/createWorkflow/createWorkflow.ts
  apps/vs-code-designer/src/extensionVariables.ts
  apps/vs-code-designer/src/main.ts
Labels: Risk:Low, pr-validated

#8180 feat(DesignerV2): Node + Edge redesign
  apps/Standalone/src/App.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/CollapsedCardNode.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/GraphContainerNode.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/HiddenNode.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/OperationCardNode.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/PlaceholderNode.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/ScopeCardNode.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/SubgraphCardNode.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/__test__/__snapshots__/GraphContainerNode.spec.tsx.snap
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/card.styles.ts
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/cardStatusBadge.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/index.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/keyboardInteraction.ts
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/svgs/failure.svg
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/svgs/skip.svg
  libs/designer-v2/src/lib/ui/CustomNodes/components/card/svgs/success.svg
  libs/designer-v2/src/lib/ui/CustomNodes/components/handles/DefaultHandle.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/components/handles/EdgeDrawSourceHandle.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/components/handles/EdgeDrawTargetHandle.tsx
  libs/designer-v2/src/lib/ui/CustomNodes/components/handles/handles.styles.ts
  libs/designer-v2/src/lib/ui/Designer.styles.ts
  libs/designer-v2/src/lib/ui/Designer.tsx
  libs/designer-v2/src/lib/ui/MonitoringTimeline/monitoringTimeline.styles.ts
  libs/designer-v2/src/lib/ui/connections/addButton/addButton.styles.ts
  libs/designer-v2/src/lib/ui/connections/addButton/index.tsx
  libs/designer-v2/src/lib/ui/connections/addButton/plus.tsx
  libs/designer-v2/src/lib/ui/connections/dropzone.tsx
  libs/designer-v2/src/lib/ui/connections/dynamicsvgs/arrowCap.tsx
  libs/designer-v2/src/lib/ui/connections/edge.tsx
  libs/designer-v2/src/lib/ui/styles.less
  libs/logic-apps-shared/src/utils/src/lib/helpers/index.ts
  libs/logic-apps-shared/src/utils/src/lib/helpers/keyboard.ts
Labels: Risk:Low, pr-validated

#8179 Feat(DesignerV2): Redesign Search Panel with Categories, Favorites, and Connector Virtualization
  Localize/lang/strings.json
  apps/Standalone/package.json
  libs/designer-ui/src/lib/panel/panelUtil.ts
  libs/designer-ui/src/lib/panel/recommendationpanel/Grid.styles.ts
  libs/designer-ui/src/lib/panel/recommendationpanel/browseResultsV2.tsx
  libs/designer-ui/src/lib/panel/recommendationpanel/index.tsx
  libs/designer-ui/src/lib/panel/recommendationpanel/operationGroupDetails/searchResult/searchResultV2.tsx
  libs/designer-ui/src/lib/panel/recommendationpanel/operationSearchHeader/OperationSearchHeaderV2.tsx
  libs/designer-ui/src/lib/panel/recommendationpanel/recommendation.less
  libs/designer-v2/package.json
  libs/designer-v2/src/lib/core/queries/browse.ts
  libs/designer-v2/src/lib/core/state/panel/panelSelectors.ts
  libs/designer-v2/src/lib/core/state/panel/panelSlice.ts
  libs/designer-v2/src/lib/core/state/panel/panelTypes.ts
  libs/designer-v2/src/lib/ui/panel/panelRoot.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/SearchOpeationsService.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/actionSpotlight.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/browse/browseView.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/browse/categoryCard.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/browse/connectorBrowse.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/browse/connectorCard.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/browse/helper.ts
  libs/designer-v2/src/lib/ui/panel/recommendation/browse/styles/BrowseView.styles.ts
  libs/designer-v2/src/lib/ui/panel/recommendation/browse/styles/CategoryCard.styles.ts
  libs/designer-v2/src/lib/ui/panel/recommendation/browse/styles/ConnectorBrowse.styles.ts
  libs/designer-v2/src/lib/ui/panel/recommendation/browse/styles/ConnectorCard.styles.ts
  libs/designer-v2/src/lib/ui/panel/recommendation/browseView.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/categories/Favorites.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/categories/styles/Favorites.styles.ts
  libs/designer-v2/src/lib/ui/panel/recommendation/customSwaggerSelection.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/details/connectorDetailsView.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/details/operationAccordionItem.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/details/operationsAccordion.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/details/styles/ConnectorDetailsView.styles.ts
  libs/designer-v2/src/lib/ui/panel/recommendation/details/styles/OperationsAccordion.styles.ts
  libs/designer-v2/src/lib/ui/panel/recommendation/helpers.ts
  libs/designer-v2/src/lib/ui/panel/recommendation/operationGroupDetailView.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/recommendationPanelContext.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/searchView.tsx
  libs/designer-v2/src/lib/ui/panel/recommendation/styles/RecommendationPanelContext.styles.ts
  libs/designer-v2/tsconfig.json
  libs/logic-apps-shared/src/designer-client-services/lib/base/manifests/a2arequest.ts
  libs/logic-apps-shared/src/designer-client-services/lib/base/operations/agent.ts
  libs/logic-apps-shared/src/utils/src/lib/mocks/connectorsSearchResultsMock.ts
  package.json
  pnpm-lock.yaml
Labels: Risk:Medium, pr-validated

#8184 feat(designerv2): New placeholder trigger UI
  Localize/lang/strings.json
  libs/designer-ui/src/lib/card/addActionCard/AddActionCardV2.tsx
  libs/designer-ui/src/lib/card/addActionCard/addActionCardV2.styles.ts
  libs/designer-ui/src/lib/index.ts
  libs/designer-v2/src/lib/core/state/workflow/workflowSlice.ts
  libs/designer-v2/src/lib/ui/CustomNodes/PlaceholderNode.tsx
Labels: Risk:Low, pr-validated
